name: Setup
description: Setup pnpm, Node 22 and install project dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/
        cache: pnpm

    - name: Install project dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts

    - name: Generate SvelteKit types
      shell: bash
      run: pnpm exec svelte-kit sync
