import type { EspeceProtegeeModificationInitializer } from "@pitchou/types/database/public/EspeceProtegeeModification.ts";

export const AJOUTS_CHUNK_1: EspeceProtegeeModificationInitializer[] = [
  {
    cd_ref: "3429",
    classification: "oiseau",
    noms_scientifiques: [
      "Streptopelia decaocto",
      "Columba decaocto",
      "Columba risoria L. var. decaocto",
    ],
    noms_vernaculaires: ["Tourterelle turque"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "60658",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Martes martes",
      "Martes abietum",
      "Martes latinorum",
      "Martes martes lorenzi",
      "Martes martes martes",
      "Martes martes sabaneevi",
      "Martes martes uralensis",
      "Martes notialis",
      "Martes ruthena",
      "Martes sylvestris",
      "Martes vulgaris",
      "Mustela martes",
    ],
    noms_vernaculaires: ["Martre des pins", "Martre"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "60674",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Martes foina",
      "Martes foina bunites",
      "Martes foina foina",
      "Martes foina milleri",
      "Mustela alba",
      "Mustela bosniaca",
      "Mustela domestica",
      "Mustela foina",
      "Mustela mediterranea",
      "Mustela mehringi",
    ],
    noms_vernaculaires: ["Fouine"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "60686",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Mustela erminea"],
    noms_vernaculaires: ["Hermine"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "60716",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Mustela nivalis",
      "Mustela alpinus",
      "Mustela boccamela",
      "Mustela corsicana",
      "Mustela ibericus",
      "Mustela italicus",
      "Mustela meridionalis",
      "Mustela minor",
      "Mustela minutus",
      "Mustela monticola",
      "Mustela nivalis boccamela",
      "Mustela nivalis corsicana",
      "Mustela nivalis nivalis",
      "Mustela nivalis vulgaris",
      "Mustela typicus",
      "Mustela vulgaris",
    ],
    noms_vernaculaires: ["Belette d'Europe", "Belette"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "60731",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Mustela putorius",
      "Mustela albus",
      "Mustela anglia",
      "Mustela aureola",
      "Mustela caledoniae",
      "Mustela foetens",
      "Mustela furo-putorius",
      "Mustela iltis",
      "Mustela infectus",
      "Mustela orientalis",
      "Mustela putorius putorius",
      "Mustela rotschildi",
      "Mustela stantschinskii",
      "Putorius putorius",
    ],
    noms_vernaculaires: ["Putois d'Europe", "Putois", "Furet"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "106678",
    classification: "flore",
    noms_scientifiques: [
      "Lotus hispidus",
      "Lotus angustissimus subsp. hispidus",
      "Lotus angustissimus subsp. suaveolens",
      "Lotus approximatus",
      "Lotus divaricatus",
      "Lotus fallax",
      "Lotus hispidus var. filiformis",
      "Lotus hispidus var. littoralis",
      "Lotus hispidus var. major",
      "Lotus levieri",
      "Lotus odoratus",
      "Lotus pilosissimus var. filiformis",
      "Lotus pilosissimus",
      "Lotus stagnalis",
      "Lotus suaveolens",
      "Lotus subbiflorus",
    ],
    noms_vernaculaires: ["Lotier hispide"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "185961",
    classification: "oiseau",
    noms_scientifiques: ["Aves"],
    noms_vernaculaires: ["Oiseaux"],
    cd_type_statuts: ["Espèce manquante"],
  },
  {
    cd_ref: "186194",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Myliobatidae"],
    noms_vernaculaires: ["Raies"],
    cd_type_statuts: ["Espèce manquante"],
  },
] as unknown as EspeceProtegeeModificationInitializer[];
