// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type GroupeInstructeursId } from './GroupeInstructeurs';
import { type PersonneId } from './Personne';

/** Represents the table public.arête_groupe_instructeurs__personne */
export default interface ArTeGroupeInstructeursPersonne {
  groupe_instructeurs: GroupeInstructeursId;

  personne: PersonneId;
}

/** Represents the initializer for the table public.arête_groupe_instructeurs__personne */
export interface ArTeGroupeInstructeursPersonneInitializer {
  groupe_instructeurs: GroupeInstructeursId;

  personne: PersonneId;
}

/** Represents the mutator for the table public.arête_groupe_instructeurs__personne */
export interface ArTeGroupeInstructeursPersonneMutator {
  groupe_instructeurs?: GroupeInstructeursId;

  personne?: PersonneId;
}
