// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from './Dossier';
import type { FichierId } from './Fichier';

/** Represents the table public.arête_dossier__fichier_pièces_jointes_pétitionnaire */
export default interface ArTeDossierFichierPiCesJointesPTitionnaire {
  dossier: DossierId;

  fichier: FichierId;
}

/** Represents the initializer for the table public.arête_dossier__fichier_pièces_jointes_pétitionnaire */
export interface ArTeDossierFichierPiCesJointesPTitionnaireInitializer {
  dossier: DossierId;

  fichier: FichierId;
}

/** Represents the mutator for the table public.arête_dossier__fichier_pièces_jointes_pétitionnaire */
export interface ArTeDossierFichierPiCesJointesPTitionnaireMutator {
  dossier?: DossierId;

  fichier?: FichierId;
}
