// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CapCritureAnnotationCap } from './CapÉcritureAnnotation';

/** Represents the table public.arête_personne__cap_écriture_annotation */
export default interface ArTePersonneCapCritureAnnotation {
  personne_cap: string | null;

  écriture_annotation_cap: CapCritureAnnotationCap | null;
}

/** Represents the initializer for the table public.arête_personne__cap_écriture_annotation */
export interface ArTePersonneCapCritureAnnotationInitializer {
  personne_cap?: string | null;

  écriture_annotation_cap?: CapCritureAnnotationCap | null;
}

/** Represents the mutator for the table public.arête_personne__cap_écriture_annotation */
export interface ArTePersonneCapCritureAnnotationMutator {
  personne_cap?: string | null;

  écriture_annotation_cap?: CapCritureAnnotationCap | null;
}
