// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from './Personne';
import type { DossierId } from './Dossier';

/** Represents the table public.arête_personne_suit_dossier */
export default interface ArTePersonneSuitDossier {
  personne: PersonneId;

  dossier: DossierId;
}

/** Represents the initializer for the table public.arête_personne_suit_dossier */
export interface ArTePersonneSuitDossierInitializer {
  personne: PersonneId;

  dossier: DossierId;
}

/** Represents the mutator for the table public.arête_personne_suit_dossier */
export interface ArTePersonneSuitDossierMutator {
  personne?: PersonneId;

  dossier?: DossierId;
}
