// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CapDossierCap } from './CapDossier';
import { type GroupeInstructeursId } from './GroupeInstructeurs';

/** Represents the table public.arête_cap_dossier__groupe_instructeurs */
export default interface ArTeCapDossierGroupeInstructeurs {
  cap_dossier: CapDossierCap;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the initializer for the table public.arête_cap_dossier__groupe_instructeurs */
export interface ArTeCapDossierGroupeInstructeursInitializer {
  cap_dossier: CapDossierCap;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the mutator for the table public.arête_cap_dossier__groupe_instructeurs */
export interface ArTeCapDossierGroupeInstructeursMutator {
  cap_dossier?: CapDossierCap;

  groupe_instructeurs?: GroupeInstructeursId;
}
