// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from './Dossier';
import type { FichierId } from './Fichier';

/** Identifier type for public.avis_expert */
export type AvisExpertId = string & { __brand: 'public.avis_expert' };

/** Represents the table public.avis_expert */
export default interface AvisExpert {
  id: AvisExpertId;

  dossier: DossierId;

  /** Instance consultée pour avis sur la dérogation (ex. : CSRPN, CNPN, autre autorité compétente). */
  expert: string | null;

  /** Date à laquelle l'expert a été officiellement saisi pour avis. */
  date_saisine: Date | null;

  /** Fichier transmis lors de la saisine de l'expert. */
  saisine_fichier: FichierId | null;

  /** Nature de l'avis émis par l'expert (ex. : Favorable, Favorable sous conditions, Défavorable, Non renseigné). */
  avis: string | null;

  /** Date de formulation ou de réception de l'avis de l'expert. */
  date_avis: Date | null;

  /** Fichier contenant l'avis formel de l'expert. */
  avis_fichier: FichierId | null;
}

/** Represents the initializer for the table public.avis_expert */
export interface AvisExpertInitializer {
  /** Default value: gen_random_uuid() */
  id?: AvisExpertId;

  dossier: DossierId;

  /** Instance consultée pour avis sur la dérogation (ex. : CSRPN, CNPN, autre autorité compétente). */
  expert?: string | null;

  /** Date à laquelle l'expert a été officiellement saisi pour avis. */
  date_saisine?: Date | null;

  /** Fichier transmis lors de la saisine de l'expert. */
  saisine_fichier?: FichierId | null;

  /** Nature de l'avis émis par l'expert (ex. : Favorable, Favorable sous conditions, Défavorable, Non renseigné). */
  avis?: string | null;

  /** Date de formulation ou de réception de l'avis de l'expert. */
  date_avis?: Date | null;

  /** Fichier contenant l'avis formel de l'expert. */
  avis_fichier?: FichierId | null;
}

/** Represents the mutator for the table public.avis_expert */
export interface AvisExpertMutator {
  id?: AvisExpertId;

  dossier?: DossierId;

  /** Instance consultée pour avis sur la dérogation (ex. : CSRPN, CNPN, autre autorité compétente). */
  expert?: string | null;

  /** Date à laquelle l'expert a été officiellement saisi pour avis. */
  date_saisine?: Date | null;

  /** Fichier transmis lors de la saisine de l'expert. */
  saisine_fichier?: FichierId | null;

  /** Nature de l'avis émis par l'expert (ex. : Favorable, Favorable sous conditions, Défavorable, Non renseigné). */
  avis?: string | null;

  /** Date de formulation ou de réception de l'avis de l'expert. */
  date_avis?: Date | null;

  /** Fichier contenant l'avis formel de l'expert. */
  avis_fichier?: FichierId | null;
}
