// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.capability-geomce */
export type CapabilityGeomceSecret = string & { __brand: 'public.capability-geomce' };

/** Represents the table public.capability-geomce */
export default interface CapabilityGeomce {
  /** Cette table n'a qu'une seule ligne, une seule valeur */
  secret: CapabilityGeomceSecret;
}

/** Represents the initializer for the table public.capability-geomce */
export interface CapabilityGeomceInitializer {
  /**
   * Cette table n'a qu'une seule ligne, une seule valeur
   * Default value: gen_random_uuid()
   */
  secret?: CapabilityGeomceSecret;
}

/** Represents the mutator for the table public.capability-geomce */
export interface CapabilityGeomceMutator {
  /** Cette table n'a qu'une seule ligne, une seule valeur */
  secret?: CapabilityGeomceSecret;
}
