// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cap_dossier */
export type CapDossierCap = string & { __brand: 'CapDossierCap' };

/** Represents the table public.cap_dossier */
export default interface CapDossier {
  cap: CapDossierCap;

  personne_cap: string;
}

/** Represents the initializer for the table public.cap_dossier */
export interface CapDossierInitializer {
  /** Default value: gen_random_uuid() */
  cap?: CapDossierCap;

  personne_cap: string;
}

/** Represents the mutator for the table public.cap_dossier */
export interface CapDossierMutator {
  cap?: CapDossierCap;

  personne_cap?: string;
}
