// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cap_notification */
export type CapNotificationCap = string & { __brand: 'public.cap_notification' };

/** Represents the table public.cap_notification */
export default interface CapNotification {
  cap: CapNotificationCap;

  personne_cap: string;
}

/** Represents the initializer for the table public.cap_notification */
export interface CapNotificationInitializer {
  /** Default value: gen_random_uuid() */
  cap?: CapNotificationCap;

  personne_cap: string;
}

/** Represents the mutator for the table public.cap_notification */
export interface CapNotificationMutator {
  cap?: CapNotificationCap;

  personne_cap?: string;
}
