// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cap_écriture_annotation */
export type CapCritureAnnotationCap = string & { __brand: 'public.cap_écriture_annotation' };

/** Represents the table public.cap_écriture_annotation */
export default interface CapCritureAnnotation {
  cap: CapCritureAnnotationCap;

  /** Identifiant de l'instructeur.rice dans Démarches Simplifiées. Utile pour faire référence à l'instructeur.rice dans les appels API */
  instructeur_id: string;
}

/** Represents the initializer for the table public.cap_écriture_annotation */
export interface CapCritureAnnotationInitializer {
  /** Default value: gen_random_uuid() */
  cap?: CapCritureAnnotationCap;

  /** Identifiant de l'instructeur.rice dans Démarches Simplifiées. Utile pour faire référence à l'instructeur.rice dans les appels API */
  instructeur_id: string;
}

/** Represents the mutator for the table public.cap_écriture_annotation */
export interface CapCritureAnnotationMutator {
  cap?: CapCritureAnnotationCap;

  /** Identifiant de l'instructeur.rice dans Démarches Simplifiées. Utile pour faire référence à l'instructeur.rice dans les appels API */
  instructeur_id?: string;
}
