// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cap_écriture_annotation */
export type CapCritureAnnotationCap = string & { __brand: 'CapCritureAnnotationCap' };

/** Represents the table public.cap_écriture_annotation */
export default interface CapCritureAnnotation {
  cap: CapCritureAnnotationCap;

  instructeur_id: string;
}

/** Represents the initializer for the table public.cap_écriture_annotation */
export interface CapCritureAnnotationInitializer {
  /** Default value: gen_random_uuid() */
  cap?: CapCritureAnnotationCap;

  instructeur_id: string;
}

/** Represents the mutator for the table public.cap_écriture_annotation */
export interface CapCritureAnnotationMutator {
  cap?: CapCritureAnnotationCap;

  instructeur_id?: string;
}
