// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cap_évènement_métrique */
export type CapVNementMTriqueCap = string & { __brand: 'public.cap_évènement_métrique' };

/** Represents the table public.cap_évènement_métrique */
export default interface CapVNementMTrique {
  cap: CapVNementMTriqueCap;

  personne_cap: string;
}

/** Represents the initializer for the table public.cap_évènement_métrique */
export interface CapVNementMTriqueInitializer {
  /** Default value: gen_random_uuid() */
  cap?: CapVNementMTriqueCap;

  personne_cap: string;
}

/** Represents the mutator for the table public.cap_évènement_métrique */
export interface CapVNementMTriqueMutator {
  cap?: CapVNementMTriqueCap;

  personne_cap?: string;
}
