// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PrescriptionId } from './Prescription';

/** Identifier type for public.contrôle */
export type ContrLeId = string & { __brand: 'public.contrôle' };

/** Represents the table public.contrôle */
export default interface ContrLe {
  id: ContrLeId;

  prescription: PrescriptionId;

  date_contrôle: Date | null;

  /** Pour le moment, c'est une string. Et après un certain temps, on pourra refermer les valeurs à un ensemble fini */
  résultat: string | null;

  commentaire: string | null;

  /** Pour le moment, c'est une string. Et après un certain temps, on pourra refermer les valeurs à un ensemble fini */
  type_action_suite_contrôle: string | null;

  date_action_suite_contrôle: Date | null;

  date_prochaine_échéance: Date | null;
}

/** Represents the initializer for the table public.contrôle */
export interface ContrLeInitializer {
  /** Default value: gen_random_uuid() */
  id?: ContrLeId;

  prescription: PrescriptionId;

  date_contrôle?: Date | null;

  /** Pour le moment, c'est une string. Et après un certain temps, on pourra refermer les valeurs à un ensemble fini */
  résultat?: string | null;

  commentaire?: string | null;

  /** Pour le moment, c'est une string. Et après un certain temps, on pourra refermer les valeurs à un ensemble fini */
  type_action_suite_contrôle?: string | null;

  date_action_suite_contrôle?: Date | null;

  date_prochaine_échéance?: Date | null;
}

/** Represents the mutator for the table public.contrôle */
export interface ContrLeMutator {
  id?: ContrLeId;

  prescription?: PrescriptionId;

  date_contrôle?: Date | null;

  /** Pour le moment, c'est une string. Et après un certain temps, on pourra refermer les valeurs à un ensemble fini */
  résultat?: string | null;

  commentaire?: string | null;

  /** Pour le moment, c'est une string. Et après un certain temps, on pourra refermer les valeurs à un ensemble fini */
  type_action_suite_contrôle?: string | null;

  date_action_suite_contrôle?: Date | null;

  date_prochaine_échéance?: Date | null;
}
