// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from './Personne';
import type { EntrepriseSiret } from './Entreprise';
import type { FichierId } from './Fichier';

/** Identifier type for public.dossier */
export type DossierId = number & { __brand: 'public.dossier' };

/** Represents the table public.dossier */
export default interface Dossier {
  /** Identifiant unique auto-incrémenté du dossier */
  id: DossierId;

  /** Identifiant unique du dossier dans la plateforme Démarches Simplifiées */
  id_demarches_simplifiées: string | null;

  /** Date à laquelle la demande de dérogation Espèce Protégée a été reçue par les instructeur.i.ces. */
  date_dépôt: Date;

  /** Liste des espèces protégées concernées par le dossier */
  espèces_protégées_concernées: string | null;

  /** Liste des départements concernés par le projet */
  départements: unknown | null;

  /** Liste des communes concernées par le projet */
  communes: unknown | null;

  /** Le déposant est la personne qui dépose le dossier sur DS\n        Dans certaines situations, cette personne est différente du demandeur (personne morale ou physique \n        qui demande la dérogation), par exemple, si un bureau d'étude mandaté par une personne morale dépose \n        le dossier\n        Le déposant n'est pas forcément représentant interne (point de contact principale) du demandeur\n \n        Dans la nomenclature DS, ce que nous appelons "déposant" se trouve dans la propriété "demandeur" \n        (qui est différent de notre "demandeur") */
  déposant: PersonneId | null;

  /** Si le demandeur est une personne physique, ce champ est non nul */
  demandeur_personne_physique: PersonneId | null;

  /** Si le demandeur est une personne morale, ce champ est non nul */
  demandeur_personne_morale: EntrepriseSiret | null;

  /** Liste des régions concernées par le projet */
  régions: unknown | null;

  /** Nom du projet */
  nom: string | null;

  /** Numéro du dossier dans Démarches Simplifiées */
  number_demarches_simplifiées: string | null;

  /** Nom du porteur de projet dans les Annotations Privées */
  historique_nom_porteur: string | null;

  /** Localisation du projet dans les Annotations Privées */
  historique_localisation: string | null;

  /** Indique si une demande de dérogation est nécessaire pour ce dossier */
  ddep_nécessaire: string | null;

  /** Indique si le dossier présente un enjeu politique */
  enjeu_politique: boolean | null;

  /** Commentaires libres sur le dossier remplis par l'instructeurice */
  commentaire_libre: string | null;

  historique_date_envoi_dernière_contribution: Date | null;

  /** Identifiant de la demande dans ONAGRE */
  historique_identifiant_demande_onagre: string | null;

  /** Date de saisine du CSRPN (Conseil Scientifique Régional du Patrimoine Naturel) */
  historique_date_saisine_csrpn: Date | null;

  /** Date de saisine du CNPN (Conseil National de Protection de la Nature) */
  historique_date_saisine_cnpn: Date | null;

  /** Date de l'avis du CSRPN */
  date_avis_csrpn: Date | null;

  /** Date de l'avis du CNPN */
  date_avis_cnpn: Date | null;

  /** Avis du CSRPN ou du CNPN */
  avis_csrpn_cnpn: string | null;

  /** Date de la consultation publique */
  date_consultation_public: Date | null;

  /** Indique si le dossier présente un enjeu écologique */
  enjeu_écologique: boolean | null;

  /** Indique si le dossier est rattaché au régime d'Autorisation Environnementale */
  rattaché_au_régime_ae: boolean | null;

  /** Indique qui doit effectuer la prochaine action (Instructeur, pétitionnaire, expert...) */
  prochaine_action_attendue_par: string | null;

  /** Activité principale relative au dossier (Aménagements fonciers (AFAF, remembrement), Transport hydrocarbures, Destruction de nids d'Hirondelles...) */
  activité_principale: string | null;

  /** Référence vers le fichier des espèces impactées */
  espèces_impactées: FichierId | null;

  /** Description synthétique du projet */
  description: string | null;

  /** Date de début de l'intervention */
  date_début_intervention: Date | null;

  /** Date de fin de l'intervention */
  date_fin_intervention: Date | null;

  /** Peut être différente de (date_fin_intervention - date_début_intervention) dans le cas des dérogations pluri-annuelles avec une petite période d'intervention annuelle */
  durée_intervention: number | null;

  /** Type de demande scientifique */
  scientifique_type_demande: string[] | null;

  /** Description du protocole de suivi scientifique */
  scientifique_description_protocole_suivi: string | null;

  /** Modes de capture utilisés */
  scientifique_mode_capture: string[] | null;

  /** null signifie qu'il n'y a pas d'utilisation de sources lumineuses */
  scientifique_modalités_source_lumineuses: string | null;

  /** Modalités de marquage des individus */
  scientifique_modalités_marquage: string | null;

  /** Modalités de transport des individus */
  scientifique_modalités_transport: string | null;

  /** Périmètre géographique de l'intervention scientifique */
  scientifique_périmètre_intervention: string | null;

  /** Liste des intervenants scientifiques */
  scientifique_intervenants: unknown | null;

  /** Précisions sur les autres intervenants scientifiques */
  scientifique_précisions_autres_intervenants: string | null;

  /** Article L411-2 I.4 du code de l'environnement */
  justification_absence_autre_solution_satisfaisante: string | null;

  /** Article L411-2 I.4 a) b) c) d) e) du code de l'environnement */
  motif_dérogation: string | null;

  /** Justification du motif de dérogation */
  justification_motif_dérogation: string | null;

  /** Indique si des mesures ERC (Éviter, Réduire, Compenser) sont prévues */
  mesures_erc_prévues: boolean | null;
}

/** Represents the initializer for the table public.dossier */
export interface DossierInitializer {
  /** Identifiant unique auto-incrémenté du dossier */
  id: DossierId;

  /** Identifiant unique du dossier dans la plateforme Démarches Simplifiées */
  id_demarches_simplifiées?: string | null;

  /** Date à laquelle la demande de dérogation Espèce Protégée a été reçue par les instructeur.i.ces. */
  date_dépôt: Date;

  /** Liste des espèces protégées concernées par le dossier */
  espèces_protégées_concernées?: string | null;

  /** Liste des départements concernés par le projet */
  départements?: unknown | null;

  /** Liste des communes concernées par le projet */
  communes?: unknown | null;

  /** Le déposant est la personne qui dépose le dossier sur DS\n        Dans certaines situations, cette personne est différente du demandeur (personne morale ou physique \n        qui demande la dérogation), par exemple, si un bureau d'étude mandaté par une personne morale dépose \n        le dossier\n        Le déposant n'est pas forcément représentant interne (point de contact principale) du demandeur\n \n        Dans la nomenclature DS, ce que nous appelons "déposant" se trouve dans la propriété "demandeur" \n        (qui est différent de notre "demandeur") */
  déposant?: PersonneId | null;

  /** Si le demandeur est une personne physique, ce champ est non nul */
  demandeur_personne_physique?: PersonneId | null;

  /** Si le demandeur est une personne morale, ce champ est non nul */
  demandeur_personne_morale?: EntrepriseSiret | null;

  /** Liste des régions concernées par le projet */
  régions?: unknown | null;

  /** Nom du projet */
  nom?: string | null;

  /** Numéro du dossier dans Démarches Simplifiées */
  number_demarches_simplifiées?: string | null;

  /** Nom du porteur de projet dans les Annotations Privées */
  historique_nom_porteur?: string | null;

  /** Localisation du projet dans les Annotations Privées */
  historique_localisation?: string | null;

  /** Indique si une demande de dérogation est nécessaire pour ce dossier */
  ddep_nécessaire?: string | null;

  /** Indique si le dossier présente un enjeu politique */
  enjeu_politique?: boolean | null;

  /** Commentaires libres sur le dossier remplis par l'instructeurice */
  commentaire_libre?: string | null;

  historique_date_envoi_dernière_contribution?: Date | null;

  /** Identifiant de la demande dans ONAGRE */
  historique_identifiant_demande_onagre?: string | null;

  /** Date de saisine du CSRPN (Conseil Scientifique Régional du Patrimoine Naturel) */
  historique_date_saisine_csrpn?: Date | null;

  /** Date de saisine du CNPN (Conseil National de Protection de la Nature) */
  historique_date_saisine_cnpn?: Date | null;

  /** Date de l'avis du CSRPN */
  date_avis_csrpn?: Date | null;

  /** Date de l'avis du CNPN */
  date_avis_cnpn?: Date | null;

  /** Avis du CSRPN ou du CNPN */
  avis_csrpn_cnpn?: string | null;

  /** Date de la consultation publique */
  date_consultation_public?: Date | null;

  /** Indique si le dossier présente un enjeu écologique */
  enjeu_écologique?: boolean | null;

  /** Indique si le dossier est rattaché au régime d'Autorisation Environnementale */
  rattaché_au_régime_ae?: boolean | null;

  /** Indique qui doit effectuer la prochaine action (Instructeur, pétitionnaire, expert...) */
  prochaine_action_attendue_par?: string | null;

  /** Activité principale relative au dossier (Aménagements fonciers (AFAF, remembrement), Transport hydrocarbures, Destruction de nids d'Hirondelles...) */
  activité_principale?: string | null;

  /** Référence vers le fichier des espèces impactées */
  espèces_impactées?: FichierId | null;

  /** Description synthétique du projet */
  description?: string | null;

  /** Date de début de l'intervention */
  date_début_intervention?: Date | null;

  /** Date de fin de l'intervention */
  date_fin_intervention?: Date | null;

  /** Peut être différente de (date_fin_intervention - date_début_intervention) dans le cas des dérogations pluri-annuelles avec une petite période d'intervention annuelle */
  durée_intervention?: number | null;

  /** Type de demande scientifique */
  scientifique_type_demande?: string[] | null;

  /** Description du protocole de suivi scientifique */
  scientifique_description_protocole_suivi?: string | null;

  /** Modes de capture utilisés */
  scientifique_mode_capture?: string[] | null;

  /** null signifie qu'il n'y a pas d'utilisation de sources lumineuses */
  scientifique_modalités_source_lumineuses?: string | null;

  /** Modalités de marquage des individus */
  scientifique_modalités_marquage?: string | null;

  /** Modalités de transport des individus */
  scientifique_modalités_transport?: string | null;

  /** Périmètre géographique de l'intervention scientifique */
  scientifique_périmètre_intervention?: string | null;

  /** Liste des intervenants scientifiques */
  scientifique_intervenants?: unknown | null;

  /** Précisions sur les autres intervenants scientifiques */
  scientifique_précisions_autres_intervenants?: string | null;

  /** Article L411-2 I.4 du code de l'environnement */
  justification_absence_autre_solution_satisfaisante?: string | null;

  /** Article L411-2 I.4 a) b) c) d) e) du code de l'environnement */
  motif_dérogation?: string | null;

  /** Justification du motif de dérogation */
  justification_motif_dérogation?: string | null;

  /** Indique si des mesures ERC (Éviter, Réduire, Compenser) sont prévues */
  mesures_erc_prévues?: boolean | null;
}

/** Represents the mutator for the table public.dossier */
export interface DossierMutator {
  /** Identifiant unique auto-incrémenté du dossier */
  id?: DossierId;

  /** Identifiant unique du dossier dans la plateforme Démarches Simplifiées */
  id_demarches_simplifiées?: string | null;

  /** Date à laquelle la demande de dérogation Espèce Protégée a été reçue par les instructeur.i.ces. */
  date_dépôt?: Date;

  /** Liste des espèces protégées concernées par le dossier */
  espèces_protégées_concernées?: string | null;

  /** Liste des départements concernés par le projet */
  départements?: unknown | null;

  /** Liste des communes concernées par le projet */
  communes?: unknown | null;

  /** Le déposant est la personne qui dépose le dossier sur DS\n        Dans certaines situations, cette personne est différente du demandeur (personne morale ou physique \n        qui demande la dérogation), par exemple, si un bureau d'étude mandaté par une personne morale dépose \n        le dossier\n        Le déposant n'est pas forcément représentant interne (point de contact principale) du demandeur\n \n        Dans la nomenclature DS, ce que nous appelons "déposant" se trouve dans la propriété "demandeur" \n        (qui est différent de notre "demandeur") */
  déposant?: PersonneId | null;

  /** Si le demandeur est une personne physique, ce champ est non nul */
  demandeur_personne_physique?: PersonneId | null;

  /** Si le demandeur est une personne morale, ce champ est non nul */
  demandeur_personne_morale?: EntrepriseSiret | null;

  /** Liste des régions concernées par le projet */
  régions?: unknown | null;

  /** Nom du projet */
  nom?: string | null;

  /** Numéro du dossier dans Démarches Simplifiées */
  number_demarches_simplifiées?: string | null;

  /** Nom du porteur de projet dans les Annotations Privées */
  historique_nom_porteur?: string | null;

  /** Localisation du projet dans les Annotations Privées */
  historique_localisation?: string | null;

  /** Indique si une demande de dérogation est nécessaire pour ce dossier */
  ddep_nécessaire?: string | null;

  /** Indique si le dossier présente un enjeu politique */
  enjeu_politique?: boolean | null;

  /** Commentaires libres sur le dossier remplis par l'instructeurice */
  commentaire_libre?: string | null;

  historique_date_envoi_dernière_contribution?: Date | null;

  /** Identifiant de la demande dans ONAGRE */
  historique_identifiant_demande_onagre?: string | null;

  /** Date de saisine du CSRPN (Conseil Scientifique Régional du Patrimoine Naturel) */
  historique_date_saisine_csrpn?: Date | null;

  /** Date de saisine du CNPN (Conseil National de Protection de la Nature) */
  historique_date_saisine_cnpn?: Date | null;

  /** Date de l'avis du CSRPN */
  date_avis_csrpn?: Date | null;

  /** Date de l'avis du CNPN */
  date_avis_cnpn?: Date | null;

  /** Avis du CSRPN ou du CNPN */
  avis_csrpn_cnpn?: string | null;

  /** Date de la consultation publique */
  date_consultation_public?: Date | null;

  /** Indique si le dossier présente un enjeu écologique */
  enjeu_écologique?: boolean | null;

  /** Indique si le dossier est rattaché au régime d'Autorisation Environnementale */
  rattaché_au_régime_ae?: boolean | null;

  /** Indique qui doit effectuer la prochaine action (Instructeur, pétitionnaire, expert...) */
  prochaine_action_attendue_par?: string | null;

  /** Activité principale relative au dossier (Aménagements fonciers (AFAF, remembrement), Transport hydrocarbures, Destruction de nids d'Hirondelles...) */
  activité_principale?: string | null;

  /** Référence vers le fichier des espèces impactées */
  espèces_impactées?: FichierId | null;

  /** Description synthétique du projet */
  description?: string | null;

  /** Date de début de l'intervention */
  date_début_intervention?: Date | null;

  /** Date de fin de l'intervention */
  date_fin_intervention?: Date | null;

  /** Peut être différente de (date_fin_intervention - date_début_intervention) dans le cas des dérogations pluri-annuelles avec une petite période d'intervention annuelle */
  durée_intervention?: number | null;

  /** Type de demande scientifique */
  scientifique_type_demande?: string[] | null;

  /** Description du protocole de suivi scientifique */
  scientifique_description_protocole_suivi?: string | null;

  /** Modes de capture utilisés */
  scientifique_mode_capture?: string[] | null;

  /** null signifie qu'il n'y a pas d'utilisation de sources lumineuses */
  scientifique_modalités_source_lumineuses?: string | null;

  /** Modalités de marquage des individus */
  scientifique_modalités_marquage?: string | null;

  /** Modalités de transport des individus */
  scientifique_modalités_transport?: string | null;

  /** Périmètre géographique de l'intervention scientifique */
  scientifique_périmètre_intervention?: string | null;

  /** Liste des intervenants scientifiques */
  scientifique_intervenants?: unknown | null;

  /** Précisions sur les autres intervenants scientifiques */
  scientifique_précisions_autres_intervenants?: string | null;

  /** Article L411-2 I.4 du code de l'environnement */
  justification_absence_autre_solution_satisfaisante?: string | null;

  /** Article L411-2 I.4 a) b) c) d) e) du code de l'environnement */
  motif_dérogation?: string | null;

  /** Justification du motif de dérogation */
  justification_motif_dérogation?: string | null;

  /** Indique si des mesures ERC (Éviter, Réduire, Compenser) sont prévues */
  mesures_erc_prévues?: boolean | null;
}
