// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FichierId } from './Fichier';
import type { DossierId } from './Dossier';

/** Identifier type for public.déclaration_espèces_impactées */
export type DClarationEspCesImpactEsId = string & { __brand: 'public.déclaration_espèces_impactées' };

/** Represents the table public.déclaration_espèces_impactées */
export default interface DClarationEspCesImpactEs {
  id: DClarationEspCesImpactEsId;

  fichier: FichierId | null;

  dossier: DossierId | null;
}

/** Represents the initializer for the table public.déclaration_espèces_impactées */
export interface DClarationEspCesImpactEsInitializer {
  /** Default value: gen_random_uuid() */
  id?: DClarationEspCesImpactEsId;

  fichier?: FichierId | null;

  dossier?: DossierId | null;
}

/** Represents the mutator for the table public.déclaration_espèces_impactées */
export interface DClarationEspCesImpactEsMutator {
  id?: DClarationEspCesImpactEsId;

  fichier?: FichierId | null;

  dossier?: DossierId | null;
}
