// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type DossierId } from './Dossier';
import { type FichierId } from './Fichier';

/** Identifier type for public.décision_administrative */
export type DCisionAdministrativeId = string & { __brand: 'DCisionAdministrativeId' };

/** Represents the table public.décision_administrative */
export default interface DCisionAdministrative {
  id: DCisionAdministrativeId;

  dossier: DossierId | null;

  numéro: string | null;

  type: string | null;

  date_signature: Date | null;

  date_fin_obligations: Date | null;

  fichier: FichierId | null;
}

/** Represents the initializer for the table public.décision_administrative */
export interface DCisionAdministrativeInitializer {
  /** Default value: gen_random_uuid() */
  id?: DCisionAdministrativeId;

  dossier?: DossierId | null;

  numéro?: string | null;

  type?: string | null;

  date_signature?: Date | null;

  date_fin_obligations?: Date | null;

  fichier?: FichierId | null;
}

/** Represents the mutator for the table public.décision_administrative */
export interface DCisionAdministrativeMutator {
  id?: DCisionAdministrativeId;

  dossier?: DossierId | null;

  numéro?: string | null;

  type?: string | null;

  date_signature?: Date | null;

  date_fin_obligations?: Date | null;

  fichier?: FichierId | null;
}
