// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.entreprise */
export type EntrepriseSiret = string & { __brand: 'EntrepriseSiret' };

/** Represents the table public.entreprise */
export default interface Entreprise {
  siret: EntrepriseSiret;

  raison_sociale: string | null;

  adresse: string | null;
}

/** Represents the initializer for the table public.entreprise */
export interface EntrepriseInitializer {
  siret: EntrepriseSiret;

  raison_sociale?: string | null;

  adresse?: string | null;
}

/** Represents the mutator for the table public.entreprise */
export interface EntrepriseMutator {
  siret?: EntrepriseSiret;

  raison_sociale?: string | null;

  adresse?: string | null;
}
