// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.espece_taxref */
export type EspeceTaxrefId = string & { __brand: 'public.espece_taxref' };

/** Represents the table public.espece_taxref */
export default interface EspeceTaxref {
  id: EspeceTaxrefId;

  cd_nom: string;

  cd_ref: string;

  lb_nom: string;

  nom_vern: string;

  regne: string;

  classe: string;
}

/** Represents the initializer for the table public.espece_taxref */
export interface EspeceTaxrefInitializer {
  /** Default value: nextval('espece_taxref_id_seq'::regclass) */
  id?: EspeceTaxrefId;

  cd_nom: string;

  cd_ref: string;

  /** Default value: ''::text */
  lb_nom?: string;

  /** Default value: ''::text */
  nom_vern?: string;

  /** Default value: ''::text */
  regne?: string;

  /** Default value: ''::text */
  classe?: string;
}

/** Represents the mutator for the table public.espece_taxref */
export interface EspeceTaxrefMutator {
  id?: EspeceTaxrefId;

  cd_nom?: string;

  cd_ref?: string;

  lb_nom?: string;

  nom_vern?: string;

  regne?: string;

  classe?: string;
}
