// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DClarationEspCesImpactEsId } from './DéclarationEspècesImpactées';

/** Identifier type for public.espèce_impactée */
export type EspCeImpactEId = string & { __brand: 'public.espèce_impactée' };

/** Represents the table public.espèce_impactée */
export default interface EspCeImpactE {
  id: EspCeImpactEId;

  /** CD_REF est l'identifiant de l'espèce donné par le fichier TAX_REF. */
  CD_REF: string;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  activité: string | null;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  méthode: string | null;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  moyen_de_poursuite: string | null;

  /** Le nombre minimum d'individus impactées. */
  nombre_individus_min: number | null;

  /** Le nombre maximum d'individus impactées. */
  nombre_individus_max: number | null;

  /** Surface d'habitat détruit en m² */
  surface_habitat_détruit: number | null;

  /** Nombre minimal de nids impactés. */
  nombre_nids_min: number | null;

  /** Nombre maximal de nids impactés. */
  nombre_nids_max: number | null;

  /** Nombre minimal d'œufs impactés. */
  nombre_œufs_min: number | null;

  /** Nombre maximal d'œufs impactés. */
  nombre_œufs_max: number | null;

  déclaration_espèces_impactées: DClarationEspCesImpactEsId;
}

/** Represents the initializer for the table public.espèce_impactée */
export interface EspCeImpactEInitializer {
  /** Default value: gen_random_uuid() */
  id?: EspCeImpactEId;

  /** CD_REF est l'identifiant de l'espèce donné par le fichier TAX_REF. */
  CD_REF: string;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  activité?: string | null;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  méthode?: string | null;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  moyen_de_poursuite?: string | null;

  /** Le nombre minimum d'individus impactées. */
  nombre_individus_min?: number | null;

  /** Le nombre maximum d'individus impactées. */
  nombre_individus_max?: number | null;

  /** Surface d'habitat détruit en m² */
  surface_habitat_détruit?: number | null;

  /** Nombre minimal de nids impactés. */
  nombre_nids_min?: number | null;

  /** Nombre maximal de nids impactés. */
  nombre_nids_max?: number | null;

  /** Nombre minimal d'œufs impactés. */
  nombre_œufs_min?: number | null;

  /** Nombre maximal d'œufs impactés. */
  nombre_œufs_max?: number | null;

  déclaration_espèces_impactées: DClarationEspCesImpactEsId;
}

/** Represents the mutator for the table public.espèce_impactée */
export interface EspCeImpactEMutator {
  id?: EspCeImpactEId;

  /** CD_REF est l'identifiant de l'espèce donné par le fichier TAX_REF. */
  CD_REF?: string;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  activité?: string | null;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  méthode?: string | null;

  /** Identifiant Pitchou qui dérive des identifiants du fichier .xsd créé pour le rapportage européen (cf https://dd.eionet.europa.eu/schemas/habides-2.0/derogations.xsd). */
  moyen_de_poursuite?: string | null;

  /** Le nombre minimum d'individus impactées. */
  nombre_individus_min?: number | null;

  /** Le nombre maximum d'individus impactées. */
  nombre_individus_max?: number | null;

  /** Surface d'habitat détruit en m² */
  surface_habitat_détruit?: number | null;

  /** Nombre minimal de nids impactés. */
  nombre_nids_min?: number | null;

  /** Nombre maximal de nids impactés. */
  nombre_nids_max?: number | null;

  /** Nombre minimal d'œufs impactés. */
  nombre_œufs_min?: number | null;

  /** Nombre maximal d'œufs impactés. */
  nombre_œufs_max?: number | null;

  déclaration_espèces_impactées?: DClarationEspCesImpactEsId;
}
