// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type DossierId } from './Dossier';

/** Identifier type for public.espèces_impactées */
export type EspCesImpactEsId = string & { __brand: 'EspCesImpactEsId' };

/** Represents the table public.espèces_impactées */
export default interface EspCesImpactEs {
  id: EspCesImpactEsId;

  dossier: DossierId;

  nom: string | null;

  media_type: string | null;

  contenu: unknown | null;
}

/** Represents the initializer for the table public.espèces_impactées */
export interface EspCesImpactEsInitializer {
  /** Default value: gen_random_uuid() */
  id?: EspCesImpactEsId;

  dossier: DossierId;

  nom?: string | null;

  media_type?: string | null;

  contenu?: unknown | null;
}

/** Represents the mutator for the table public.espèces_impactées */
export interface EspCesImpactEsMutator {
  id?: EspCesImpactEsId;

  dossier?: DossierId;

  nom?: string | null;

  media_type?: string | null;

  contenu?: unknown | null;
}
