// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.fichier */
export type FichierId = string & { __brand: 'public.fichier' };

/** Represents the table public.fichier */
export default interface Fichier {
  id: FichierId;

  nom: string | null;

  media_type: string | null;

  contenu: Buffer | null;

  DS_checksum: string | null;

  DS_createdAt: Date | null;
}

/** Represents the initializer for the table public.fichier */
export interface FichierInitializer {
  /** Default value: gen_random_uuid() */
  id?: FichierId;

  nom?: string | null;

  media_type?: string | null;

  contenu?: Buffer | null;

  DS_checksum?: string | null;

  DS_createdAt?: Date | null;
}

/** Represents the mutator for the table public.fichier */
export interface FichierMutator {
  id?: FichierId;

  nom?: string | null;

  media_type?: string | null;

  contenu?: Buffer | null;

  DS_checksum?: string | null;

  DS_createdAt?: Date | null;
}
