// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.groupe_instructeurs */
export type GroupeInstructeursId = string & { __brand: 'public.groupe_instructeurs' };

/** Represents the table public.groupe_instructeurs */
export default interface GroupeInstructeurs {
  id: GroupeInstructeursId;

  nom: string;
}

/** Represents the initializer for the table public.groupe_instructeurs */
export interface GroupeInstructeursInitializer {
  /** Default value: gen_random_uuid() */
  id?: GroupeInstructeursId;

  nom: string;
}

/** Represents the mutator for the table public.groupe_instructeurs */
export interface GroupeInstructeursMutator {
  id?: GroupeInstructeursId;

  nom?: string;
}
