// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from './Personne';
import type { DossierId } from './Dossier';

/** Identifier type for public.notification */
export type NotificationId = string & { __brand: 'public.notification' };

/** Represents the table public.notification */
export default interface Notification {
  id: NotificationId;

  /** Date à laquelle la notification a été mise à jour pour la dernière fois */
  updated_at: Date | null;

  /** Indique si la personne a consulté ou non la notification */
  vue: boolean;

  personne: PersonneId;

  dossier: DossierId;
}

/** Represents the initializer for the table public.notification */
export interface NotificationInitializer {
  /** Default value: gen_random_uuid() */
  id?: NotificationId;

  /**
   * Date à laquelle la notification a été mise à jour pour la dernière fois
   * Default value: CURRENT_TIMESTAMP
   */
  updated_at?: Date | null;

  /**
   * Indique si la personne a consulté ou non la notification
   * Default value: false
   */
  vue?: boolean;

  personne: PersonneId;

  dossier: DossierId;
}

/** Represents the mutator for the table public.notification */
export interface NotificationMutator {
  id?: NotificationId;

  /** Date à laquelle la notification a été mise à jour pour la dernière fois */
  updated_at?: Date | null;

  /** Indique si la personne a consulté ou non la notification */
  vue?: boolean;

  personne?: PersonneId;

  dossier?: DossierId;
}
