// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.personne */
export type PersonneId = number & { __brand: 'public.personne' };

/** Represents the table public.personne */
export default interface Personne {
  id: PersonneId;

  /** Nom de famille de la personne. Identité civile */
  nom: string | null;

  /** Prénoms de la personne. Identité civile */
  prénoms: string | null;

  /** Adresse email de la personne. Utilisée pour la communication, l'authentification et l'identification unique de l'utilisateur dans le système. */
  email: string | null;

  /** Code d'accès unique de la personne. Permet de récupérer un lot de capabilities dans la table, notamment dans la table arête_cap_dossier__groupe_nstructeur */
  code_accès: string | null;
}

/** Represents the initializer for the table public.personne */
export interface PersonneInitializer {
  /** Default value: nextval('personne_id_seq'::regclass) */
  id?: PersonneId;

  /** Nom de famille de la personne. Identité civile */
  nom?: string | null;

  /** Prénoms de la personne. Identité civile */
  prénoms?: string | null;

  /** Adresse email de la personne. Utilisée pour la communication, l'authentification et l'identification unique de l'utilisateur dans le système. */
  email?: string | null;

  /** Code d'accès unique de la personne. Permet de récupérer un lot de capabilities dans la table, notamment dans la table arête_cap_dossier__groupe_nstructeur */
  code_accès?: string | null;
}

/** Represents the mutator for the table public.personne */
export interface PersonneMutator {
  id?: PersonneId;

  /** Nom de famille de la personne. Identité civile */
  nom?: string | null;

  /** Prénoms de la personne. Identité civile */
  prénoms?: string | null;

  /** Adresse email de la personne. Utilisée pour la communication, l'authentification et l'identification unique de l'utilisateur dans le système. */
  email?: string | null;

  /** Code d'accès unique de la personne. Permet de récupérer un lot de capabilities dans la table, notamment dans la table arête_cap_dossier__groupe_nstructeur */
  code_accès?: string | null;
}
