// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.personne */
export type PersonneId = number & { __brand: 'PersonneId' };

/** Represents the table public.personne */
export default interface Personne {
  id: PersonneId;

  nom: string | null;

  prénoms: string | null;

  email: string | null;

  code_accès: string | null;
}

/** Represents the initializer for the table public.personne */
export interface PersonneInitializer {
  /** Default value: nextval('personne_id_seq'::regclass) */
  id?: PersonneId;

  nom?: string | null;

  prénoms?: string | null;

  email?: string | null;

  code_accès?: string | null;
}

/** Represents the mutator for the table public.personne */
export interface PersonneMutator {
  id?: PersonneId;

  nom?: string | null;

  prénoms?: string | null;

  email?: string | null;

  code_accès?: string | null;
}
