// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type DCisionAdministrativeId } from './DécisionAdministrative';

/** Identifier type for public.prescription */
export type PrescriptionId = string & { __brand: 'PrescriptionId' };

/** Represents the table public.prescription */
export default interface Prescription {
  id: PrescriptionId;

  décision_administrative: DCisionAdministrativeId;

  date_échéance: Date | null;

  numéro_article: string | null;

  description: string | null;

  /** en m² */
  surface_évitée: number | null;

  /** en m² */
  surface_compensée: number | null;

  nids_évités: number | null;

  nids_compensés: number | null;

  individus_évités: number | null;

  individus_compensés: number | null;
}

/** Represents the initializer for the table public.prescription */
export interface PrescriptionInitializer {
  /** Default value: gen_random_uuid() */
  id?: PrescriptionId;

  décision_administrative: DCisionAdministrativeId;

  date_échéance?: Date | null;

  numéro_article?: string | null;

  description?: string | null;

  /** en m² */
  surface_évitée?: number | null;

  /** en m² */
  surface_compensée?: number | null;

  nids_évités?: number | null;

  nids_compensés?: number | null;

  individus_évités?: number | null;

  individus_compensés?: number | null;
}

/** Represents the mutator for the table public.prescription */
export interface PrescriptionMutator {
  id?: PrescriptionId;

  décision_administrative?: DCisionAdministrativeId;

  date_échéance?: Date | null;

  numéro_article?: string | null;

  description?: string | null;

  /** en m² */
  surface_évitée?: number | null;

  /** en m² */
  surface_compensée?: number | null;

  nids_évités?: number | null;

  nids_compensés?: number | null;

  individus_évités?: number | null;

  individus_compensés?: number | null;
}
