// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.TypeDossier */
type TypeDossier = 
  | 'Hirondelle'
  | 'Cigogne';

export default TypeDossier;
