// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type DossierId } from './Dossier';
import { type DossierPhase } from '../../API_Pitchou.ts';
import { type PersonneId } from './Personne';

/** Represents the table public.évènement_phase_dossier */
export default interface VNementPhaseDossier {
  dossier: DossierId;

  phase: DossierPhase;

  horodatage: Date;

  cause_personne: PersonneId | null;
}

/** Represents the initializer for the table public.évènement_phase_dossier */
export interface VNementPhaseDossierInitializer {
  dossier: DossierId;

  phase: DossierPhase;

  horodatage: Date;

  cause_personne?: PersonneId | null;
}

/** Represents the mutator for the table public.évènement_phase_dossier */
export interface VNementPhaseDossierMutator {
  dossier?: DossierId;

  phase?: DossierPhase;

  horodatage?: Date;

  cause_personne?: PersonneId | null;
}
