// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from './Personne';

/** Identifier type for public.évènement_métrique */
export type VNementMTriqueId = string & { __brand: 'public.évènement_métrique' };

/** Represents the table public.évènement_métrique */
export default interface VNementMTrique {
  id: VNementMTriqueId;

  personne: PersonneId;

  /** Date de l’évènement */
  date: Date;

  /** Type de l’évènement */
  évènement: string;

  /** Données structurées liées donnant des détails sur l’évènement */
  détails: unknown | null;
}

/** Represents the initializer for the table public.évènement_métrique */
export interface VNementMTriqueInitializer {
  /** Default value: gen_random_uuid() */
  id?: VNementMTriqueId;

  personne: PersonneId;

  /**
   * Date de l’évènement
   * Default value: CURRENT_TIMESTAMP
   */
  date?: Date;

  /** Type de l’évènement */
  évènement: string;

  /** Données structurées liées donnant des détails sur l’évènement */
  détails?: unknown | null;
}

/** Represents the mutator for the table public.évènement_métrique */
export interface VNementMTriqueMutator {
  id?: VNementMTriqueId;

  personne?: PersonneId;

  /** Date de l’évènement */
  date?: Date;

  /** Type de l’évènement */
  évènement?: string;

  /** Données structurées liées donnant des détails sur l’évènement */
  détails?: unknown | null;
}
