export const tableRenames = [
  ["arête_personne__cap_écriture_annotation", "edge_personne__cap_annotation_write"],
  ["arête_cap_dossier__groupe_instructeurs", "edge_cap_dossier__groupe_instructeurs"],
  ["arête_groupe_instructeurs__dossier", "edge_groupe_instructeurs__dossier"],
  ["arête_personne_suit_dossier", "edge_personne_follows_dossier"],
  [
    "arête_dossier__fichier_pièces_jointes_pétitionnaire",
    "edge_dossier__fichier_pieces_jointes_petitionnaire",
  ],
  ["cap_écriture_annotation", "cap_annotation_write"],
  ["cap_évènement_métrique", "cap_evenement_metrique"],
  ["évènement_métrique", "evenement_metrique"],
  ["évènement_phase_dossier", "evenement_phase_dossier"],
  ["décision_administrative", "decision_administrative"],
  ["contrôle", "controle"],
  ["résultat_synchronisation_DS_88444", "demarche_numerique_88444_synchronization_result"],
  ["attachment_autre", "other_attachment"],
  ["capability-geomce", "capability_geomce"],
] as const;

export const columnRenames = {
  dossier: [
    ["id_demarches_simplifiées", "demarche_numerique_id"],
    ["date_dépôt", "depot_date"],
    ["départements", "departments"],
    ["déposant", "deposant"],
    ["régions", "regions"],
    ["nom", "name"],
    ["number_demarches_simplifiées", "demarche_numerique_number"],
    ["ddep_nécessaire", "ddep_required"],
    ["commentaire_libre", "free_comment"],
    ["historique_identifiant_demande_onagre", "onagre_demande_identifier"],
    ["date_debut_consultation_public", "public_consultation_start_date"],
    ["rattaché_au_régime_ae", "linked_to_ae_regime"],
    ["prochaine_action_attendue_par", "next_action_expected_from"],
    ["activité_principale", "main_activite"],
    ["espèces_impactées", "especes_impactees"],
    ["date_début_intervention", "intervention_start_date"],
    ["date_fin_intervention", "intervention_end_date"],
    ["durée_intervention", "intervention_duration"],
    ["scientifique_type_demande", "scientifique_demande_type"],
    ["scientifique_description_protocole_suivi", "scientifique_suivi_protocol_description"],
    ["scientifique_mode_capture", "scientifique_capture_mode"],
    ["scientifique_modalités_source_lumineuses", "scientifique_light_source_conditions"],
    ["scientifique_modalités_marquage", "scientifique_marking_conditions"],
    ["scientifique_modalités_transport", "scientifique_transport_conditions"],
    ["scientifique_périmètre_intervention", "scientifique_intervention_perimeter"],
    ["scientifique_précisions_autres_intervenants", "scientifique_other_intervenants_details"],
    [
      "justification_absence_autre_solution_satisfaisante",
      "no_other_satisfactory_solution_justification",
    ],
    ["motif_dérogation", "motif_derogation"],
    ["justification_motif_dérogation", "motif_derogation_justification"],
    ["mesures_erc_prévues", "mesures_erc_planned"],
    ["scientifique_bilan_antérieur", "scientifique_previous_assessment"],
    ["scientifique_finalité_demande", "scientifique_demande_purposes"],
    ["nombre_nids_détruits_dossier_oiseau_simple", "dossier_oiseau_simple_destroyed_nids_count"],
    ["nombre_nids_compensés_dossier_oiseau_simple", "dossier_oiseau_simple_compensated_nids_count"],
    ["numéro_démarche", "demarche_number"],
    ["etat_des_lieux_ecologique_complet_realise", "ecological_inventory_completed"],
    ["presence_especes_dans_aire_influence", "especes_present_in_influence_area"],
    ["risque_malgre_mesures_erc", "risk_despite_erc_mesures"],
    ["date_fin_consultation_public", "public_consultation_end_date"],
    ["mesures_er_suffisantes", "er_mesures_sufficient"],
    ["date_mise_en_service", "commissioning_date"],
    ["cartographie_projet", "projet_map"],
  ],
  personne: [
    ["nom", "last_name"],
    ["prénoms", "first_names"],
    ["code_accès", "access_code"],
  ],
  entreprise: [
    ["raison_sociale", "legal_name"],
    ["adresse", "address"],
  ],
  groupe_instructeurs: [
    ["nom", "name"],
    ["numéro_démarche", "demarche_number"],
  ],
  decision_administrative: [
    ["numéro", "number"],
    ["date_signature", "signature_date"],
    ["date_fin_obligations", "obligations_end_date"],
  ],
  prescription: [
    ["décision_administrative", "decision_administrative"],
    ["date_échéance", "due_date"],
    ["numéro_article", "article_number"],
    ["surface_évitée", "avoided_surface"],
    ["surface_compensée", "compensated_surface"],
    ["nids_évités", "avoided_nids"],
    ["nids_compensés", "compensated_nids"],
    ["individus_évités", "avoided_individus"],
    ["individus_compensés", "compensated_individus"],
  ],
  controle: [
    ["date_contrôle", "controle_date"],
    ["résultat", "result"],
    ["commentaire", "comment"],
    ["type_action_suite_contrôle", "post_controle_action_type"],
    ["date_action_suite_contrôle", "post_controle_action_date"],
    ["date_prochaine_échéance", "next_due_date"],
  ],
  avis_expert: [
    ["date_saisine", "saisine_date"],
    ["date_avis", "avis_date"],
  ],
  message: [
    ["contenu", "content"],
    ["email_expéditeur", "sender_email"],
    ["id_démarches_simplifiées", "demarche_numerique_id"],
  ],
  notification: [
    ["date_dernière_mise_à_jour", "updated_at"],
    ["vue", "viewed"],
  ],
  demarche_numerique_88444_synchronization_result: [
    ["succès", "success"],
    ["horodatage", "timestamp"],
    ["erreur", "error"],
  ],
  evenement_phase_dossier: [
    ["horodatage", "timestamp"],
    ["cause_personne", "caused_by_personne"],
    ["DS_emailAgentTraitant", "demarche_numerique_agent_email"],
    ["DS_motivation", "demarche_numerique_motivation"],
  ],
  evenement_metrique: [
    ["évènement", "evenement"],
    ["détails", "details"],
  ],
  edge_personne__cap_annotation_write: [["écriture_annotation_cap", "annotation_write_cap"]],
  file: [
    ["nom", "name"],
    ["taille", "size"],
    ["DS_checksum", "demarche_numerique_checksum"],
    ["DS_createdAt", "demarche_numerique_created_at"],
  ],
  espece_protegee_modification: [
    ["exclu", "excluded"],
    ["modifie_par", "modified_by"],
  ],
} as const;
