// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActiviteCode } from "./Activite";

/** Identifier type for public.activite_label */
export type ActiviteLabelLabel = string & { __brand: "public.activite_label" };

/**
 * Represents the table public.activite_label
 * Raw « Activité principale » labels as stored on dossiers, grouped under one activite. Several labels can point to the same activity when an option was renamed in Démarche Numérique over time.
 */
export default interface ActiviteLabel {
  /** Exact raw label as it appears in dossier.main_activite. */
  label: ActiviteLabelLabel;

  /** Activity this label is grouped under. */
  activite_code: ActiviteCode;

  /** True while the label was auto-assigned to the 'autre' activity (by the DN sync or by this migration's backfill) and no administrator has reviewed it yet. */
  needs_review: boolean;

  /** When the label was first registered, i.e. when the sync detected it. */
  created_at: Date;
}

/**
 * Represents the initializer for the table public.activite_label
 * Raw « Activité principale » labels as stored on dossiers, grouped under one activite. Several labels can point to the same activity when an option was renamed in Démarche Numérique over time.
 */
export interface ActiviteLabelInitializer {
  /** Exact raw label as it appears in dossier.main_activite. */
  label: ActiviteLabelLabel;

  /** Activity this label is grouped under. */
  activite_code: ActiviteCode;

  /**
   * True while the label was auto-assigned to the 'autre' activity (by the DN sync or by this migration's backfill) and no administrator has reviewed it yet.
   * Default value: false
   */
  needs_review?: boolean;

  /**
   * When the label was first registered, i.e. when the sync detected it.
   * Default value: CURRENT_TIMESTAMP
   */
  created_at?: Date;
}

/**
 * Represents the mutator for the table public.activite_label
 * Raw « Activité principale » labels as stored on dossiers, grouped under one activite. Several labels can point to the same activity when an option was renamed in Démarche Numérique over time.
 */
export interface ActiviteLabelMutator {
  /** Exact raw label as it appears in dossier.main_activite. */
  label?: ActiviteLabelLabel;

  /** Activity this label is grouped under. */
  activite_code?: ActiviteCode;

  /** True while the label was auto-assigned to the 'autre' activity (by the DN sync or by this migration's backfill) and no administrator has reviewed it yet. */
  needs_review?: boolean;

  /** When the label was first registered, i.e. when the sync detected it. */
  created_at?: Date;
}
