// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.activite */
export type ActiviteCode = string & { __brand: "public.activite" };

/**
 * Represents the table public.activite
 * Referentiel of the activities behind a derogation request, owned by Pitchou. Dossiers reference an activity through the raw labels grouped in activite_label.
 */
export default interface Activite {
  /** Stable identifier, e.g. 'carrieres'. Also names the activity icon file. */
  code: ActiviteCode;

  /** Display name shown in Pitchou, decided by administrators. */
  label: string;
}

/**
 * Represents the initializer for the table public.activite
 * Referentiel of the activities behind a derogation request, owned by Pitchou. Dossiers reference an activity through the raw labels grouped in activite_label.
 */
export interface ActiviteInitializer {
  /** Stable identifier, e.g. 'carrieres'. Also names the activity icon file. */
  code: ActiviteCode;

  /** Display name shown in Pitchou, decided by administrators. */
  label: string;
}

/**
 * Represents the mutator for the table public.activite
 * Referentiel of the activities behind a derogation request, owned by Pitchou. Dossiers reference an activity through the raw labels grouped in activite_label.
 */
export interface ActiviteMutator {
  /** Stable identifier, e.g. 'carrieres'. Also names the activity icon file. */
  code?: ActiviteCode;

  /** Display name shown in Pitchou, decided by administrators. */
  label?: string;
}
