// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.activite_groupe */
export type ActiviteGroupeCode = string & { __brand: "public.activite_groupe" };

/**
 * Represents the table public.activite_groupe
 * Thematic groups of the activity referentiel. Activities are displayed grouped by activite_groupe, each group with its own color.
 */
export default interface ActiviteGroupe {
  /** Stable identifier, e.g. 'projets-urbains'. */
  code: ActiviteGroupeCode;

  /** Display name shown in Pitchou, renamable by administrators. */
  label: string;

  /** Pastel background color of the group, as a CSS hex value, e.g. '#fceeb5'. */
  color: string;
}

/**
 * Represents the initializer for the table public.activite_groupe
 * Thematic groups of the activity referentiel. Activities are displayed grouped by activite_groupe, each group with its own color.
 */
export interface ActiviteGroupeInitializer {
  /** Stable identifier, e.g. 'projets-urbains'. */
  code: ActiviteGroupeCode;

  /** Display name shown in Pitchou, renamable by administrators. */
  label: string;

  /** Pastel background color of the group, as a CSS hex value, e.g. '#fceeb5'. */
  color: string;
}

/**
 * Represents the mutator for the table public.activite_groupe
 * Thematic groups of the activity referentiel. Activities are displayed grouped by activite_groupe, each group with its own color.
 */
export interface ActiviteGroupeMutator {
  /** Stable identifier, e.g. 'projets-urbains'. */
  code?: ActiviteGroupeCode;

  /** Display name shown in Pitchou, renamable by administrators. */
  label?: string;

  /** Pastel background color of the group, as a CSS hex value, e.g. '#fceeb5'. */
  color?: string;
}
