// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { PersonneId } from "./Personne";

/** Identifier type for public.action_dossier */
export type ActionDossierId = string & { __brand: "public.action_dossier" };

/** Represents the table public.action_dossier */
export default interface ActionDossier {
  id: ActionDossierId;

  dossier: DossierId;

  /** Kind of action, e.g. 'phase_renseignee' or 'commentaire_ajoute' */
  type: string;

  /** Type-specific details: field label, new value, follower email… */
  data: unknown;

  /** Instructeur behind the action, null for pétitionnaire or system actions */
  author_personne: PersonneId | null;

  /** True when the action comes from the pétitionnaire via the form platform */
  author_petitionnaire: boolean;

  /** Date on which the action happened */
  created_at: Date;
}

/** Represents the initializer for the table public.action_dossier */
export interface ActionDossierInitializer {
  /** Default value: gen_random_uuid() */
  id?: ActionDossierId;

  dossier: DossierId;

  /** Kind of action, e.g. 'phase_renseignee' or 'commentaire_ajoute' */
  type: string;

  /**
   * Type-specific details: field label, new value, follower email…
   * Default value: '{}'::jsonb
   */
  data?: unknown;

  /** Instructeur behind the action, null for pétitionnaire or system actions */
  author_personne?: PersonneId | null;

  /**
   * True when the action comes from the pétitionnaire via the form platform
   * Default value: false
   */
  author_petitionnaire?: boolean;

  /**
   * Date on which the action happened
   * Default value: CURRENT_TIMESTAMP
   */
  created_at?: Date;
}

/** Represents the mutator for the table public.action_dossier */
export interface ActionDossierMutator {
  id?: ActionDossierId;

  dossier?: DossierId;

  /** Kind of action, e.g. 'phase_renseignee' or 'commentaire_ajoute' */
  type?: string;

  /** Type-specific details: field label, new value, follower email… */
  data?: unknown;

  /** Instructeur behind the action, null for pétitionnaire or system actions */
  author_personne?: PersonneId | null;

  /** True when the action comes from the pétitionnaire via the form platform */
  author_petitionnaire?: boolean;

  /** Date on which the action happened */
  created_at?: Date;
}
