// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AuthUserId } from "./AuthUser";

/** Identifier type for public.administration_event */
export type AdministrationEventId = string & { __brand: "public.administration_event" };

/** Represents the table public.administration_event */
export default interface AdministrationEvent {
  id: AdministrationEventId;

  actor: AuthUserId | null;

  action: string;

  data: unknown;

  created_at: Date;
}

/** Represents the initializer for the table public.administration_event */
export interface AdministrationEventInitializer {
  /** Default value: nextval('administration_event_id_seq'::regclass) */
  id?: AdministrationEventId;

  actor?: AuthUserId | null;

  action: string;

  data: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.administration_event */
export interface AdministrationEventMutator {
  id?: AdministrationEventId;

  actor?: AuthUserId | null;

  action?: string;

  data?: unknown;

  created_at?: Date;
}
