// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { GroupeInstructeursId } from "./GroupeInstructeurs";

/** Represents the table public.arête_groupe_instructeurs__dossier */
export default interface AreteGroupeInstructeursDossier {
  dossier: DossierId;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the initializer for the table public.arête_groupe_instructeurs__dossier */
export interface AreteGroupeInstructeursDossierInitializer {
  dossier: DossierId;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the mutator for the table public.arête_groupe_instructeurs__dossier */
export interface AreteGroupeInstructeursDossierMutator {
  dossier?: DossierId;

  groupe_instructeurs?: GroupeInstructeursId;
}
