// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CapEcritureAnnotationCap } from "./CapEcritureAnnotation";

/** Represents the table public.arête_personne__cap_écriture_annotation */
export default interface AretePersonneCapEcritureAnnotation {
  personne_cap: string | null;

  écriture_annotation_cap: CapEcritureAnnotationCap | null;
}

/** Represents the initializer for the table public.arête_personne__cap_écriture_annotation */
export interface AretePersonneCapEcritureAnnotationInitializer {
  personne_cap?: string | null;

  écriture_annotation_cap?: CapEcritureAnnotationCap | null;
}

/** Represents the mutator for the table public.arête_personne__cap_écriture_annotation */
export interface AretePersonneCapEcritureAnnotationMutator {
  personne_cap?: string | null;

  écriture_annotation_cap?: CapEcritureAnnotationCap | null;
}
