// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { FileId } from "./File";

/** Represents the table public.arête_dossier__fichier_pièces_jointes_pétitionnaire */
export default interface ArTeDossierFichierPiCesJointesPTitionnaire {
  dossier: DossierId;

  fichier: FileId;
}

/** Represents the initializer for the table public.arête_dossier__fichier_pièces_jointes_pétitionnaire */
export interface ArTeDossierFichierPiCesJointesPTitionnaireInitializer {
  dossier: DossierId;

  fichier: FileId;
}

/** Represents the mutator for the table public.arête_dossier__fichier_pièces_jointes_pétitionnaire */
export interface ArTeDossierFichierPiCesJointesPTitionnaireMutator {
  dossier?: DossierId;

  fichier?: FileId;
}
