// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { FileId } from "./File";

/** Identifier type for public.attachment_autre */
export type AttachmentAutreId = string & { __brand: "public.attachment_autre" };

/** Represents the table public.attachment_autre */
export default interface AttachmentAutre {
  id: AttachmentAutreId;

  dossier: DossierId;

  fichier: FileId;

  type: string;

  attachment_date: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.attachment_autre */
export interface AttachmentAutreInitializer {
  /** Default value: gen_random_uuid() */
  id?: AttachmentAutreId;

  dossier: DossierId;

  fichier: FileId;

  type: string;

  attachment_date?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.attachment_autre */
export interface AttachmentAutreMutator {
  id?: AttachmentAutreId;

  dossier?: DossierId;

  fichier?: FileId;

  type?: string;

  attachment_date?: Date | null;

  created_at?: Date;
}
