// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AuthUserId } from "./AuthUser";

/** Identifier type for public.auth_permission_exclusion */
export type AuthPermissionExclusionPermission = string & {
  __brand: "public.auth_permission_exclusion";
};

/** Represents the table public.auth_permission_exclusion */
export default interface AuthPermissionExclusion {
  user_id: AuthUserId;

  permission: AuthPermissionExclusionPermission;
}

/** Represents the initializer for the table public.auth_permission_exclusion */
export interface AuthPermissionExclusionInitializer {
  user_id: AuthUserId;

  permission: AuthPermissionExclusionPermission;
}

/** Represents the mutator for the table public.auth_permission_exclusion */
export interface AuthPermissionExclusionMutator {
  user_id?: AuthUserId;

  permission?: AuthPermissionExclusionPermission;
}
