// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AuthUserId } from "./AuthUser";

/** Identifier type for public.auth_permission */
export type AuthPermissionPermission = string & { __brand: "public.auth_permission" };

/** Represents the table public.auth_permission */
export default interface AuthPermission {
  user_id: AuthUserId;

  permission: AuthPermissionPermission;
}

/** Represents the initializer for the table public.auth_permission */
export interface AuthPermissionInitializer {
  user_id: AuthUserId;

  permission: AuthPermissionPermission;
}

/** Represents the mutator for the table public.auth_permission */
export interface AuthPermissionMutator {
  user_id?: AuthUserId;

  permission?: AuthPermissionPermission;
}
