// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AuthUserId } from "./AuthUser";

/** Identifier type for public.auth_permission_bundle */
export type AuthPermissionBundleBundle = string & { __brand: "public.auth_permission_bundle" };

/** Represents the table public.auth_permission_bundle */
export default interface AuthPermissionBundle {
  user_id: AuthUserId;

  bundle: AuthPermissionBundleBundle;
}

/** Represents the initializer for the table public.auth_permission_bundle */
export interface AuthPermissionBundleInitializer {
  user_id: AuthUserId;

  bundle: AuthPermissionBundleBundle;
}

/** Represents the mutator for the table public.auth_permission_bundle */
export interface AuthPermissionBundleMutator {
  user_id?: AuthUserId;

  bundle?: AuthPermissionBundleBundle;
}
