// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.auth_user */
export type AuthUserId = number & { __brand: "public.auth_user" };

/** Represents the table public.auth_user */
export default interface AuthUser {
  id: AuthUserId;

  email: string | null;

  first_names: string | null;

  last_name: string | null;

  active: boolean;

  created_at: Date;

  first_login_at: Date | null;

  last_login_at: Date | null;
}

/** Represents the initializer for the table public.auth_user */
export interface AuthUserInitializer {
  /** Default value: nextval('auth_user_id_seq'::regclass) */
  id?: AuthUserId;

  email?: string | null;

  first_names?: string | null;

  last_name?: string | null;

  /** Default value: true */
  active?: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  first_login_at?: Date | null;

  last_login_at?: Date | null;
}

/** Represents the mutator for the table public.auth_user */
export interface AuthUserMutator {
  id?: AuthUserId;

  email?: string | null;

  first_names?: string | null;

  last_name?: string | null;

  active?: boolean;

  created_at?: Date;

  first_login_at?: Date | null;

  last_login_at?: Date | null;
}
