// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AuthUserId } from "./AuthUser";

/** Identifier type for public.auth_identity */
export type AuthIdentityIssuer = string & { __brand: "public.auth_identity" };

/** Identifier type for public.auth_identity */
export type AuthIdentitySubject = string & { __brand: "public.auth_identity" };

/** Represents the table public.auth_identity */
export default interface AuthIdentity {
  issuer: AuthIdentityIssuer;

  subject: AuthIdentitySubject;

  user_id: AuthUserId;
}

/** Represents the initializer for the table public.auth_identity */
export interface AuthIdentityInitializer {
  issuer: AuthIdentityIssuer;

  subject: AuthIdentitySubject;

  user_id: AuthUserId;
}

/** Represents the mutator for the table public.auth_identity */
export interface AuthIdentityMutator {
  issuer?: AuthIdentityIssuer;

  subject?: AuthIdentitySubject;

  user_id?: AuthUserId;
}
