// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { FileId } from "./File";

/** Identifier type for public.avis_expert */
export type AvisExpertId = string & { __brand: "public.avis_expert" };

/** Represents the table public.avis_expert */
export default interface AvisExpert {
  id: AvisExpertId;

  dossier: DossierId;

  /** Authority consulted for an avis on the derogation (e.g. CSRPN, CNPN, or another competent authority). */
  expert: string | null;

  /** Date on which the expert was officially consulted for an avis. */
  saisine_date: Date | null;

  /** Fichier sent when the expert was consulted. */
  saisine_fichier: FileId | null;

  /** Nature of the avis issued by the expert (e.g. "Favorable", "Favorable sous conditions", "Défavorable", "Non renseigné"). */
  avis: string | null;

  /** Date on which the expert's avis was issued or received. */
  avis_date: Date | null;

  /** Fichier containing the expert's formal avis. */
  avis_fichier: FileId | null;
}

/** Represents the initializer for the table public.avis_expert */
export interface AvisExpertInitializer {
  /** Default value: gen_random_uuid() */
  id?: AvisExpertId;

  dossier: DossierId;

  /** Authority consulted for an avis on the derogation (e.g. CSRPN, CNPN, or another competent authority). */
  expert?: string | null;

  /** Date on which the expert was officially consulted for an avis. */
  saisine_date?: Date | null;

  /** Fichier sent when the expert was consulted. */
  saisine_fichier?: FileId | null;

  /** Nature of the avis issued by the expert (e.g. "Favorable", "Favorable sous conditions", "Défavorable", "Non renseigné"). */
  avis?: string | null;

  /** Date on which the expert's avis was issued or received. */
  avis_date?: Date | null;

  /** Fichier containing the expert's formal avis. */
  avis_fichier?: FileId | null;
}

/** Represents the mutator for the table public.avis_expert */
export interface AvisExpertMutator {
  id?: AvisExpertId;

  dossier?: DossierId;

  /** Authority consulted for an avis on the derogation (e.g. CSRPN, CNPN, or another competent authority). */
  expert?: string | null;

  /** Date on which the expert was officially consulted for an avis. */
  saisine_date?: Date | null;

  /** Fichier sent when the expert was consulted. */
  saisine_fichier?: FileId | null;

  /** Nature of the avis issued by the expert (e.g. "Favorable", "Favorable sous conditions", "Défavorable", "Non renseigné"). */
  avis?: string | null;

  /** Date on which the expert's avis was issued or received. */
  avis_date?: Date | null;

  /** Fichier containing the expert's formal avis. */
  avis_fichier?: FileId | null;
}
