// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.capability_geomce */
export type CapabilityGeomceSecret = string & { __brand: "public.capability_geomce" };

/** Represents the table public.capability_geomce */
export default interface CapabilityGeomce {
  /** This table has only one row and one value */
  secret: CapabilityGeomceSecret;
}

/** Represents the initializer for the table public.capability_geomce */
export interface CapabilityGeomceInitializer {
  /**
   * This table has only one row and one value
   * Default value: gen_random_uuid()
   */
  secret?: CapabilityGeomceSecret;
}

/** Represents the mutator for the table public.capability_geomce */
export interface CapabilityGeomceMutator {
  /** This table has only one row and one value */
  secret?: CapabilityGeomceSecret;
}
