// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cap_annotation_write */
export type CapAnnotationWriteCap = string & { __brand: "public.cap_annotation_write" };

/** Represents the table public.cap_annotation_write */
export default interface CapAnnotationWrite {
  cap: CapAnnotationWriteCap;

  /** Démarches Simplifiées identifier of the instructeur. Used to refer to the instructeur in API calls */
  instructeur_id: string;
}

/** Represents the initializer for the table public.cap_annotation_write */
export interface CapAnnotationWriteInitializer {
  /** Default value: gen_random_uuid() */
  cap?: CapAnnotationWriteCap;

  /** Démarches Simplifiées identifier of the instructeur. Used to refer to the instructeur in API calls */
  instructeur_id: string;
}

/** Represents the mutator for the table public.cap_annotation_write */
export interface CapAnnotationWriteMutator {
  cap?: CapAnnotationWriteCap;

  /** Démarches Simplifiées identifier of the instructeur. Used to refer to the instructeur in API calls */
  instructeur_id?: string;
}
