// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cap_evenement_metrique */
export type CapEvenementMetriqueCap = string & { __brand: "public.cap_evenement_metrique" };

/** Represents the table public.cap_evenement_metrique */
export default interface CapEvenementMetrique {
  cap: CapEvenementMetriqueCap;

  personne_cap: string;
}

/** Represents the initializer for the table public.cap_evenement_metrique */
export interface CapEvenementMetriqueInitializer {
  /** Default value: gen_random_uuid() */
  cap?: CapEvenementMetriqueCap;

  personne_cap: string;
}

/** Represents the mutator for the table public.cap_evenement_metrique */
export interface CapEvenementMetriqueMutator {
  cap?: CapEvenementMetriqueCap;

  personne_cap?: string;
}
