// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.changelog */
export type ChangelogId = number & { __brand: "public.changelog" };

/** Represents the table public.changelog */
export default interface Changelog {
  id: ChangelogId;

  version_major: number | null;

  version_minor: number | null;

  version_patch: number | null;

  date: Date;

  titre: string;

  contenu: string;

  published: boolean;

  updated_by: string;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.changelog */
export interface ChangelogInitializer {
  /** Default value: nextval('changelog_id_seq'::regclass) */
  id?: ChangelogId;

  version_major?: number | null;

  version_minor?: number | null;

  version_patch?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  date?: Date;

  titre: string;

  /** Default value: ''::text */
  contenu?: string;

  /** Default value: false */
  published?: boolean;

  updated_by: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.changelog */
export interface ChangelogMutator {
  id?: ChangelogId;

  version_major?: number | null;

  version_minor?: number | null;

  version_patch?: number | null;

  date?: Date;

  titre?: string;

  contenu?: string;

  published?: boolean;

  updated_by?: string;

  created_at?: Date;

  updated_at?: Date;
}
