// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { PersonneId } from "./Personne";

/** Identifier type for public.commentaire */
export type CommentaireId = string & { __brand: "public.commentaire" };

/** Represents the table public.commentaire */
export default interface Commentaire {
  id: CommentaireId;

  dossier: DossierId;

  /** Author of the comment. Null for the comment migrated from the dossier's former free comment, displayed as « initial ». */
  personne: PersonneId | null;

  content: string;

  /** Date on which the comment was written */
  created_at: Date;

  /** Date of the last edit, null when the comment was never edited */
  updated_at: Date | null;
}

/** Represents the initializer for the table public.commentaire */
export interface CommentaireInitializer {
  /** Default value: gen_random_uuid() */
  id?: CommentaireId;

  dossier: DossierId;

  /** Author of the comment. Null for the comment migrated from the dossier's former free comment, displayed as « initial ». */
  personne?: PersonneId | null;

  content: string;

  /**
   * Date on which the comment was written
   * Default value: CURRENT_TIMESTAMP
   */
  created_at?: Date;

  /** Date of the last edit, null when the comment was never edited */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.commentaire */
export interface CommentaireMutator {
  id?: CommentaireId;

  dossier?: DossierId;

  /** Author of the comment. Null for the comment migrated from the dossier's former free comment, displayed as « initial ». */
  personne?: PersonneId | null;

  content?: string;

  /** Date on which the comment was written */
  created_at?: Date;

  /** Date of the last edit, null when the comment was never edited */
  updated_at?: Date | null;
}
