// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PrescriptionId } from "./Prescription";

/** Identifier type for public.controle */
export type ControleId = string & { __brand: "public.controle" };

/** Represents the table public.controle */
export default interface Controle {
  id: ControleId;

  /** Reference to the prescription associated with this controle. A prescription can have several controles to track its implementation. */
  prescription: PrescriptionId;

  /** Exact date and time when the controle was performed. Used to track the timeline of checks and schedule future controles. */
  controle_date: Date | null;

  /** Result of the controle. It is currently free text. Eventually, values may be standardized (e.g. "Conforme", "Non conforme", "Conforme avec réserves") to facilitate analysis and reporting. */
  result: string | null;

  /** Detailed inspector comments about the controle. May include observations about implementation status, difficulties encountered, recommendations, etc. */
  comment: string | null;

  /** Type of action to take following the controle. It is currently free text. Examples: email, letter, etc. */
  post_controle_action_type: string | null;

  /** Date on which the action following the controle was taken. It is often equal to controle_date, but may differ if the instructeur does not follow up immediately after the controle */
  post_controle_action_date: Date | null;

  /** Date of the next scheduled controle deadline. Used to plan prescription monitoring and another controle. */
  next_due_date: Date | null;
}

/** Represents the initializer for the table public.controle */
export interface ControleInitializer {
  /** Default value: gen_random_uuid() */
  id?: ControleId;

  /** Reference to the prescription associated with this controle. A prescription can have several controles to track its implementation. */
  prescription: PrescriptionId;

  /** Exact date and time when the controle was performed. Used to track the timeline of checks and schedule future controles. */
  controle_date?: Date | null;

  /** Result of the controle. It is currently free text. Eventually, values may be standardized (e.g. "Conforme", "Non conforme", "Conforme avec réserves") to facilitate analysis and reporting. */
  result?: string | null;

  /** Detailed inspector comments about the controle. May include observations about implementation status, difficulties encountered, recommendations, etc. */
  comment?: string | null;

  /** Type of action to take following the controle. It is currently free text. Examples: email, letter, etc. */
  post_controle_action_type?: string | null;

  /** Date on which the action following the controle was taken. It is often equal to controle_date, but may differ if the instructeur does not follow up immediately after the controle */
  post_controle_action_date?: Date | null;

  /** Date of the next scheduled controle deadline. Used to plan prescription monitoring and another controle. */
  next_due_date?: Date | null;
}

/** Represents the mutator for the table public.controle */
export interface ControleMutator {
  id?: ControleId;

  /** Reference to the prescription associated with this controle. A prescription can have several controles to track its implementation. */
  prescription?: PrescriptionId;

  /** Exact date and time when the controle was performed. Used to track the timeline of checks and schedule future controles. */
  controle_date?: Date | null;

  /** Result of the controle. It is currently free text. Eventually, values may be standardized (e.g. "Conforme", "Non conforme", "Conforme avec réserves") to facilitate analysis and reporting. */
  result?: string | null;

  /** Detailed inspector comments about the controle. May include observations about implementation status, difficulties encountered, recommendations, etc. */
  comment?: string | null;

  /** Type of action to take following the controle. It is currently free text. Examples: email, letter, etc. */
  post_controle_action_type?: string | null;

  /** Date on which the action following the controle was taken. It is often equal to controle_date, but may differ if the instructeur does not follow up immediately after the controle */
  post_controle_action_date?: Date | null;

  /** Date of the next scheduled controle deadline. Used to plan prescription monitoring and another controle. */
  next_due_date?: Date | null;
}
