// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { FileId } from "./File";

/** Identifier type for public.decision_administrative */
export type DecisionAdministrativeId = string & { __brand: "public.decision_administrative" };

/** Represents the table public.decision_administrative */
export default interface DecisionAdministrative {
  id: DecisionAdministrativeId;

  /** Reference to the dossier associated with this decision administrative. A dossier can have several decisions administratives during its review (e.g. "arrêté préfectoral", "arrêté ministériel"). */
  dossier: DossierId;

  /** Official number of the decision administrative. This number is generally assigned by the administration and formally identifies the decision in administrative systems. */
  number: string | null;

  /** Type of decision administrative. Examples include: "Arrêté refus", "Arrêté modification", "Arrêté dérogation", "Autre décision". */
  type: string | null;

  /** Date on which the decision administrative was signed by the competent authority. This date marks the decision taking effect and the start of the beneficiary's obligations. */
  signature_date: Date | null;

  /** End date of the obligations imposed by the decision administrative. This date marks the end of the decision's validity period and its associated prescriptions. */
  obligations_end_date: Date | null;

  /** Reference to the fichier containing the decision administrative. */
  fichier: FileId | null;
}

/** Represents the initializer for the table public.decision_administrative */
export interface DecisionAdministrativeInitializer {
  /** Default value: gen_random_uuid() */
  id?: DecisionAdministrativeId;

  /** Reference to the dossier associated with this decision administrative. A dossier can have several decisions administratives during its review (e.g. "arrêté préfectoral", "arrêté ministériel"). */
  dossier: DossierId;

  /** Official number of the decision administrative. This number is generally assigned by the administration and formally identifies the decision in administrative systems. */
  number?: string | null;

  /** Type of decision administrative. Examples include: "Arrêté refus", "Arrêté modification", "Arrêté dérogation", "Autre décision". */
  type?: string | null;

  /** Date on which the decision administrative was signed by the competent authority. This date marks the decision taking effect and the start of the beneficiary's obligations. */
  signature_date?: Date | null;

  /** End date of the obligations imposed by the decision administrative. This date marks the end of the decision's validity period and its associated prescriptions. */
  obligations_end_date?: Date | null;

  /** Reference to the fichier containing the decision administrative. */
  fichier?: FileId | null;
}

/** Represents the mutator for the table public.decision_administrative */
export interface DecisionAdministrativeMutator {
  id?: DecisionAdministrativeId;

  /** Reference to the dossier associated with this decision administrative. A dossier can have several decisions administratives during its review (e.g. "arrêté préfectoral", "arrêté ministériel"). */
  dossier?: DossierId;

  /** Official number of the decision administrative. This number is generally assigned by the administration and formally identifies the decision in administrative systems. */
  number?: string | null;

  /** Type of decision administrative. Examples include: "Arrêté refus", "Arrêté modification", "Arrêté dérogation", "Autre décision". */
  type?: string | null;

  /** Date on which the decision administrative was signed by the competent authority. This date marks the decision taking effect and the start of the beneficiary's obligations. */
  signature_date?: Date | null;

  /** End date of the obligations imposed by the decision administrative. This date marks the end of the decision's validity period and its associated prescriptions. */
  obligations_end_date?: Date | null;

  /** Reference to the fichier containing the decision administrative. */
  fichier?: FileId | null;
}
