// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.demarche_numerique_88444_synchronization_result */
export default interface DemarcheNumerique88444SynchronizationResult {
  success: boolean;

  timestamp: Date;

  error: string | null;
}

/** Represents the initializer for the table public.demarche_numerique_88444_synchronization_result */
export interface DemarcheNumerique88444SynchronizationResultInitializer {
  success: boolean;

  timestamp: Date;

  error?: string | null;
}

/** Represents the mutator for the table public.demarche_numerique_88444_synchronization_result */
export interface DemarcheNumerique88444SynchronizationResultMutator {
  success?: boolean;

  timestamp?: Date;

  error?: string | null;
}
