// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export type { default } from "./DossierRow";
export type { DossierInitializer } from "./DossierInitializer";
export type { DossierMutator } from "./DossierMutator";
export type { DossierId } from "./DossierRow";
