// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { PersonneId } from "./Personne";

/** Identifier type for public.dossier_cnpn_email_sent_event */
export type DossierCnpnEmailSentEventId = string & {
  __brand: "public.dossier_cnpn_email_sent_event";
};

/** Represents the table public.dossier_cnpn_email_sent_event */
export default interface DossierCnpnEmailSentEvent {
  id: DossierCnpnEmailSentEventId;

  dossier: DossierId;

  sent_by: PersonneId | null;

  created_at: Date;

  sent_at: Date | null;

  status: string;

  sent_by_email: string;

  recipient_email: string;

  cc_emails: string[];

  subject: string;

  html_body: string;

  payload_hash: string;

  attachment_ids: string[];

  attachment_names: string[];

  provider_message_id: string | null;

  delivered_at: Date | null;

  opened_at: Date | null;

  read_receipt_claimed_at: Date | null;

  read_receipt_sent_at: Date | null;
}

/** Represents the initializer for the table public.dossier_cnpn_email_sent_event */
export interface DossierCnpnEmailSentEventInitializer {
  id: DossierCnpnEmailSentEventId;

  dossier: DossierId;

  sent_by?: PersonneId | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  sent_at?: Date | null;

  /** Default value: 'pending'::text */
  status?: string;

  sent_by_email: string;

  recipient_email: string;

  /** Default value: '{}'::text[] */
  cc_emails?: string[];

  subject: string;

  html_body: string;

  payload_hash: string;

  /** Default value: '{}'::uuid[] */
  attachment_ids?: string[];

  /** Default value: '{}'::text[] */
  attachment_names?: string[];

  provider_message_id?: string | null;

  delivered_at?: Date | null;

  opened_at?: Date | null;

  read_receipt_claimed_at?: Date | null;

  read_receipt_sent_at?: Date | null;
}

/** Represents the mutator for the table public.dossier_cnpn_email_sent_event */
export interface DossierCnpnEmailSentEventMutator {
  id?: DossierCnpnEmailSentEventId;

  dossier?: DossierId;

  sent_by?: PersonneId | null;

  created_at?: Date;

  sent_at?: Date | null;

  status?: string;

  sent_by_email?: string;

  recipient_email?: string;

  cc_emails?: string[];

  subject?: string;

  html_body?: string;

  payload_hash?: string;

  attachment_ids?: string[];

  attachment_names?: string[];

  provider_message_id?: string | null;

  delivered_at?: Date | null;

  opened_at?: Date | null;

  read_receipt_claimed_at?: Date | null;

  read_receipt_sent_at?: Date | null;
}
