// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from "./Personne";

/** Identifier type for public.dossier_search */
export type DossierSearchId = string & { __brand: "public.dossier_search" };

/** Represents the table public.dossier_search */
export default interface DossierSearch {
  id: DossierSearchId;

  personne: PersonneId;

  /** Text typed in the dossiers search bar */
  text: string;

  /** Date and time of the search */
  date: Date;
}

/** Represents the initializer for the table public.dossier_search */
export interface DossierSearchInitializer {
  /** Default value: gen_random_uuid() */
  id?: DossierSearchId;

  personne: PersonneId;

  /** Text typed in the dossiers search bar */
  text: string;

  /**
   * Date and time of the search
   * Default value: CURRENT_TIMESTAMP
   */
  date?: Date;
}

/** Represents the mutator for the table public.dossier_search */
export interface DossierSearchMutator {
  id?: DossierSearchId;

  personne?: PersonneId;

  /** Text typed in the dossiers search bar */
  text?: string;

  /** Date and time of the search */
  date?: Date;
}
