// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from "./Personne";
import type { EntrepriseSiret } from "./Entreprise";
import type { FileId } from "./File";
import type { default as TypeDossier } from "./TypeDossier";

/** Identifier type for public.dossier */
export type DossierId = number & { __brand: "public.dossier" };

/** Represents the table public.dossier */
export default interface Dossier {
  id: DossierId;

  /** Unique dossier identifier on Démarches Simplifiées. Used only for some GraphQL API mutations. Prefer demarche_numerique_number */
  demarche_numerique_id: string | null;

  /** Date on which the protected espece derogation request was received by the instructeurs. */
  depot_date: Date;

  /** List of departments covered by the project */
  departments: unknown | null;

  /** List of municipalities covered by the project */
  communes: unknown | null;

  /** The deposant is the personne who submits the dossier on DS. In some situations, this personne differs from the demandeur (the personne morale or personne physique requesting the derogation), for example when a consulting firm authorized by a personne morale submits the dossier. The deposant is not necessarily the demandeur's internal representative (main point of contact). In DS terminology, what we call "déposant" is stored in the "demandeur" property (which differs from our "demandeur") */
  deposant: PersonneId | null;

  /** If the demandeur is a personne physique, this field is not null */
  demandeur_personne_physique: PersonneId | null;

  /** If the demandeur is a personne morale, this field is not null */
  demandeur_personne_morale: EntrepriseSiret | null;

  /** List of regions covered by the project */
  regions: unknown | null;

  /** Name of the protected espece derogation request */
  name: string | null;

  /** Dossier number in Démarches Simplifiées */
  demarche_numerique_number: string | null;

  /** Indicates whether a derogation request is required for this dossier. */
  ddep_required: boolean | null;

  /** Comments from the instructeur about the dossier */
  free_comment: string;

  /** Demande identifier in ONAGRE */
  onagre_demande_identifier: string;

  /** Public consultation date */
  public_consultation_start_date: Date | null;

  /** Indicates whether the dossier is linked to the Autorisation Environnementale regime */
  linked_to_ae_regime: boolean | null;

  /** Indicates who must take the next action ("Instructeur", "CNPN/CSRPN", "Consultation du public", "Pétitionnaire", "Autre administration") */
  next_action_expected_from: string | null;

  /** Standardized category describing the sector or activity behind the protected espece derogation request. Possible values cover different fields (renewable energy production, transport infrastructure, quarries, urban development, water management, ecological restoration, etc.) and classify dossiers by the nature of the work. */
  main_activite: string | null;

  /** Reference to the fichier containing the impacted especes */
  especes_impactees: FileId | null;

  /** Summary description of the project */
  description: string | null;

  /** Intervention start date */
  intervention_start_date: Date | null;

  /** Intervention end date */
  intervention_end_date: Date | null;

  /** May differ from (intervention_end_date - intervention_start_date) for multi-year derogations with a short annual intervention period */
  intervention_duration: number | null;

  /** For a dossier whose main activity is scientific research. This field contains the operations planned under the protected espece derogation request, selected from predefined categories (e.g. immediate on-site capture and release with or without marking, biological material sampling, and other specific cases). Several types can be selected for one request. */
  scientifique_demande_type: string[] | null;

  /** For a dossier whose main activity is scientific research. Description of the planned scientific protocol (e.g. immediate capture and release with or without marking, biological material sampling, and other cases). */
  scientifique_suivi_protocol_description: string | null;

  /** For a dossier whose main activity is scientific research. Capture methods used */
  scientifique_capture_mode: string[] | null;

  /** null means that no light sources are used */
  scientifique_light_source_conditions: string | null;

  /** Conditions for marking individus */
  scientifique_marking_conditions: string | null;

  /** Conditions for transporting individus */
  scientifique_transport_conditions: string | null;

  /** Geographic perimeter of the scientific intervention */
  scientifique_intervention_perimeter: string | null;

  /** List of scientific intervenants */
  scientifique_intervenants: unknown | null;

  /** Details about the other scientific intervenants */
  scientifique_other_intervenants_details: string | null;

  /** Article L411-2 I.4 of the French Environmental Code */
  no_other_satisfactory_solution_justification: string | null;

  /** Article L411-2 I.4 a) b) c) d) e) of the French Environmental Code */
  motif_derogation: string | null;

  /** Justification for the derogation motif */
  motif_derogation_justification: string | null;

  /** Assessment by the petitionnaire. Indicates whether ERC mesures (Avoid, Reduce, Compensate) are planned */
  mesures_erc_planned: boolean | null;

  /** Answer to the question "Cette demande concerne un programme de suivi déjà existant" */
  scientifique_previous_assessment: boolean | null;

  /** Answer to the question "Captures/Relâchers/Prélèvement - Finalité(s) de la demande" */
  scientifique_demande_purposes: unknown | null;

  /** Answer to the question "Nombre de nids d'Hirondelles détruits" */
  dossier_oiseau_simple_destroyed_nids_count: number | null;

  /** Answer to the question "Indiquer le nombre de nids artificiels posés en compensation". Applies to dossiers specific to birds such as swallows or storks. */
  dossier_oiseau_simple_compensated_nids_count: number | null;

  /** Dossier type. Instructeurs often encounter recurring dossier categories such as "Hirondelle" dossiers and "Cigogne" dossiers. */
  type: TypeDossier | null;

  demarche_number: number;

  /** Answer to the question: "Avez-vous réalisé un état des lieux écologique complet $1" */
  ecological_inventory_completed: boolean | null;

  /** Answer to the question: "Des spécimens ou habitats d'espèces protégées sont-ils présents dans l'aire d'influence de votre projet $1" */
  especes_present_in_influence_area: boolean | null;

  /** Answer to the question: "Après mises en oeuvre de mesures d'évitement et de réduction, un risque suffisamment caractérisé pour les espèces protégées demeure-t-il $1" */
  risk_despite_erc_mesures: boolean | null;

  /** Value for the field: "Date de fin de la consultation du public ou enquête publique" */
  public_consultation_end_date: Date | null;

  /** Assessment by the instructeur. Indicates whether avoidance and reduction (ER) mesures are sufficient to avoid a derogation request. This field is linked to ddep_required. */
  er_mesures_sufficient: boolean | null;

  /** Indicates whether the dossier has an enjeu (ecological, political...). */
  enjeu: boolean;

  /** Start date of operations (commissioning of operations) */
  commissioning_date: Date | null;

  projet_map: unknown | null;
}

/** Represents the initializer for the table public.dossier */
export interface DossierInitializer {
  /** Default value: nextval('dossier_id_seq'::regclass) */
  id?: DossierId;

  /** Unique dossier identifier on Démarches Simplifiées. Used only for some GraphQL API mutations. Prefer demarche_numerique_number */
  demarche_numerique_id?: string | null;

  /** Date on which the protected espece derogation request was received by the instructeurs. */
  depot_date: Date;

  /** List of departments covered by the project */
  departments?: unknown | null;

  /** List of municipalities covered by the project */
  communes?: unknown | null;

  /** The deposant is the personne who submits the dossier on DS. In some situations, this personne differs from the demandeur (the personne morale or personne physique requesting the derogation), for example when a consulting firm authorized by a personne morale submits the dossier. The deposant is not necessarily the demandeur's internal representative (main point of contact). In DS terminology, what we call "déposant" is stored in the "demandeur" property (which differs from our "demandeur") */
  deposant?: PersonneId | null;

  /** If the demandeur is a personne physique, this field is not null */
  demandeur_personne_physique?: PersonneId | null;

  /** If the demandeur is a personne morale, this field is not null */
  demandeur_personne_morale?: EntrepriseSiret | null;

  /** List of regions covered by the project */
  regions?: unknown | null;

  /** Name of the protected espece derogation request */
  name?: string | null;

  /** Dossier number in Démarches Simplifiées */
  demarche_numerique_number?: string | null;

  /** Indicates whether a derogation request is required for this dossier. */
  ddep_required?: boolean | null;

  /**
   * Comments from the instructeur about the dossier
   * Default value: ''::text
   */
  free_comment?: string;

  /**
   * Demande identifier in ONAGRE
   * Default value: ''::character varying
   */
  onagre_demande_identifier?: string;

  /** Public consultation date */
  public_consultation_start_date?: Date | null;

  /** Indicates whether the dossier is linked to the Autorisation Environnementale regime */
  linked_to_ae_regime?: boolean | null;

  /** Indicates who must take the next action ("Instructeur", "CNPN/CSRPN", "Consultation du public", "Pétitionnaire", "Autre administration") */
  next_action_expected_from?: string | null;

  /** Standardized category describing the sector or activity behind the protected espece derogation request. Possible values cover different fields (renewable energy production, transport infrastructure, quarries, urban development, water management, ecological restoration, etc.) and classify dossiers by the nature of the work. */
  main_activite?: string | null;

  /** Reference to the fichier containing the impacted especes */
  especes_impactees?: FileId | null;

  /** Summary description of the project */
  description?: string | null;

  /** Intervention start date */
  intervention_start_date?: Date | null;

  /** Intervention end date */
  intervention_end_date?: Date | null;

  /** May differ from (intervention_end_date - intervention_start_date) for multi-year derogations with a short annual intervention period */
  intervention_duration?: number | null;

  /** For a dossier whose main activity is scientific research. This field contains the operations planned under the protected espece derogation request, selected from predefined categories (e.g. immediate on-site capture and release with or without marking, biological material sampling, and other specific cases). Several types can be selected for one request. */
  scientifique_demande_type?: string[] | null;

  /** For a dossier whose main activity is scientific research. Description of the planned scientific protocol (e.g. immediate capture and release with or without marking, biological material sampling, and other cases). */
  scientifique_suivi_protocol_description?: string | null;

  /** For a dossier whose main activity is scientific research. Capture methods used */
  scientifique_capture_mode?: string[] | null;

  /** null means that no light sources are used */
  scientifique_light_source_conditions?: string | null;

  /** Conditions for marking individus */
  scientifique_marking_conditions?: string | null;

  /** Conditions for transporting individus */
  scientifique_transport_conditions?: string | null;

  /** Geographic perimeter of the scientific intervention */
  scientifique_intervention_perimeter?: string | null;

  /** List of scientific intervenants */
  scientifique_intervenants?: unknown | null;

  /** Details about the other scientific intervenants */
  scientifique_other_intervenants_details?: string | null;

  /** Article L411-2 I.4 of the French Environmental Code */
  no_other_satisfactory_solution_justification?: string | null;

  /** Article L411-2 I.4 a) b) c) d) e) of the French Environmental Code */
  motif_derogation?: string | null;

  /** Justification for the derogation motif */
  motif_derogation_justification?: string | null;

  /** Assessment by the petitionnaire. Indicates whether ERC mesures (Avoid, Reduce, Compensate) are planned */
  mesures_erc_planned?: boolean | null;

  /** Answer to the question "Cette demande concerne un programme de suivi déjà existant" */
  scientifique_previous_assessment?: boolean | null;

  /** Answer to the question "Captures/Relâchers/Prélèvement - Finalité(s) de la demande" */
  scientifique_demande_purposes?: unknown | null;

  /** Answer to the question "Nombre de nids d'Hirondelles détruits" */
  dossier_oiseau_simple_destroyed_nids_count?: number | null;

  /** Answer to the question "Indiquer le nombre de nids artificiels posés en compensation". Applies to dossiers specific to birds such as swallows or storks. */
  dossier_oiseau_simple_compensated_nids_count?: number | null;

  /** Dossier type. Instructeurs often encounter recurring dossier categories such as "Hirondelle" dossiers and "Cigogne" dossiers. */
  type?: TypeDossier | null;

  demarche_number: number;

  /** Answer to the question: "Avez-vous réalisé un état des lieux écologique complet $1" */
  ecological_inventory_completed?: boolean | null;

  /** Answer to the question: "Des spécimens ou habitats d'espèces protégées sont-ils présents dans l'aire d'influence de votre projet $1" */
  especes_present_in_influence_area?: boolean | null;

  /** Answer to the question: "Après mises en oeuvre de mesures d'évitement et de réduction, un risque suffisamment caractérisé pour les espèces protégées demeure-t-il $1" */
  risk_despite_erc_mesures?: boolean | null;

  /** Value for the field: "Date de fin de la consultation du public ou enquête publique" */
  public_consultation_end_date?: Date | null;

  /** Assessment by the instructeur. Indicates whether avoidance and reduction (ER) mesures are sufficient to avoid a derogation request. This field is linked to ddep_required. */
  er_mesures_sufficient?: boolean | null;

  /**
   * Indicates whether the dossier has an enjeu (ecological, political...).
   * Default value: false
   */
  enjeu?: boolean;

  /** Start date of operations (commissioning of operations) */
  commissioning_date?: Date | null;

  projet_map?: unknown | null;
}

/** Represents the mutator for the table public.dossier */
export interface DossierMutator {
  id?: DossierId;

  /** Unique dossier identifier on Démarches Simplifiées. Used only for some GraphQL API mutations. Prefer demarche_numerique_number */
  demarche_numerique_id?: string | null;

  /** Date on which the protected espece derogation request was received by the instructeurs. */
  depot_date?: Date;

  /** List of departments covered by the project */
  departments?: unknown | null;

  /** List of municipalities covered by the project */
  communes?: unknown | null;

  /** The deposant is the personne who submits the dossier on DS. In some situations, this personne differs from the demandeur (the personne morale or personne physique requesting the derogation), for example when a consulting firm authorized by a personne morale submits the dossier. The deposant is not necessarily the demandeur's internal representative (main point of contact). In DS terminology, what we call "déposant" is stored in the "demandeur" property (which differs from our "demandeur") */
  deposant?: PersonneId | null;

  /** If the demandeur is a personne physique, this field is not null */
  demandeur_personne_physique?: PersonneId | null;

  /** If the demandeur is a personne morale, this field is not null */
  demandeur_personne_morale?: EntrepriseSiret | null;

  /** List of regions covered by the project */
  regions?: unknown | null;

  /** Name of the protected espece derogation request */
  name?: string | null;

  /** Dossier number in Démarches Simplifiées */
  demarche_numerique_number?: string | null;

  /** Indicates whether a derogation request is required for this dossier. */
  ddep_required?: boolean | null;

  /** Comments from the instructeur about the dossier */
  free_comment?: string;

  /** Demande identifier in ONAGRE */
  onagre_demande_identifier?: string;

  /** Public consultation date */
  public_consultation_start_date?: Date | null;

  /** Indicates whether the dossier is linked to the Autorisation Environnementale regime */
  linked_to_ae_regime?: boolean | null;

  /** Indicates who must take the next action ("Instructeur", "CNPN/CSRPN", "Consultation du public", "Pétitionnaire", "Autre administration") */
  next_action_expected_from?: string | null;

  /** Standardized category describing the sector or activity behind the protected espece derogation request. Possible values cover different fields (renewable energy production, transport infrastructure, quarries, urban development, water management, ecological restoration, etc.) and classify dossiers by the nature of the work. */
  main_activite?: string | null;

  /** Reference to the fichier containing the impacted especes */
  especes_impactees?: FileId | null;

  /** Summary description of the project */
  description?: string | null;

  /** Intervention start date */
  intervention_start_date?: Date | null;

  /** Intervention end date */
  intervention_end_date?: Date | null;

  /** May differ from (intervention_end_date - intervention_start_date) for multi-year derogations with a short annual intervention period */
  intervention_duration?: number | null;

  /** For a dossier whose main activity is scientific research. This field contains the operations planned under the protected espece derogation request, selected from predefined categories (e.g. immediate on-site capture and release with or without marking, biological material sampling, and other specific cases). Several types can be selected for one request. */
  scientifique_demande_type?: string[] | null;

  /** For a dossier whose main activity is scientific research. Description of the planned scientific protocol (e.g. immediate capture and release with or without marking, biological material sampling, and other cases). */
  scientifique_suivi_protocol_description?: string | null;

  /** For a dossier whose main activity is scientific research. Capture methods used */
  scientifique_capture_mode?: string[] | null;

  /** null means that no light sources are used */
  scientifique_light_source_conditions?: string | null;

  /** Conditions for marking individus */
  scientifique_marking_conditions?: string | null;

  /** Conditions for transporting individus */
  scientifique_transport_conditions?: string | null;

  /** Geographic perimeter of the scientific intervention */
  scientifique_intervention_perimeter?: string | null;

  /** List of scientific intervenants */
  scientifique_intervenants?: unknown | null;

  /** Details about the other scientific intervenants */
  scientifique_other_intervenants_details?: string | null;

  /** Article L411-2 I.4 of the French Environmental Code */
  no_other_satisfactory_solution_justification?: string | null;

  /** Article L411-2 I.4 a) b) c) d) e) of the French Environmental Code */
  motif_derogation?: string | null;

  /** Justification for the derogation motif */
  motif_derogation_justification?: string | null;

  /** Assessment by the petitionnaire. Indicates whether ERC mesures (Avoid, Reduce, Compensate) are planned */
  mesures_erc_planned?: boolean | null;

  /** Answer to the question "Cette demande concerne un programme de suivi déjà existant" */
  scientifique_previous_assessment?: boolean | null;

  /** Answer to the question "Captures/Relâchers/Prélèvement - Finalité(s) de la demande" */
  scientifique_demande_purposes?: unknown | null;

  /** Answer to the question "Nombre de nids d'Hirondelles détruits" */
  dossier_oiseau_simple_destroyed_nids_count?: number | null;

  /** Answer to the question "Indiquer le nombre de nids artificiels posés en compensation". Applies to dossiers specific to birds such as swallows or storks. */
  dossier_oiseau_simple_compensated_nids_count?: number | null;

  /** Dossier type. Instructeurs often encounter recurring dossier categories such as "Hirondelle" dossiers and "Cigogne" dossiers. */
  type?: TypeDossier | null;

  demarche_number?: number;

  /** Answer to the question: "Avez-vous réalisé un état des lieux écologique complet $1" */
  ecological_inventory_completed?: boolean | null;

  /** Answer to the question: "Des spécimens ou habitats d'espèces protégées sont-ils présents dans l'aire d'influence de votre projet $1" */
  especes_present_in_influence_area?: boolean | null;

  /** Answer to the question: "Après mises en oeuvre de mesures d'évitement et de réduction, un risque suffisamment caractérisé pour les espèces protégées demeure-t-il $1" */
  risk_despite_erc_mesures?: boolean | null;

  /** Value for the field: "Date de fin de la consultation du public ou enquête publique" */
  public_consultation_end_date?: Date | null;

  /** Assessment by the instructeur. Indicates whether avoidance and reduction (ER) mesures are sufficient to avoid a derogation request. This field is linked to ddep_required. */
  er_mesures_sufficient?: boolean | null;

  /** Indicates whether the dossier has an enjeu (ecological, political...). */
  enjeu?: boolean;

  /** Start date of operations (commissioning of operations) */
  commissioning_date?: Date | null;

  projet_map?: unknown | null;
}
