// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { FileId } from "./File";

/** Represents the table public.edge_dossier__fichier_pieces_jointes_petitionnaire */
export default interface EdgeDossierFichierPiecesJointesPetitionnaire {
  dossier: DossierId;

  fichier: FileId;
}

/** Represents the initializer for the table public.edge_dossier__fichier_pieces_jointes_petitionnaire */
export interface EdgeDossierFichierPiecesJointesPetitionnaireInitializer {
  dossier: DossierId;

  fichier: FileId;
}

/** Represents the mutator for the table public.edge_dossier__fichier_pieces_jointes_petitionnaire */
export interface EdgeDossierFichierPiecesJointesPetitionnaireMutator {
  dossier?: DossierId;

  fichier?: FileId;
}
