// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CapDossierCap } from "./CapDossier";
import type { GroupeInstructeursId } from "./GroupeInstructeurs";

/** Represents the table public.edge_cap_dossier__groupe_instructeurs */
export default interface EdgeCapDossierGroupeInstructeurs {
  cap_dossier: CapDossierCap;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the initializer for the table public.edge_cap_dossier__groupe_instructeurs */
export interface EdgeCapDossierGroupeInstructeursInitializer {
  cap_dossier: CapDossierCap;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the mutator for the table public.edge_cap_dossier__groupe_instructeurs */
export interface EdgeCapDossierGroupeInstructeursMutator {
  cap_dossier?: CapDossierCap;

  groupe_instructeurs?: GroupeInstructeursId;
}
