// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CapAnnotationWriteCap } from "./CapAnnotationWrite";

/** Represents the table public.edge_personne__cap_annotation_write */
export default interface EdgePersonneCapAnnotationWrite {
  personne_cap: string | null;

  annotation_write_cap: CapAnnotationWriteCap | null;
}

/** Represents the initializer for the table public.edge_personne__cap_annotation_write */
export interface EdgePersonneCapAnnotationWriteInitializer {
  personne_cap?: string | null;

  annotation_write_cap?: CapAnnotationWriteCap | null;
}

/** Represents the mutator for the table public.edge_personne__cap_annotation_write */
export interface EdgePersonneCapAnnotationWriteMutator {
  personne_cap?: string | null;

  annotation_write_cap?: CapAnnotationWriteCap | null;
}
