// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AuthUserId } from "./AuthUser";
import type { DossierId } from "./Dossier";

/** Represents the table public.edge_personne_follows_dossier */
export default interface EdgePersonneFollowsDossier {
  personne: AuthUserId;

  dossier: DossierId;
}

/** Represents the initializer for the table public.edge_personne_follows_dossier */
export interface EdgePersonneFollowsDossierInitializer {
  personne: AuthUserId;

  dossier: DossierId;
}

/** Represents the mutator for the table public.edge_personne_follows_dossier */
export interface EdgePersonneFollowsDossierMutator {
  personne?: AuthUserId;

  dossier?: DossierId;
}
