// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { GroupeInstructeursId } from "./GroupeInstructeurs";

/** Represents the table public.edge_groupe_instructeurs__dossier */
export default interface EdgeGroupeInstructeursDossier {
  dossier: DossierId;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the initializer for the table public.edge_groupe_instructeurs__dossier */
export interface EdgeGroupeInstructeursDossierInitializer {
  dossier: DossierId;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the mutator for the table public.edge_groupe_instructeurs__dossier */
export interface EdgeGroupeInstructeursDossierMutator {
  dossier?: DossierId;

  groupe_instructeurs?: GroupeInstructeursId;
}
