// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.entreprise */
export type EntrepriseSiret = string & { __brand: "public.entreprise" };

/** Represents the table public.entreprise */
export default interface Entreprise {
  siret: EntrepriseSiret;

  legal_name: string | null;

  address: string | null;

  siren: string | null;

  legal_form: string | null;

  naf_code: string | null;

  naf_label: string | null;

  creation_date: string | null;

  admin_status: string | null;

  headcount: string | null;

  share_capital: string | null;

  insee_code: string | null;

  postal_code: string | null;

  department: string | null;

  region: string | null;
}

/** Represents the initializer for the table public.entreprise */
export interface EntrepriseInitializer {
  siret: EntrepriseSiret;

  legal_name?: string | null;

  address?: string | null;

  siren?: string | null;

  legal_form?: string | null;

  naf_code?: string | null;

  naf_label?: string | null;

  creation_date?: string | null;

  admin_status?: string | null;

  headcount?: string | null;

  share_capital?: string | null;

  insee_code?: string | null;

  postal_code?: string | null;

  department?: string | null;

  region?: string | null;
}

/** Represents the mutator for the table public.entreprise */
export interface EntrepriseMutator {
  siret?: EntrepriseSiret;

  legal_name?: string | null;

  address?: string | null;

  siren?: string | null;

  legal_form?: string | null;

  naf_code?: string | null;

  naf_label?: string | null;

  creation_date?: string | null;

  admin_status?: string | null;

  headcount?: string | null;

  share_capital?: string | null;

  insee_code?: string | null;

  postal_code?: string | null;

  department?: string | null;

  region?: string | null;
}
