// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.espece_bdc_statut */
export type EspeceBdcStatutId = string & { __brand: "public.espece_bdc_statut" };

/** Represents the table public.espece_bdc_statut */
export default interface EspeceBdcStatut {
  id: EspeceBdcStatutId;

  cd_nom: string;

  cd_ref: string;

  cd_type_statut: string;

  label_statut: string;
}

/** Represents the initializer for the table public.espece_bdc_statut */
export interface EspeceBdcStatutInitializer {
  /** Default value: nextval('espece_bdc_statut_id_seq'::regclass) */
  id?: EspeceBdcStatutId;

  cd_nom: string;

  cd_ref: string;

  cd_type_statut: string;

  /** Default value: ''::text */
  label_statut?: string;
}

/** Represents the mutator for the table public.espece_bdc_statut */
export interface EspeceBdcStatutMutator {
  id?: EspeceBdcStatutId;

  cd_nom?: string;

  cd_ref?: string;

  cd_type_statut?: string;

  label_statut?: string;
}
