// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view public.espece_protegee */
export default interface EspeceProtegee {
  cd_ref: string;

  classification: string;

  noms_scientifiques: string[];

  noms_vernaculaires: string[];

  cd_type_statuts: string[];

  espece_ministerielle: boolean;

  espece_cnpn: boolean;
}
