// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from "./Personne";

/** Identifier type for public.évènement_métrique */
export type EvenementMetriqueId = string & { __brand: "public.évènement_métrique" };

/** Represents the table public.évènement_métrique */
export default interface EvenementMetrique {
  id: EvenementMetriqueId;

  personne: PersonneId;

  /** Date de l’évènement */
  date: Date;

  /** Type de l’évènement */
  évènement: string;

  /** Données structurées liées donnant des détails sur l’évènement */
  détails: unknown | null;
}

/** Represents the initializer for the table public.évènement_métrique */
export interface EvenementMetriqueInitializer {
  /** Default value: gen_random_uuid() */
  id?: EvenementMetriqueId;

  personne: PersonneId;

  /**
   * Date de l’évènement
   * Default value: CURRENT_TIMESTAMP
   */
  date?: Date;

  /** Type de l’évènement */
  évènement: string;

  /** Données structurées liées donnant des détails sur l’évènement */
  détails?: unknown | null;
}

/** Represents the mutator for the table public.évènement_métrique */
export interface EvenementMetriqueMutator {
  id?: EvenementMetriqueId;

  personne?: PersonneId;

  /** Date de l’évènement */
  date?: Date;

  /** Type de l’évènement */
  évènement?: string;

  /** Données structurées liées donnant des détails sur l’évènement */
  détails?: unknown | null;
}
