// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from "./Personne";

/** Identifier type for public.evenement_metrique */
export type EvenementMetriqueId = string & { __brand: "public.evenement_metrique" };

/** Represents the table public.evenement_metrique */
export default interface EvenementMetrique {
  id: EvenementMetriqueId;

  personne: PersonneId;

  /** Evenement date */
  date: Date;

  /** Evenement type */
  evenement: string;

  /** Related structured data providing details about the evenement */
  details: unknown | null;
}

/** Represents the initializer for the table public.evenement_metrique */
export interface EvenementMetriqueInitializer {
  /** Default value: gen_random_uuid() */
  id?: EvenementMetriqueId;

  personne: PersonneId;

  /**
   * Evenement date
   * Default value: CURRENT_TIMESTAMP
   */
  date?: Date;

  /** Evenement type */
  evenement: string;

  /** Related structured data providing details about the evenement */
  details?: unknown | null;
}

/** Represents the mutator for the table public.evenement_metrique */
export interface EvenementMetriqueMutator {
  id?: EvenementMetriqueId;

  personne?: PersonneId;

  /** Evenement date */
  date?: Date;

  /** Evenement type */
  evenement?: string;

  /** Related structured data providing details about the evenement */
  details?: unknown | null;
}
