// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.file */
export type FileId = string & { __brand: "public.file" };

/** Represents the table public.file */
export default interface File {
  id: FileId;

  name: string;

  media_type: string | null;

  size: string;

  demarche_numerique_checksum: string | null;

  demarche_numerique_created_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.file */
export interface FileInitializer {
  /** Default value: gen_random_uuid() */
  id?: FileId;

  name: string;

  media_type?: string | null;

  size: string;

  demarche_numerique_checksum?: string | null;

  demarche_numerique_created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.file */
export interface FileMutator {
  id?: FileId;

  name?: string;

  media_type?: string | null;

  size?: string;

  demarche_numerique_checksum?: string | null;

  demarche_numerique_created_at?: Date | null;

  created_at?: Date;
}
