// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FileId } from "./File";
import type { AnomalieFichierEspeces } from "../../especesImpact.d.ts";

/** Identifier type for public.file_especes_impactees */
export type FileEspecesImpacteesId = string & { __brand: "public.file_especes_impactees" };

/**
 * Represents the table public.file_especes_impactees
 * An Espèces Impactées file provided by the Porteur de projet.
 */
export default interface FileEspecesImpactees {
  id: FileEspecesImpacteesId;

  file: FileId;

  /** The anomalies contained in Espèces Impactées file provided by the Porteur de projet. Null until the file has been read. */
  anomalies: AnomalieFichierEspeces[] | null;
}

/**
 * Represents the initializer for the table public.file_especes_impactees
 * An Espèces Impactées file provided by the Porteur de projet.
 */
export interface FileEspecesImpacteesInitializer {
  /** Default value: gen_random_uuid() */
  id?: FileEspecesImpacteesId;

  file: FileId;

  /** The anomalies contained in Espèces Impactées file provided by the Porteur de projet. Null until the file has been read. */
  anomalies?: AnomalieFichierEspeces[] | null;
}

/**
 * Represents the mutator for the table public.file_especes_impactees
 * An Espèces Impactées file provided by the Porteur de projet.
 */
export interface FileEspecesImpacteesMutator {
  id?: FileEspecesImpacteesId;

  file?: FileId;

  /** The anomalies contained in Espèces Impactées file provided by the Porteur de projet. Null until the file has been read. */
  anomalies?: AnomalieFichierEspeces[] | null;
}
