// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { GroupeInstructeursId } from "./GroupeInstructeurs";

/** Identifier type for public.groupe_departement */
export type GroupeDepartementDepartment = string & { __brand: "public.groupe_departement" };

/** Represents the table public.groupe_departement */
export default interface GroupeDepartement {
  groupe_instructeurs: GroupeInstructeursId;

  department: GroupeDepartementDepartment;
}

/** Represents the initializer for the table public.groupe_departement */
export interface GroupeDepartementInitializer {
  groupe_instructeurs: GroupeInstructeursId;

  department: GroupeDepartementDepartment;
}

/** Represents the mutator for the table public.groupe_departement */
export interface GroupeDepartementMutator {
  groupe_instructeurs?: GroupeInstructeursId;

  department?: GroupeDepartementDepartment;
}
