// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";

/** Identifier type for public.identite_dossier */
export type IdentiteDossierId = number & { __brand: "public.identite_dossier" };

/** Represents the table public.identite_dossier */
export default interface IdentiteDossier {
  id: IdentiteDossierId;

  dossier: DossierId;

  /** Identity type: 'demandeur', 'mandataire' or 'representant' */
  type: string;

  last_name: string | null;

  first_names: string | null;

  email: string | null;

  /** Only filled for the 'representant' type */
  phone: string | null;

  /** Position within the personne morale, only filled for the 'representant' type */
  role: string | null;
}

/** Represents the initializer for the table public.identite_dossier */
export interface IdentiteDossierInitializer {
  /** Default value: nextval('identite_dossier_id_seq'::regclass) */
  id?: IdentiteDossierId;

  dossier: DossierId;

  /** Identity type: 'demandeur', 'mandataire' or 'representant' */
  type: string;

  last_name?: string | null;

  first_names?: string | null;

  email?: string | null;

  /** Only filled for the 'representant' type */
  phone?: string | null;

  /** Position within the personne morale, only filled for the 'representant' type */
  role?: string | null;
}

/** Represents the mutator for the table public.identite_dossier */
export interface IdentiteDossierMutator {
  id?: IdentiteDossierId;

  dossier?: DossierId;

  /** Identity type: 'demandeur', 'mandataire' or 'representant' */
  type?: string;

  last_name?: string | null;

  first_names?: string | null;

  email?: string | null;

  /** Only filled for the 'representant' type */
  phone?: string | null;

  /** Position within the personne morale, only filled for the 'representant' type */
  role?: string | null;
}
