// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.impact_moyen_de_poursuite */
export type ImpactMoyenDePoursuiteCode = string & { __brand: "public.impact_moyen_de_poursuite" };

/** Identifier type for public.impact_moyen_de_poursuite */
export type ImpactMoyenDePoursuiteClassification = string & {
  __brand: "public.impact_moyen_de_poursuite";
};

/**
 * Represents the table public.impact_moyen_de_poursuite
 * Means of pursuit used to reach the impacted species, offered when the type impact has critere_moyen_de_poursuite. Holds no flore row: the directive defines none. Also called Transport.
 */
export default interface ImpactMoyenDePoursuite {
  /** Means-of-pursuit code from the European directive. Not unique on its own: 0, 1 and 2 each mean one thing in the Oiseaux directive and another in the Habitats directive. */
  code: ImpactMoyenDePoursuiteCode;

  /** Living-being classification this moyen de poursuite can qualify: 'oiseau' or 'faune non-oiseau'. Part of the key, since it is what tells two identical codes apart. */
  classification: ImpactMoyenDePoursuiteClassification;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /** Wording of the means of pursuit in the European directive. */
  libelle_europeen: string;
}

/**
 * Represents the initializer for the table public.impact_moyen_de_poursuite
 * Means of pursuit used to reach the impacted species, offered when the type impact has critere_moyen_de_poursuite. Holds no flore row: the directive defines none. Also called Transport.
 */
export interface ImpactMoyenDePoursuiteInitializer {
  /** Means-of-pursuit code from the European directive. Not unique on its own: 0, 1 and 2 each mean one thing in the Oiseaux directive and another in the Habitats directive. */
  code: ImpactMoyenDePoursuiteCode;

  /** Living-being classification this moyen de poursuite can qualify: 'oiseau' or 'faune non-oiseau'. Part of the key, since it is what tells two identical codes apart. */
  classification: ImpactMoyenDePoursuiteClassification;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /**
   * Wording of the means of pursuit in the European directive.
   * Default value: ''::text
   */
  libelle_europeen?: string;
}

/**
 * Represents the mutator for the table public.impact_moyen_de_poursuite
 * Means of pursuit used to reach the impacted species, offered when the type impact has critere_moyen_de_poursuite. Holds no flore row: the directive defines none. Also called Transport.
 */
export interface ImpactMoyenDePoursuiteMutator {
  /** Means-of-pursuit code from the European directive. Not unique on its own: 0, 1 and 2 each mean one thing in the Oiseaux directive and another in the Habitats directive. */
  code?: ImpactMoyenDePoursuiteCode;

  /** Living-being classification this moyen de poursuite can qualify: 'oiseau' or 'faune non-oiseau'. Part of the key, since it is what tells two identical codes apart. */
  classification?: ImpactMoyenDePoursuiteClassification;

  /** Label shown to users in Pitchou */
  libelle_pitchou?: string;

  /** Wording of the means of pursuit in the European directive. */
  libelle_europeen?: string;
}
