// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.impact_methode */
export type ImpactMethodeCode = string & { __brand: "public.impact_methode" };

/**
 * Represents the table public.impact_methode
 * Methods used to reach the impacted species, offered when the type impact has critere_methode.
 */
export default interface ImpactMethode {
  /** Method code from the European directive. */
  code: ImpactMethodeCode;

  /** Living-being classification this methode can qualify. */
  classification: string;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /** Wording of the method in the European directive */
  libelle_europeen: string;
}

/**
 * Represents the initializer for the table public.impact_methode
 * Methods used to reach the impacted species, offered when the type impact has critere_methode.
 */
export interface ImpactMethodeInitializer {
  /** Method code from the European directive. */
  code: ImpactMethodeCode;

  /** Living-being classification this methode can qualify. */
  classification: string;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /**
   * Wording of the method in the European directive
   * Default value: ''::text
   */
  libelle_europeen?: string;
}

/**
 * Represents the mutator for the table public.impact_methode
 * Methods used to reach the impacted species, offered when the type impact has critere_methode.
 */
export interface ImpactMethodeMutator {
  /** Method code from the European directive. */
  code?: ImpactMethodeCode;

  /** Living-being classification this methode can qualify. */
  classification?: string;

  /** Label shown to users in Pitchou */
  libelle_pitchou?: string;

  /** Wording of the method in the European directive */
  libelle_europeen?: string;
}
