// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { FileId } from "./File";
import type {
  ImpactMoyenDePoursuiteClassification,
  ImpactMoyenDePoursuiteCode,
} from "./ImpactMoyenDePoursuite";
import type { ImpactTypeIdentifiantPitchou } from "./ImpactType";
import type { ImpactMethodeCode } from "./ImpactMethode";

/** Identifier type for public.impact_espece */
export type ImpactEspeceId = string & { __brand: "public.impact_espece" };

/**
 * Represents the table public.impact_espece
 * One row per protected espece impacted by a dossier, and how it is impacted.
 */
export default interface ImpactEspece {
  id: ImpactEspeceId;

  dossier: DossierId;

  /** The file this row was parsed from. */
  source_file: FileId;

  /** TAXREF identifier of the impacted espece. No foreign key: 'espece_protegee' is a view, so Postgres cannot enforce one. A CD_REF missing from the referential is reported to the instructrice rather than imported. */
  cd_ref: string;

  /** Living-being classification of the espece: 'oiseau', 'faune non-oiseau' or 'flore'. Redundant with the espece, but it is half the key of impact_moyen_de_poursuite, so it has to be on the row for that foreign key to exist. */
  classification: ImpactMoyenDePoursuiteClassification;

  /** Type of impact, e.g. 'P-2-1'. Nullable: a file may leave it empty, and those rows are already displayed apart, under 'Type d'impact non renseigné'. */
  impact_type: ImpactTypeIdentifiantPitchou | null;

  impact_methode: ImpactMethodeCode | null;

  /** Means of pursuit used to reach the espece. Only when the type d'impact allows it. */
  impact_moyen_de_poursuite: ImpactMoyenDePoursuiteCode | null;

  /** Number of impacted individuals, as a range such as '11-100'. Not a number. */
  nombre_individus: string | null;

  /** Number of impacted nids. Only ever filled for an oiseau. */
  nids: number | null;

  /** Number of impacted eggs. Only ever filled for an oiseau. */
  oeufs: number | null;

  /** Destroyed habitat area, in square meters. */
  surface_habitat_detruit: number | null;

  created_at: Date;

  updated_at: Date;
}

/**
 * Represents the initializer for the table public.impact_espece
 * One row per protected espece impacted by a dossier, and how it is impacted.
 */
export interface ImpactEspeceInitializer {
  /** Default value: nextval('impact_espece_id_seq'::regclass) */
  id?: ImpactEspeceId;

  dossier: DossierId;

  /** The file this row was parsed from. */
  source_file: FileId;

  /** TAXREF identifier of the impacted espece. No foreign key: 'espece_protegee' is a view, so Postgres cannot enforce one. A CD_REF missing from the referential is reported to the instructrice rather than imported. */
  cd_ref: string;

  /** Living-being classification of the espece: 'oiseau', 'faune non-oiseau' or 'flore'. Redundant with the espece, but it is half the key of impact_moyen_de_poursuite, so it has to be on the row for that foreign key to exist. */
  classification: ImpactMoyenDePoursuiteClassification;

  /** Type of impact, e.g. 'P-2-1'. Nullable: a file may leave it empty, and those rows are already displayed apart, under 'Type d'impact non renseigné'. */
  impact_type?: ImpactTypeIdentifiantPitchou | null;

  impact_methode?: ImpactMethodeCode | null;

  /** Means of pursuit used to reach the espece. Only when the type d'impact allows it. */
  impact_moyen_de_poursuite?: ImpactMoyenDePoursuiteCode | null;

  /** Number of impacted individuals, as a range such as '11-100'. Not a number. */
  nombre_individus?: string | null;

  /** Number of impacted nids. Only ever filled for an oiseau. */
  nids?: number | null;

  /** Number of impacted eggs. Only ever filled for an oiseau. */
  oeufs?: number | null;

  /** Destroyed habitat area, in square meters. */
  surface_habitat_detruit?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/**
 * Represents the mutator for the table public.impact_espece
 * One row per protected espece impacted by a dossier, and how it is impacted.
 */
export interface ImpactEspeceMutator {
  id?: ImpactEspeceId;

  dossier?: DossierId;

  /** The file this row was parsed from. */
  source_file?: FileId;

  /** TAXREF identifier of the impacted espece. No foreign key: 'espece_protegee' is a view, so Postgres cannot enforce one. A CD_REF missing from the referential is reported to the instructrice rather than imported. */
  cd_ref?: string;

  /** Living-being classification of the espece: 'oiseau', 'faune non-oiseau' or 'flore'. Redundant with the espece, but it is half the key of impact_moyen_de_poursuite, so it has to be on the row for that foreign key to exist. */
  classification?: ImpactMoyenDePoursuiteClassification;

  /** Type of impact, e.g. 'P-2-1'. Nullable: a file may leave it empty, and those rows are already displayed apart, under 'Type d'impact non renseigné'. */
  impact_type?: ImpactTypeIdentifiantPitchou | null;

  impact_methode?: ImpactMethodeCode | null;

  /** Means of pursuit used to reach the espece. Only when the type d'impact allows it. */
  impact_moyen_de_poursuite?: ImpactMoyenDePoursuiteCode | null;

  /** Number of impacted individuals, as a range such as '11-100'. Not a number. */
  nombre_individus?: string | null;

  /** Number of impacted nids. Only ever filled for an oiseau. */
  nids?: number | null;

  /** Number of impacted eggs. Only ever filled for an oiseau. */
  oeufs?: number | null;

  /** Destroyed habitat area, in square meters. */
  surface_habitat_detruit?: number | null;

  created_at?: Date;

  updated_at?: Date;
}
