// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.impact_type */
export type ImpactTypeIdentifiantPitchou = string & { __brand: "public.impact_type" };

/**
 * Represents the table public.impact_type
 * Types of impact a projet can have on a protected species, and the criteres that can qualify each of them. Type of impact is called Activité by the European Commission.
 */
export default interface ImpactType {
  /** Pitchou identifier, e.g. 'P-2-1' for 'Type d'impact'. */
  identifiant_pitchou: ImpactTypeIdentifiantPitchou;

  /** Code used when reporting to the European Commission (HaBiDeS+). Not unique: P-70-1, P-70-2 and P-70-3 are three Pitchou types reported under the single code 70. */
  code_europeen: string;

  /** Living-being classification this type impact applies to: 'oiseau', 'faune non-oiseau' or 'flore'. Also decides which methode and moyen_de_poursuite rows can qualify it. */
  classification: string;

  /** Label shown to users in Pitchou. */
  libelle_pitchou: string;

  /** Wording of the activity in the European directive. */
  libelle_europeen: string;

  /** Labels of the Onagre reference activities that correspond to this type impact. Informative: it records how the Onagre vocabulary maps onto the Pitchou one. */
  activites_onagre: string[];

  /** Whether a methode can qualify this type impact. */
  critere_methode: boolean;

  /** Whether a moyen de poursuite can qualify this type impact. */
  critere_moyen_de_poursuite: boolean;

  /** Whether a number of impacted individuals can be given. */
  critere_nombre_individus: boolean;

  /** Whether a number of nids can be given. */
  critere_nids: boolean;

  /** Whether a number of oeufs can be given. */
  critere_oeufs: boolean;

  /** Whether a destroyed habitat area, in m², can be given. */
  critere_surface_habitat_detruit: boolean;
}

/**
 * Represents the initializer for the table public.impact_type
 * Types of impact a projet can have on a protected species, and the criteres that can qualify each of them. Type of impact is called Activité by the European Commission.
 */
export interface ImpactTypeInitializer {
  /** Pitchou identifier, e.g. 'P-2-1' for 'Type d'impact'. */
  identifiant_pitchou: ImpactTypeIdentifiantPitchou;

  /** Code used when reporting to the European Commission (HaBiDeS+). Not unique: P-70-1, P-70-2 and P-70-3 are three Pitchou types reported under the single code 70. */
  code_europeen: string;

  /** Living-being classification this type impact applies to: 'oiseau', 'faune non-oiseau' or 'flore'. Also decides which methode and moyen_de_poursuite rows can qualify it. */
  classification: string;

  /** Label shown to users in Pitchou. */
  libelle_pitchou: string;

  /**
   * Wording of the activity in the European directive.
   * Default value: ''::text
   */
  libelle_europeen?: string;

  /**
   * Labels of the Onagre reference activities that correspond to this type impact. Informative: it records how the Onagre vocabulary maps onto the Pitchou one.
   * Default value: '{}'::text[]
   */
  activites_onagre?: string[];

  /**
   * Whether a methode can qualify this type impact.
   * Default value: false
   */
  critere_methode?: boolean;

  /**
   * Whether a moyen de poursuite can qualify this type impact.
   * Default value: false
   */
  critere_moyen_de_poursuite?: boolean;

  /**
   * Whether a number of impacted individuals can be given.
   * Default value: false
   */
  critere_nombre_individus?: boolean;

  /**
   * Whether a number of nids can be given.
   * Default value: false
   */
  critere_nids?: boolean;

  /**
   * Whether a number of oeufs can be given.
   * Default value: false
   */
  critere_oeufs?: boolean;

  /**
   * Whether a destroyed habitat area, in m², can be given.
   * Default value: false
   */
  critere_surface_habitat_detruit?: boolean;
}

/**
 * Represents the mutator for the table public.impact_type
 * Types of impact a projet can have on a protected species, and the criteres that can qualify each of them. Type of impact is called Activité by the European Commission.
 */
export interface ImpactTypeMutator {
  /** Pitchou identifier, e.g. 'P-2-1' for 'Type d'impact'. */
  identifiant_pitchou?: ImpactTypeIdentifiantPitchou;

  /** Code used when reporting to the European Commission (HaBiDeS+). Not unique: P-70-1, P-70-2 and P-70-3 are three Pitchou types reported under the single code 70. */
  code_europeen?: string;

  /** Living-being classification this type impact applies to: 'oiseau', 'faune non-oiseau' or 'flore'. Also decides which methode and moyen_de_poursuite rows can qualify it. */
  classification?: string;

  /** Label shown to users in Pitchou. */
  libelle_pitchou?: string;

  /** Wording of the activity in the European directive. */
  libelle_europeen?: string;

  /** Labels of the Onagre reference activities that correspond to this type impact. Informative: it records how the Onagre vocabulary maps onto the Pitchou one. */
  activites_onagre?: string[];

  /** Whether a methode can qualify this type impact. */
  critere_methode?: boolean;

  /** Whether a moyen de poursuite can qualify this type impact. */
  critere_moyen_de_poursuite?: boolean;

  /** Whether a number of impacted individuals can be given. */
  critere_nombre_individus?: boolean;

  /** Whether a number of nids can be given. */
  critere_nids?: boolean;

  /** Whether a number of oeufs can be given. */
  critere_oeufs?: boolean;

  /** Whether a destroyed habitat area, in m², can be given. */
  critere_surface_habitat_detruit?: boolean;
}
