// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.methode */
export type MethodeCode = string & { __brand: "public.methode" };

/**
 * Represents the table public.methode
 * Methods used to reach the impacted species, offered when the type impact has critere_methode.
 */
export default interface Methode {
  /** Method code from the European directive. */
  code: MethodeCode;

  /** Living-being classification this methode can qualify. */
  classification: string;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /** Wording of the method in the European directive */
  libelle_europeen: string;
}

/**
 * Represents the initializer for the table public.methode
 * Methods used to reach the impacted species, offered when the type impact has critere_methode.
 */
export interface MethodeInitializer {
  /** Method code from the European directive. */
  code: MethodeCode;

  /** Living-being classification this methode can qualify. */
  classification: string;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /**
   * Wording of the method in the European directive
   * Default value: ''::text
   */
  libelle_europeen?: string;
}

/**
 * Represents the mutator for the table public.methode
 * Methods used to reach the impacted species, offered when the type impact has critere_methode.
 */
export interface MethodeMutator {
  /** Method code from the European directive. */
  code?: MethodeCode;

  /** Living-being classification this methode can qualify. */
  classification?: string;

  /** Label shown to users in Pitchou */
  libelle_pitchou?: string;

  /** Wording of the method in the European directive */
  libelle_europeen?: string;
}
