// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.moyen_de_poursuite */
export type MoyenDePoursuiteCode = string & { __brand: "public.moyen_de_poursuite" };

/** Identifier type for public.moyen_de_poursuite */
export type MoyenDePoursuiteClassification = string & { __brand: "public.moyen_de_poursuite" };

/**
 * Represents the table public.moyen_de_poursuite
 * Means of pursuit used to reach the impacted species, offered when the type impact has critere_moyen_de_poursuite. Holds no flore row: the directive defines none. Also called Transport.
 */
export default interface MoyenDePoursuite {
  /** Means-of-pursuit code from the European directive. Not unique on its own: 0, 1 and 2 each mean one thing in the Oiseaux directive and another in the Habitats directive. */
  code: MoyenDePoursuiteCode;

  /** Living-being classification this moyen de poursuite can qualify: 'oiseau' or 'faune non-oiseau'. Part of the key, since it is what tells two identical codes apart. */
  classification: MoyenDePoursuiteClassification;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /** Wording of the means of pursuit in the European directive. */
  libelle_europeen: string;
}

/**
 * Represents the initializer for the table public.moyen_de_poursuite
 * Means of pursuit used to reach the impacted species, offered when the type impact has critere_moyen_de_poursuite. Holds no flore row: the directive defines none. Also called Transport.
 */
export interface MoyenDePoursuiteInitializer {
  /** Means-of-pursuit code from the European directive. Not unique on its own: 0, 1 and 2 each mean one thing in the Oiseaux directive and another in the Habitats directive. */
  code: MoyenDePoursuiteCode;

  /** Living-being classification this moyen de poursuite can qualify: 'oiseau' or 'faune non-oiseau'. Part of the key, since it is what tells two identical codes apart. */
  classification: MoyenDePoursuiteClassification;

  /** Label shown to users in Pitchou */
  libelle_pitchou: string;

  /**
   * Wording of the means of pursuit in the European directive.
   * Default value: ''::text
   */
  libelle_europeen?: string;
}

/**
 * Represents the mutator for the table public.moyen_de_poursuite
 * Means of pursuit used to reach the impacted species, offered when the type impact has critere_moyen_de_poursuite. Holds no flore row: the directive defines none. Also called Transport.
 */
export interface MoyenDePoursuiteMutator {
  /** Means-of-pursuit code from the European directive. Not unique on its own: 0, 1 and 2 each mean one thing in the Oiseaux directive and another in the Habitats directive. */
  code?: MoyenDePoursuiteCode;

  /** Living-being classification this moyen de poursuite can qualify: 'oiseau' or 'faune non-oiseau'. Part of the key, since it is what tells two identical codes apart. */
  classification?: MoyenDePoursuiteClassification;

  /** Label shown to users in Pitchou */
  libelle_pitchou?: string;

  /** Wording of the means of pursuit in the European directive. */
  libelle_europeen?: string;
}
