// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from "./Personne";
import type { DossierId } from "./Dossier";

/** Identifier type for public.notification */
export type NotificationId = string & { __brand: "public.notification" };

/** Represents the table public.notification */
export default interface Notification {
  id: NotificationId;

  /** Date on which the notification was last updated */
  updated_at: Date | null;

  /** Indicates whether the personne has viewed the notification */
  viewed: boolean;

  personne: PersonneId;

  dossier: DossierId;
}

/** Represents the initializer for the table public.notification */
export interface NotificationInitializer {
  /** Default value: gen_random_uuid() */
  id?: NotificationId;

  /**
   * Date on which the notification was last updated
   * Default value: CURRENT_TIMESTAMP
   */
  updated_at?: Date | null;

  /**
   * Indicates whether the personne has viewed the notification
   * Default value: false
   */
  viewed?: boolean;

  personne: PersonneId;

  dossier: DossierId;
}

/** Represents the mutator for the table public.notification */
export interface NotificationMutator {
  id?: NotificationId;

  /** Date on which the notification was last updated */
  updated_at?: Date | null;

  /** Indicates whether the personne has viewed the notification */
  viewed?: boolean;

  personne?: PersonneId;

  dossier?: DossierId;
}
