// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonneId } from "./Personne";
import type { DossierId } from "./Dossier";

/** Identifier type for public.notification */
export type NotificationId = string & { __brand: "public.notification" };

/** Represents the table public.notification */
export default interface Notification {
  id: NotificationId;

  /** Latest detected applicant change, including acknowledged revisions */
  updated_at: Date | null;

  /** Indicates whether the personne has viewed the notification */
  viewed: boolean;

  personne: PersonneId;

  dossier: DossierId;

  /** Last arrival/follow dismissal; historical read boundary used only by the migration. */
  viewed_at: Date | null;

  arrival_viewed: boolean;

  follow_revision: string | null;

  follow_at: Date | null;

  /** Whether this recipient existed before per-revision review was introduced. */
  receive_legacy_changes: boolean;
}

/** Represents the initializer for the table public.notification */
export interface NotificationInitializer {
  /** Default value: gen_random_uuid() */
  id?: NotificationId;

  /** Latest detected applicant change, including acknowledged revisions */
  updated_at?: Date | null;

  /**
   * Indicates whether the personne has viewed the notification
   * Default value: false
   */
  viewed?: boolean;

  personne: PersonneId;

  dossier: DossierId;

  /** Last arrival/follow dismissal; historical read boundary used only by the migration. */
  viewed_at?: Date | null;

  /** Default value: false */
  arrival_viewed?: boolean;

  follow_revision?: string | null;

  follow_at?: Date | null;

  /** Default value: false */
  receive_legacy_changes?: boolean;
}

/** Represents the mutator for the table public.notification */
export interface NotificationMutator {
  id?: NotificationId;

  /** Latest detected applicant change, including acknowledged revisions */
  updated_at?: Date | null;

  /** Indicates whether the personne has viewed the notification */
  viewed?: boolean;

  personne?: PersonneId;

  dossier?: DossierId;

  /** Last arrival/follow dismissal; historical read boundary used only by the migration. */
  viewed_at?: Date | null;

  arrival_viewed?: boolean;

  follow_revision?: string | null;

  follow_at?: Date | null;

  receive_legacy_changes?: boolean;
}
