// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActionDossierId } from "./ActionDossier";
import type { AuthUserId } from "./AuthUser";

/** Represents the table public.notification_review */
export default interface NotificationReview {
  action: ActionDossierId;

  personne: AuthUserId;
}

/** Represents the initializer for the table public.notification_review */
export interface NotificationReviewInitializer {
  action: ActionDossierId;

  personne: AuthUserId;
}

/** Represents the mutator for the table public.notification_review */
export interface NotificationReviewMutator {
  action?: ActionDossierId;

  personne?: AuthUserId;
}
