// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";

/** Represents the table public.notification_arrival */
export default interface NotificationArrival {
  dossier: DossierId;

  created_at: Date;
}

/** Represents the initializer for the table public.notification_arrival */
export interface NotificationArrivalInitializer {
  dossier: DossierId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.notification_arrival */
export interface NotificationArrivalMutator {
  dossier?: DossierId;

  created_at?: Date;
}
