// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActionDossierId } from "./ActionDossier";
import type { PersonneId } from "./Personne";

/** Represents the table public.notification_review */
export default interface NotificationReview {
  action: ActionDossierId;

  personne: PersonneId;
}

/** Represents the initializer for the table public.notification_review */
export interface NotificationReviewInitializer {
  action: ActionDossierId;

  personne: PersonneId;
}

/** Represents the mutator for the table public.notification_review */
export interface NotificationReviewMutator {
  action?: ActionDossierId;

  personne?: PersonneId;
}
