// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DossierId } from "./Dossier";
import type { FileId } from "./File";

/** Identifier type for public.other_attachment */
export type OtherAttachmentId = string & { __brand: "public.other_attachment" };

/** Represents the table public.other_attachment */
export default interface OtherAttachment {
  id: OtherAttachmentId;

  dossier: DossierId;

  fichier: FileId;

  type: string;

  attachment_date: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.other_attachment */
export interface OtherAttachmentInitializer {
  /** Default value: gen_random_uuid() */
  id?: OtherAttachmentId;

  dossier: DossierId;

  fichier: FileId;

  type: string;

  attachment_date?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.other_attachment */
export interface OtherAttachmentMutator {
  id?: OtherAttachmentId;

  dossier?: DossierId;

  fichier?: FileId;

  type?: string;

  attachment_date?: Date | null;

  created_at?: Date;
}
