// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.personne_physique */
export type PersonnePhysiqueId = number & { __brand: "public.personne_physique" };

/**
 * Represents the table public.personne_physique
 * Contains the natural persons that can be linked to one or more dossiers.
 */
export default interface PersonnePhysique {
  id: PersonnePhysiqueId;

  first_names: string | null;

  last_name: string | null;

  email: string | null;

  /** Postal address description */
  address: string | null;

  phone: string | null;

  /** Functions / professional titles / roles of the person or contact (free text) */
  role: string | null;
}

/**
 * Represents the initializer for the table public.personne_physique
 * Contains the natural persons that can be linked to one or more dossiers.
 */
export interface PersonnePhysiqueInitializer {
  /** Default value: nextval('personne_physique_id_seq'::regclass) */
  id?: PersonnePhysiqueId;

  first_names?: string | null;

  last_name?: string | null;

  email?: string | null;

  /** Postal address description */
  address?: string | null;

  phone?: string | null;

  /** Functions / professional titles / roles of the person or contact (free text) */
  role?: string | null;
}

/**
 * Represents the mutator for the table public.personne_physique
 * Contains the natural persons that can be linked to one or more dossiers.
 */
export interface PersonnePhysiqueMutator {
  id?: PersonnePhysiqueId;

  first_names?: string | null;

  last_name?: string | null;

  email?: string | null;

  /** Postal address description */
  address?: string | null;

  phone?: string | null;

  /** Functions / professional titles / roles of the person or contact (free text) */
  role?: string | null;
}
