// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.personne */
export type PersonneId = number & { __brand: "public.personne" };

/** Represents the table public.personne */
export default interface Personne {
  id: PersonneId;

  /** Personne last name. Civil identity */
  last_name: string | null;

  /** Personne first names. Civil identity */
  first_names: string | null;

  /** Personne email address. Used for communication, authentication, and unique user identification in the system. */
  email: string | null;

  /** Unique access code of the personne. Used to retrieve a set of capabilities, particularly from the edge_cap_dossier__groupe_instructeurs table */
  access_code: string | null;

  address: string | null;

  phone: string | null;

  role: string | null;
}

/** Represents the initializer for the table public.personne */
export interface PersonneInitializer {
  /** Default value: nextval('personne_id_seq'::regclass) */
  id?: PersonneId;

  /** Personne last name. Civil identity */
  last_name?: string | null;

  /** Personne first names. Civil identity */
  first_names?: string | null;

  /** Personne email address. Used for communication, authentication, and unique user identification in the system. */
  email?: string | null;

  /** Unique access code of the personne. Used to retrieve a set of capabilities, particularly from the edge_cap_dossier__groupe_instructeurs table */
  access_code?: string | null;

  address?: string | null;

  phone?: string | null;

  role?: string | null;
}

/** Represents the mutator for the table public.personne */
export interface PersonneMutator {
  id?: PersonneId;

  /** Personne last name. Civil identity */
  last_name?: string | null;

  /** Personne first names. Civil identity */
  first_names?: string | null;

  /** Personne email address. Used for communication, authentication, and unique user identification in the system. */
  email?: string | null;

  /** Unique access code of the personne. Used to retrieve a set of capabilities, particularly from the edge_cap_dossier__groupe_instructeurs table */
  access_code?: string | null;

  address?: string | null;

  phone?: string | null;

  role?: string | null;
}
