// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface pitchou_can_instruct_params {
  user_id: number;
}

/** Return type for pitchou_can_instruct */
export type pitchou_can_instruct_return_type = boolean;
