// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonnePhysiqueId } from "./PersonnePhysique";
import type { EntrepriseSiret } from "./Entreprise";

/** Identifier type for public.porteur_de_projet */
export type PorteurDeProjetId = number & { __brand: "public.porteur_de_projet" };

/**
 * Represents the table public.porteur_de_projet
 * Contains the porteurs de projet, also called "bénéficiaire": the party that may benefit from the derogation request. Either a personne physique, or a personne morale (association, company, local authority).
 */
export default interface PorteurDeProjet {
  id: PorteurDeProjetId;

  personne_physique: PersonnePhysiqueId | null;

  personne_morale: EntrepriseSiret | null;
}

/**
 * Represents the initializer for the table public.porteur_de_projet
 * Contains the porteurs de projet, also called "bénéficiaire": the party that may benefit from the derogation request. Either a personne physique, or a personne morale (association, company, local authority).
 */
export interface PorteurDeProjetInitializer {
  /** Default value: nextval('porteur_de_projet_id_seq'::regclass) */
  id?: PorteurDeProjetId;

  personne_physique?: PersonnePhysiqueId | null;

  personne_morale?: EntrepriseSiret | null;
}

/**
 * Represents the mutator for the table public.porteur_de_projet
 * Contains the porteurs de projet, also called "bénéficiaire": the party that may benefit from the derogation request. Either a personne physique, or a personne morale (association, company, local authority).
 */
export interface PorteurDeProjetMutator {
  id?: PorteurDeProjetId;

  personne_physique?: PersonnePhysiqueId | null;

  personne_morale?: EntrepriseSiret | null;
}
