// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DecisionAdministrativeId } from "./DecisionAdministrative";

/** Identifier type for public.prescription */
export type PrescriptionId = string & { __brand: "public.prescription" };

/** Represents the table public.prescription */
export default interface Prescription {
  id: PrescriptionId;

  /** Reference to the decision administrative associated with this prescription. A decision administrative can contain several prescriptions detailing the specific obligations to fulfill. */
  decision_administrative: DecisionAdministrativeId;

  /** Deadline by which the prescription must be fulfilled. Controles of this prescription are performed once the due date has passed. */
  due_date: Date | null;

  /** Article number of the prescription. Used to identify and precisely reference the prescription within the decision administrative. */
  article_number: string | null;

  /** Detailed description of the prescription. Explains precisely what must be done, how, and under what conditions to fulfill the imposed obligation. */
  description: string | null;

  /** Surface area in m² avoided through the implemented protection mesures. */
  avoided_surface: number | null;

  /** Surface area in m² compensated to mitigate the project's impacts. */
  compensated_surface: number | null;

  /** For a dossier impacting a bird espece. Number of nests avoided through the implemented protection mesures. */
  avoided_nids: number | null;

  /** For a dossier impacting a bird espece. Number of nests compensated to mitigate the project's impacts. */
  compensated_nids: number | null;

  /** Number of individus avoided through the implemented protection mesures. */
  avoided_individus: number | null;

  /** Number of individus compensated to mitigate the project's impacts. */
  compensated_individus: number | null;
}

/** Represents the initializer for the table public.prescription */
export interface PrescriptionInitializer {
  /** Default value: gen_random_uuid() */
  id?: PrescriptionId;

  /** Reference to the decision administrative associated with this prescription. A decision administrative can contain several prescriptions detailing the specific obligations to fulfill. */
  decision_administrative: DecisionAdministrativeId;

  /** Deadline by which the prescription must be fulfilled. Controles of this prescription are performed once the due date has passed. */
  due_date?: Date | null;

  /** Article number of the prescription. Used to identify and precisely reference the prescription within the decision administrative. */
  article_number?: string | null;

  /** Detailed description of the prescription. Explains precisely what must be done, how, and under what conditions to fulfill the imposed obligation. */
  description?: string | null;

  /** Surface area in m² avoided through the implemented protection mesures. */
  avoided_surface?: number | null;

  /** Surface area in m² compensated to mitigate the project's impacts. */
  compensated_surface?: number | null;

  /** For a dossier impacting a bird espece. Number of nests avoided through the implemented protection mesures. */
  avoided_nids?: number | null;

  /** For a dossier impacting a bird espece. Number of nests compensated to mitigate the project's impacts. */
  compensated_nids?: number | null;

  /** Number of individus avoided through the implemented protection mesures. */
  avoided_individus?: number | null;

  /** Number of individus compensated to mitigate the project's impacts. */
  compensated_individus?: number | null;
}

/** Represents the mutator for the table public.prescription */
export interface PrescriptionMutator {
  id?: PrescriptionId;

  /** Reference to the decision administrative associated with this prescription. A decision administrative can contain several prescriptions detailing the specific obligations to fulfill. */
  decision_administrative?: DecisionAdministrativeId;

  /** Deadline by which the prescription must be fulfilled. Controles of this prescription are performed once the due date has passed. */
  due_date?: Date | null;

  /** Article number of the prescription. Used to identify and precisely reference the prescription within the decision administrative. */
  article_number?: string | null;

  /** Detailed description of the prescription. Explains precisely what must be done, how, and under what conditions to fulfill the imposed obligation. */
  description?: string | null;

  /** Surface area in m² avoided through the implemented protection mesures. */
  avoided_surface?: number | null;

  /** Surface area in m² compensated to mitigate the project's impacts. */
  compensated_surface?: number | null;

  /** For a dossier impacting a bird espece. Number of nests avoided through the implemented protection mesures. */
  avoided_nids?: number | null;

  /** For a dossier impacting a bird espece. Number of nests compensated to mitigate the project's impacts. */
  compensated_nids?: number | null;

  /** Number of individus avoided through the implemented protection mesures. */
  avoided_individus?: number | null;

  /** Number of individus compensated to mitigate the project's impacts. */
  compensated_individus?: number | null;
}
