// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.résultat_synchronisation_DS_88444 */
export default interface ResultatSynchronisationDS {
  succès: boolean;

  horodatage: Date;

  erreur: string | null;
}

/** Represents the initializer for the table public.résultat_synchronisation_DS_88444 */
export interface ResultatSynchronisationDSInitializer {
  succès: boolean;

  horodatage: Date;

  erreur?: string | null;
}

/** Represents the mutator for the table public.résultat_synchronisation_DS_88444 */
export interface ResultatSynchronisationDSMutator {
  succès?: boolean;

  horodatage?: Date;

  erreur?: string | null;
}
