// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.session */
export type SessionId = string & { __brand: "public.session" };

/** Represents the table public.session */
export default interface Session {
  id: SessionId;

  email: string;

  name: string;

  id_token: string | null;

  date_created: Date;

  date_expired: Date;
}

/** Represents the initializer for the table public.session */
export interface SessionInitializer {
  id: SessionId;

  email: string;

  /** Default value: ''::text */
  name?: string;

  id_token?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  date_created?: Date;

  date_expired: Date;
}

/** Represents the mutator for the table public.session */
export interface SessionMutator {
  id?: SessionId;

  email?: string;

  name?: string;

  id_token?: string | null;

  date_created?: Date;

  date_expired?: Date;
}
