// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.type_dossier */
type TypeDossier = "Hirondelle" | "Cigogne";

export type { TypeDossier as default };
