// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AuthUserId } from "./AuthUser";
import type { GroupeInstructeursId } from "./GroupeInstructeurs";

/** Represents the table public.user_groupe */
export default interface UserGroupe {
  user_id: AuthUserId;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the initializer for the table public.user_groupe */
export interface UserGroupeInitializer {
  user_id: AuthUserId;

  groupe_instructeurs: GroupeInstructeursId;
}

/** Represents the mutator for the table public.user_groupe */
export interface UserGroupeMutator {
  user_id?: AuthUserId;

  groupe_instructeurs?: GroupeInstructeursId;
}
