import type { Knex } from "knex";

import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

const TAXREF: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "8332",
    cd_ref: "8332",
    lb_nom: "Cicindela sylvatica",
    nom_vern: "Cicindèle à labre noir",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "251458",
    cd_ref: "8332",
    lb_nom: "Cicindela sylvatica sylvatica",
    nom_vern: "Cicindèle à labre noir",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9266",
    cd_ref: "9266",
    lb_nom: "Ophonus cordatus",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "798822",
    cd_ref: "9266",
    lb_nom: "Carabus cordatus",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "395528",
    cd_ref: "9266",
    lb_nom: "Carabus porosus",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "395529",
    cd_ref: "9266",
    lb_nom: "Harpalus iberiae",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9370",
    cd_ref: "9370",
    lb_nom: "Oodes gracilis",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "808473",
    cd_ref: "9370",
    lb_nom: "Oodes gracilior",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "967142",
    cd_ref: "9370",
    lb_nom: "Oodes gracilior",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "967141",
    cd_ref: "9370",
    lb_nom: "Oodes similis",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9074",
    cd_ref: "9074",
    lb_nom: "Pterostichus aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "799002",
    cd_ref: "9074",
    lb_nom: "Carabus aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9077",
    cd_ref: "9074",
    lb_nom: "Omaseus aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9075",
    cd_ref: "9074",
    lb_nom: "Pterostichus (Argutor) aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "417000",
    cd_ref: "417000",
    lb_nom: "Antanartia borbonica",
    nom_vern: "Vanesse de l’Obetie",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "812102",
    cd_ref: "417000",
    lb_nom: "Vanessa borbonica",
    nom_vern: "Vanesse de l’Obetie",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "985508",
    cd_ref: "417000",
    lb_nom: "Vanessa hippomene",
    nom_vern: "Vanesse de l’Obetie",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "416999",
    cd_ref: "416999",
    lb_nom: "Papilio phorbanta",
    nom_vern: "Papillon la Pâture",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "985500",
    cd_ref: "416999",
    lb_nom: "Papilio disparilis",
    nom_vern: "Papillon la Pâture",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "212",
    cd_ref: "212",
    lb_nom: "Bombina variegata",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "214",
    cd_ref: "212",
    lb_nom: "Rana variegata",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1020126",
    cd_ref: "212",
    lb_nom: "Bombina salsa",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1042155",
    cd_ref: "212",
    lb_nom: "Bombinator igneus",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "292",
    cd_ref: "292",
    lb_nom: "Hyla meridionalis",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "286",
    cd_ref: "292",
    lb_nom: "Hyla africana",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "294",
    cd_ref: "292",
    lb_nom: "Hyla arborea var. meridionalis",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "296",
    cd_ref: "292",
    lb_nom: "Hyla barytonus",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "295",
    cd_ref: "292",
    lb_nom: "Hyla perezii",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1009333",
    cd_ref: "292",
    lb_nom: "Hyla arborea meridionalis",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "240",
    cd_ref: "240",
    lb_nom: "Pelobates fuscus",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "242",
    cd_ref: "240",
    lb_nom: "Bufo fuscus",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "243",
    cd_ref: "240",
    lb_nom: "Cultripes minor",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "699685",
    cd_ref: "240",
    lb_nom: "Pelobates fuscus fuscus",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "299",
    cd_ref: "299",
    lb_nom: "Rana arvalis",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "302",
    cd_ref: "299",
    lb_nom: "Rana palustris",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "303",
    cd_ref: "299",
    lb_nom: "Rana ulginosa",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1056557",
    cd_ref: "299",
    lb_nom: "Rana terrestris",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "59",
    cd_ref: "59",
    lb_nom: "Euproctus montanus",
    nom_vern: "Euprocte de Corse (L')",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "61",
    cd_ref: "59",
    lb_nom: "Megapterna montana",
    nom_vern: "Euprocte de Corse (L')",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "86",
    cd_ref: "86",
    lb_nom: "Salamandra atra atra",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "17",
    cd_ref: "86",
    lb_nom: "Geotriton fuscus",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "82",
    cd_ref: "86",
    lb_nom: "Salamandra atra",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "84",
    cd_ref: "86",
    lb_nom: "Salamandra fusca",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "85",
    cd_ref: "86",
    lb_nom: "Salamandra nigra",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "92",
    cd_ref: "92",
    lb_nom: "Salamandra salamandra",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "94",
    cd_ref: "92",
    lb_nom: "Lacerta salamandra",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "95",
    cd_ref: "92",
    lb_nom: "Salamandra maculata",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "96",
    cd_ref: "92",
    lb_nom: "Salamandra maculosa",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "98",
    cd_ref: "92",
    lb_nom: "Salamandra vulgaris",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "97",
    cd_ref: "92",
    lb_nom: "Triton corthyphorus",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "100",
    cd_ref: "100",
    lb_nom: "Salamandra salamandra salamandra",
    nom_vern: "",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "139",
    cd_ref: "139",
    lb_nom: "Triturus cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "145",
    cd_ref: "139",
    lb_nom: "Lacerta lacustris",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "144",
    cd_ref: "139",
    lb_nom: "Lacerta triton",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "143",
    cd_ref: "139",
    lb_nom: "Salamandra lati-caudata",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "142",
    cd_ref: "139",
    lb_nom: "Salamandra platyura",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "141",
    cd_ref: "139",
    lb_nom: "Triton cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "147",
    cd_ref: "139",
    lb_nom: "Triton intermedius",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "146",
    cd_ref: "139",
    lb_nom: "Triton trouessarti",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "951901",
    cd_ref: "139",
    lb_nom: "Triturus cristatus cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "79256",
    cd_ref: "139",
    lb_nom: "Triturus (cristatus) cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1046385",
    cd_ref: "139",
    lb_nom: "Molge cristata",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "185961",
    cd_ref: "185961",
    lb_nom: "Aves",
    nom_vern: "Oiseaux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2869",
    cd_ref: "2869",
    lb_nom: "Aegypius monachus",
    nom_vern: "Vautour moine",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2871",
    cd_ref: "2869",
    lb_nom: "Vultur monachus",
    nom_vern: "Vautour moine",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2645",
    cd_ref: "2645",
    lb_nom: "Aquila chrysaetos",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "416681",
    cd_ref: "2645",
    lb_nom: "Aquila fulva",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2647",
    cd_ref: "2645",
    lb_nom: "Falco chrysaetos",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "846567",
    cd_ref: "2645",
    lb_nom: "Falco fulvus",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2657",
    cd_ref: "2657",
    lb_nom: "Aquila fasciata",
    nom_vern: "Aigle de Bonelli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2655",
    cd_ref: "2657",
    lb_nom: "Hieraaetus fasciatus",
    nom_vern: "Aigle de Bonelli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "432596",
    cd_ref: "432596",
    lb_nom: "Circus maillardi",
    nom_vern: "Busard de Maillard",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2852",
    cd_ref: "2852",
    lb_nom: "Gypaetus barbatus",
    nom_vern: "Gypaète barbu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2854",
    cd_ref: "2852",
    lb_nom: "Vultur barbatus",
    nom_vern: "Gypaète barbu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2660",
    cd_ref: "2660",
    lb_nom: "Pandion haliaetus",
    nom_vern: "Balbuzard pêcheur",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2662",
    cd_ref: "2660",
    lb_nom: "Falco haliaetus",
    nom_vern: "Balbuzard pêcheur",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1973",
    cd_ref: "1973",
    lb_nom: "Anas acuta",
    nom_vern: "Canard pilet",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1948",
    cd_ref: "1948",
    lb_nom: "Anas bahamensis",
    nom_vern: "Canard des Bahamas, Pilet des Bahamas",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1958",
    cd_ref: "1958",
    lb_nom: "Anas crecca",
    nom_vern: "Sarcelle d'hiver",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1960",
    cd_ref: "1960",
    lb_nom: "Anas crecca crecca",
    nom_vern: "Sarcelle d'hiver",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1988",
    cd_ref: "1988",
    lb_nom: "Aythya collaris",
    nom_vern: "Fuligule à bec cerclé, Fuligule à collier, Morillon à collier",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1990",
    cd_ref: "1988",
    lb_nom: "Anas collaris",
    nom_vern: "Fuligule à bec cerclé, Fuligule à collier, Morillon à collier",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1955",
    cd_ref: "1955",
    lb_nom: "Mareca americana",
    nom_vern: "Canard à front blanc, Canard d'Amérique, Canard siffleur d'Amérique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1953",
    cd_ref: "1955",
    lb_nom: "Anas americana",
    nom_vern: "Canard à front blanc, Canard d'Amérique, Canard siffleur d'Amérique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1972",
    cd_ref: "1972",
    lb_nom: "Spatula clypeata",
    nom_vern: "Canard souchet",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1970",
    cd_ref: "1972",
    lb_nom: "Anas clypeata",
    nom_vern: "Canard souchet",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2709",
    cd_ref: "2709",
    lb_nom: "Cygnus columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2711",
    cd_ref: "2709",
    lb_nom: "Anas Columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2703",
    cd_ref: "2709",
    lb_nom: "Cygnus colombianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2713",
    cd_ref: "2709",
    lb_nom: "Cygnus columbianus columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2712",
    cd_ref: "2709",
    lb_nom: "Olor columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2826",
    cd_ref: "2826",
    lb_nom: "Oxyura leucocephala",
    nom_vern: "Érismature à tête blanche",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2828",
    cd_ref: "2826",
    lb_nom: "Anas leucocephala",
    nom_vern: "Érismature à tête blanche",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "199352",
    cd_ref: "199352",
    lb_nom: "Calidris tenuirostris",
    nom_vern: "Bécasseau de l'Anadyr",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "927283",
    cd_ref: "199352",
    lb_nom: "Totanus tenuirostris",
    nom_vern: "Bécasseau de l'Anadyr",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "199363",
    cd_ref: "199363",
    lb_nom: "Heteroscelus brevipes",
    nom_vern: "Chevalier de Sibérie",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "814097",
    cd_ref: "199363",
    lb_nom: "Totanus brevipes",
    nom_vern: "Chevalier de Sibérie",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "442470",
    cd_ref: "199363",
    lb_nom: "Tringa brevipes",
    nom_vern: "Chevalier de Sibérie",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2557",
    cd_ref: "2557",
    lb_nom: "Limnodromus griseus",
    nom_vern: "Bécassin à bec court, Limnodrome à bec court, Bécassin roux, Grise à long bec",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "814241",
    cd_ref: "2557",
    lb_nom: "Scolopax grisea",
    nom_vern: "Bécassin à bec court, Limnodrome à bec court, Bécassin roux, Grise à long bec",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "199357",
    cd_ref: "199357",
    lb_nom: "Numenius minutus",
    nom_vern: "Courlis nain",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2571",
    cd_ref: "2571",
    lb_nom: "Numenius phaeopus",
    nom_vern: "Courlis corlieu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2573",
    cd_ref: "2571",
    lb_nom: "Scolopax phaeopus",
    nom_vern: "Courlis corlieu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3420",
    cd_ref: "3420",
    lb_nom: "Columba livia",
    nom_vern: "Pigeon biset",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3429",
    cd_ref: "3429",
    lb_nom: "Streptopelia decaocto",
    nom_vern: "Tourterelle turque",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3431",
    cd_ref: "3429",
    lb_nom: "Columba decaocto",
    nom_vern: "Tourterelle turque",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961155",
    cd_ref: "3429",
    lb_nom: "Columba risoria L. var. decaocto",
    nom_vern: "Tourterelle turque",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2666",
    cd_ref: "2666",
    lb_nom: "Falco naumanni",
    nom_vern: "Faucon crécerellette",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2668",
    cd_ref: "2666",
    lb_nom: "Cerchneis naumanni",
    nom_vern: "Faucon crécerellette",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "953",
    cd_ref: "953",
    lb_nom: "Gavia adamsii",
    nom_vern: "Plongeon à bec blanc",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "955",
    cd_ref: "953",
    lb_nom: "Colymbus adamsii",
    nom_vern: "Plongeon à bec blanc",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "956",
    cd_ref: "956",
    lb_nom: "Gavia arctica",
    nom_vern: "Plongeon arctique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "958",
    cd_ref: "956",
    lb_nom: "Colymbus arcticus",
    nom_vern: "Plongeon arctique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "959",
    cd_ref: "959",
    lb_nom: "Gavia immer",
    nom_vern: "Plongeon imbrin",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961",
    cd_ref: "959",
    lb_nom: "Colymbus immer",
    nom_vern: "Plongeon imbrin",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3053",
    cd_ref: "3053",
    lb_nom: "Crex crex",
    nom_vern: "Râle des genêts",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3055",
    cd_ref: "3053",
    lb_nom: "Rallus crex",
    nom_vern: "Râle des genêts",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1053763",
    cd_ref: "3053",
    lb_nom: "Crex pratensis",
    nom_vern: "Râle des genêts",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3089",
    cd_ref: "3089",
    lb_nom: "Tetrax tetrax",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961340",
    cd_ref: "3089",
    lb_nom: "Otis tetrax orientalis",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3091",
    cd_ref: "3089",
    lb_nom: "Otis tetrax",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3092",
    cd_ref: "3089",
    lb_nom: "Tetrax tetrax orientalis",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3093",
    cd_ref: "3089",
    lb_nom: "Tetrax tetrax tetrax",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2473",
    cd_ref: "2473",
    lb_nom: "Botaurus stellaris",
    nom_vern: "Butor étoilé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2475",
    cd_ref: "2473",
    lb_nom: "Ardea stellaris",
    nom_vern: "Butor étoilé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2477",
    cd_ref: "2477",
    lb_nom: "Ixobrychus minutus",
    nom_vern: "Blongios nain, Butor blongios",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2479",
    cd_ref: "2477",
    lb_nom: "Ardea minuta",
    nom_vern: "Blongios nain, Butor blongios",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2514",
    cd_ref: "2514",
    lb_nom: "Ciconia nigra",
    nom_vern: "Cigogne noire",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2516",
    cd_ref: "2514",
    lb_nom: "Ardea nigra",
    nom_vern: "Cigogne noire",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "971",
    cd_ref: "971",
    lb_nom: "Podiceps auritus",
    nom_vern: "Grèbe esclavon",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "973",
    cd_ref: "971",
    lb_nom: "Colymbus auritus",
    nom_vern: "Grèbe esclavon",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380267",
    cd_ref: "971",
    lb_nom: "Podicipes auritus",
    nom_vern: "Grèbe esclavon",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "965",
    cd_ref: "965",
    lb_nom: "Podiceps cristatus",
    nom_vern: "Grèbe huppé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "967",
    cd_ref: "965",
    lb_nom: "Colymbus cristatus",
    nom_vern: "Grèbe huppé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380268",
    cd_ref: "965",
    lb_nom: "Podicipes cristatus",
    nom_vern: "Grèbe huppé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "968",
    cd_ref: "968",
    lb_nom: "Podiceps grisegena",
    nom_vern: "Grèbe jougris",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "970",
    cd_ref: "968",
    lb_nom: "Colymbus grisegena",
    nom_vern: "Grèbe jougris",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380269",
    cd_ref: "968",
    lb_nom: "Podicipes grisegena",
    nom_vern: "Grèbe jougris",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "974",
    cd_ref: "974",
    lb_nom: "Podiceps nigricollis",
    nom_vern: "Grèbe à cou noir",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380266",
    cd_ref: "974",
    lb_nom: "Podicipes nigricollis",
    nom_vern: "Grèbe à cou noir",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "982",
    cd_ref: "982",
    lb_nom: "Podilymbus podiceps",
    nom_vern: "Grèbe à bec bigarré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "814135",
    cd_ref: "982",
    lb_nom: "Colymbus podiceps",
    nom_vern: "Grèbe à bec bigarré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "977",
    cd_ref: "977",
    lb_nom: "Tachybaptus ruficollis",
    nom_vern: "Grèbe castagneux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "979",
    cd_ref: "977",
    lb_nom: "Colymbus ruficollis",
    nom_vern: "Grèbe castagneux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "980",
    cd_ref: "977",
    lb_nom: "Podiceps ruficollis",
    nom_vern: "Grèbe castagneux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2419",
    cd_ref: "2419",
    lb_nom: "Hydrobates pelagicus",
    nom_vern: "Océanite tempête, Pétrel tempête",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2421",
    cd_ref: "2419",
    lb_nom: "Procellaria pelagica",
    nom_vern: "Océanite tempête, Pétrel tempête",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1005",
    cd_ref: "1005",
    lb_nom: "Bulweria bulwerii",
    nom_vern: "Pétrel de Bulwer",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1007",
    cd_ref: "1005",
    lb_nom: "Procellaria bulwerii",
    nom_vern: "Pétrel de Bulwer",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "929600",
    cd_ref: "1005",
    lb_nom: "Thalassidroma bulwerii",
    nom_vern: "Pétrel de Bulwer",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "886117",
    cd_ref: "886117",
    lb_nom: "Calonectris borealis",
    nom_vern: "Puffin cendré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1014",
    cd_ref: "886117",
    lb_nom: "Calonectris diomedea borealis",
    nom_vern: "Puffin cendré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "886120",
    cd_ref: "886117",
    lb_nom: "Puffinus borealis",
    nom_vern: "Puffin cendré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1009",
    cd_ref: "1009",
    lb_nom: "Calonectris diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1015",
    cd_ref: "1009",
    lb_nom: "Calonectris diomedea diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1011",
    cd_ref: "1009",
    lb_nom: "Procellaria diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961387",
    cd_ref: "1009",
    lb_nom: "Procellaria kuhlii",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1013",
    cd_ref: "1009",
    lb_nom: "Puffinus diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1012",
    cd_ref: "1009",
    lb_nom: "Puffinus kuhli",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "994",
    cd_ref: "994",
    lb_nom: "Macronectes giganteus",
    nom_vern: "Fulmar géant, Fulmar de Hall, Pétrel géant",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "996",
    cd_ref: "994",
    lb_nom: "Procellaria gigantea",
    nom_vern: "Fulmar géant, Fulmar de Hall, Pétrel géant",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1027",
    cd_ref: "1027",
    lb_nom: "Puffinus puffinus",
    nom_vern: "Puffin des Anglais",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1029",
    cd_ref: "1027",
    lb_nom: "Procellaria puffinus",
    nom_vern: "Puffin des Anglais",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1030",
    cd_ref: "1027",
    lb_nom: "Puffinus puffinus puffinus",
    nom_vern: "Puffin des Anglais",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1031",
    cd_ref: "1031",
    lb_nom: "Puffinus yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961093",
    cd_ref: "1031",
    lb_nom: "Procellaria yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1033",
    cd_ref: "1031",
    lb_nom: "Puffinus puffinus yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1034",
    cd_ref: "1031",
    lb_nom: "Puffinus yelkouan yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "189374",
    cd_ref: "189374",
    lb_nom: "Ara",
    nom_vern: "",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "195598",
    cd_ref: "195598",
    lb_nom: "Otus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "66459",
    cd_ref: "66459",
    lb_nom: "Carcharhinus falciformis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564788",
    cd_ref: "66459",
    lb_nom: "Aprionodon sitankaiensis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555565",
    cd_ref: "66459",
    lb_nom: "Carcharhinus atrodorsus",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581850",
    cd_ref: "66459",
    lb_nom: "Carcharhinus falciformes",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66461",
    cd_ref: "66459",
    lb_nom: "Carcharhinus floridanus",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "551202",
    cd_ref: "66459",
    lb_nom: "Carcharhinus floridianus",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "577750",
    cd_ref: "66459",
    lb_nom: "Carcharhinus menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555783",
    cd_ref: "66459",
    lb_nom: "Carcharias falciformis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555784",
    cd_ref: "66459",
    lb_nom: "Carcharias falcipinnis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555862",
    cd_ref: "66459",
    lb_nom: "Carcharias menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581851",
    cd_ref: "66459",
    lb_nom: "Carcharins menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581852",
    cd_ref: "66459",
    lb_nom: "Carcharius menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "562907",
    cd_ref: "66459",
    lb_nom: "Eulamia malpeloensis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "562908",
    cd_ref: "66459",
    lb_nom: "Eulamia menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563781",
    cd_ref: "66459",
    lb_nom: "Gymnorhinus pharaonis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "565552",
    cd_ref: "66459",
    lb_nom: "Prionodon tiburo",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554884",
    cd_ref: "66459",
    lb_nom: "Squalus tiburo",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66465",
    cd_ref: "66465",
    lb_nom: "Carcharhinus leucas",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555566",
    cd_ref: "66465",
    lb_nom: "Carcharhinus azureus",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66467",
    cd_ref: "66465",
    lb_nom: "Carcharhinus nicaraguensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66469",
    cd_ref: "66465",
    lb_nom: "Carcharhinus vanrooyeni",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66468",
    cd_ref: "66465",
    lb_nom: "Carcharhinus zambezensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555772",
    cd_ref: "66465",
    lb_nom: "Carcharias azureus",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555802",
    cd_ref: "66465",
    lb_nom: "Carcharias leucas",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555882",
    cd_ref: "66465",
    lb_nom: "Carcharias spenceri",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555893",
    cd_ref: "66465",
    lb_nom: "Carcharias zambezensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "562909",
    cd_ref: "66465",
    lb_nom: "Eulamia nicaraguensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563464",
    cd_ref: "66465",
    lb_nom: "Galeolamna bogimba",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "566383",
    cd_ref: "66465",
    lb_nom: "Galeolamna greyi mckaili",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581854",
    cd_ref: "66465",
    lb_nom: "Galeolamna leucas",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563471",
    cd_ref: "66465",
    lb_nom: "Galeolamna mckaili",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "565551",
    cd_ref: "66465",
    lb_nom: "Prionodon platyodon",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554817",
    cd_ref: "66465",
    lb_nom: "Squalus obtusus",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554823",
    cd_ref: "66465",
    lb_nom: "Squalus platyodon",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66371",
    cd_ref: "66371",
    lb_nom: "Heptranchias perlo",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555675",
    cd_ref: "66371",
    lb_nom: "Heptranchias angio",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555677",
    cd_ref: "66371",
    lb_nom: "Heptranchias cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555678",
    cd_ref: "66371",
    lb_nom: "Heptranchias dakini",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555679",
    cd_ref: "66371",
    lb_nom: "Heptranchias deani",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564111",
    cd_ref: "66371",
    lb_nom: "Heptrancus angio",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66373",
    cd_ref: "66371",
    lb_nom: "Heptrianchias cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66374",
    cd_ref: "66371",
    lb_nom: "Heptrianchias deani",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "566363",
    cd_ref: "66371",
    lb_nom: "Notidanus cinereus aetatis",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "566364",
    cd_ref: "66371",
    lb_nom: "Notidanus cinereus pristiurus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563797",
    cd_ref: "66371",
    lb_nom: "Notidanus cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554782",
    cd_ref: "66371",
    lb_nom: "Squalus cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554821",
    cd_ref: "66371",
    lb_nom: "Squalus perlo",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66376",
    cd_ref: "66376",
    lb_nom: "Hexanchus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555683",
    cd_ref: "66376",
    lb_nom: "Hexanchus corinum",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555684",
    cd_ref: "66376",
    lb_nom: "Hexanchus corinus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564060",
    cd_ref: "66376",
    lb_nom: "Hexanchus griseus australis",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564891",
    cd_ref: "66376",
    lb_nom: "Monopterhinus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581794",
    cd_ref: "66376",
    lb_nom: "Monopterinus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66378",
    cd_ref: "66376",
    lb_nom: "Notidanus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563801",
    cd_ref: "66376",
    lb_nom: "Notidanus monge",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66379",
    cd_ref: "66376",
    lb_nom: "Notidanus vulgaris",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "546241",
    cd_ref: "66376",
    lb_nom: "Squalus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554888",
    cd_ref: "66376",
    lb_nom: "Squalus vacca",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66382",
    cd_ref: "66382",
    lb_nom: "Hexanchus nakamurai",
    nom_vern: "Requin vache",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564061",
    cd_ref: "66382",
    lb_nom: "Hexanchus griseus nakamurai",
    nom_vern: "Requin vache",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66380",
    cd_ref: "66382",
    lb_nom: "Hexanchus vitulus",
    nom_vern: "Requin vache",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66391",
    cd_ref: "66391",
    lb_nom: "Odontaspis ferox",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66394",
    cd_ref: "66391",
    lb_nom: "Carcharias ferox",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66393",
    cd_ref: "66391",
    lb_nom: "Odontaspis herbsti",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554794",
    cd_ref: "66391",
    lb_nom: "Squalus ferox",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66395",
    cd_ref: "66395",
    lb_nom: "Odontaspis noronhai",
    nom_vern: "Requin noronhai",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66397",
    cd_ref: "66395",
    lb_nom: "Carcharias noronhai",
    nom_vern: "Requin noronhai",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "186194",
    cd_ref: "186194",
    lb_nom: "Myliobatidae",
    nom_vern: "Raies",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "60674",
    cd_ref: "60674",
    lb_nom: "Martes foina",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60683",
    cd_ref: "60674",
    lb_nom: "Martes foina bunites",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60677",
    cd_ref: "60674",
    lb_nom: "Martes foina foina",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60684",
    cd_ref: "60674",
    lb_nom: "Martes foina milleri",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60678",
    cd_ref: "60674",
    lb_nom: "Mustela alba",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60679",
    cd_ref: "60674",
    lb_nom: "Mustela bosniaca",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60680",
    cd_ref: "60674",
    lb_nom: "Mustela domestica",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60676",
    cd_ref: "60674",
    lb_nom: "Mustela foina",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60681",
    cd_ref: "60674",
    lb_nom: "Mustela mediterranea",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60682",
    cd_ref: "60674",
    lb_nom: "Mustela mehringi",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60658",
    cd_ref: "60658",
    lb_nom: "Martes martes",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60664",
    cd_ref: "60658",
    lb_nom: "Martes abietum",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60665",
    cd_ref: "60658",
    lb_nom: "Martes latinorum",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60670",
    cd_ref: "60658",
    lb_nom: "Martes martes lorenzi",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60661",
    cd_ref: "60658",
    lb_nom: "Martes martes martes",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60669",
    cd_ref: "60658",
    lb_nom: "Martes martes sabaneevi",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60668",
    cd_ref: "60658",
    lb_nom: "Martes martes uralensis",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60666",
    cd_ref: "60658",
    lb_nom: "Martes notialis",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60667",
    cd_ref: "60658",
    lb_nom: "Martes ruthena",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60662",
    cd_ref: "60658",
    lb_nom: "Martes sylvestris",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60663",
    cd_ref: "60658",
    lb_nom: "Martes vulgaris",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60660",
    cd_ref: "60658",
    lb_nom: "Mustela martes",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60686",
    cd_ref: "60686",
    lb_nom: "Mustela erminea",
    nom_vern: "Hermine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60716",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60722",
    cd_ref: "60716",
    lb_nom: "Mustela alpinus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60728",
    cd_ref: "60716",
    lb_nom: "Mustela boccamela",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60730",
    cd_ref: "60716",
    lb_nom: "Mustela corsicana",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60723",
    cd_ref: "60716",
    lb_nom: "Mustela ibericus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60724",
    cd_ref: "60716",
    lb_nom: "Mustela italicus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60725",
    cd_ref: "60716",
    lb_nom: "Mustela meridionalis",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60720",
    cd_ref: "60716",
    lb_nom: "Mustela minor",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60726",
    cd_ref: "60716",
    lb_nom: "Mustela minutus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60727",
    cd_ref: "60716",
    lb_nom: "Mustela monticola",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "899271",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis boccamela",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60718",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis corsicana",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60719",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis nivalis",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "200109",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis vulgaris",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60721",
    cd_ref: "60716",
    lb_nom: "Mustela typicus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60729",
    cd_ref: "60716",
    lb_nom: "Mustela vulgaris",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60731",
    cd_ref: "60731",
    lb_nom: "Mustela putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60737",
    cd_ref: "60731",
    lb_nom: "Mustela albus",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60738",
    cd_ref: "60731",
    lb_nom: "Mustela anglia",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60739",
    cd_ref: "60731",
    lb_nom: "Mustela aureola",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60740",
    cd_ref: "60731",
    lb_nom: "Mustela caledoniae",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60733",
    cd_ref: "60731",
    lb_nom: "Mustela foetens",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60741",
    cd_ref: "60731",
    lb_nom: "Mustela furo-putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60735",
    cd_ref: "60731",
    lb_nom: "Mustela iltis",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60734",
    cd_ref: "60731",
    lb_nom: "Mustela infectus",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60743",
    cd_ref: "60731",
    lb_nom: "Mustela orientalis",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "200111",
    cd_ref: "60731",
    lb_nom: "Mustela putorius putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60744",
    cd_ref: "60731",
    lb_nom: "Mustela rotschildi",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60745",
    cd_ref: "60731",
    lb_nom: "Mustela stantschinskii",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60742",
    cd_ref: "60731",
    lb_nom: "Putorius putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "535463",
    cd_ref: "535463",
    lb_nom: "Hydrurga leptonyx",
    nom_vern: "Léopard de mer",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186209",
    cd_ref: "186209",
    lb_nom: "Bovidae",
    nom_vern: "Bisons, Boeufs",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186233",
    cd_ref: "186233",
    lb_nom: "Chiroptera",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186236",
    cd_ref: "186233",
    lb_nom: "Microchiroptera",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "192256",
    cd_ref: "192256",
    lb_nom: "Eptesicus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "195005",
    cd_ref: "195005",
    lb_nom: "Myotis",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186259",
    cd_ref: "186259",
    lb_nom: "Muridae",
    nom_vern: "Souris, Campagnols, Mulots, Rats",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "194935",
    cd_ref: "194935",
    lb_nom: "Mus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "7466",
    cd_ref: "7466",
    lb_nom: "Epizoanthus arenaceus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Anthozoa",
  },
  {
    cd_nom: "386316",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "371739",
    cd_ref: "386316",
    lb_nom: "Fistularia impatiens",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "359560",
    cd_ref: "386316",
    lb_nom: "Holothuria botellus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "569419",
    cd_ref: "386316",
    lb_nom: "Holothuria fulva",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "386334",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens bicolor",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "386335",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens concolor",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "386336",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens lutea",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "386337",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens pulchra",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "569433",
    cd_ref: "386316",
    lb_nom: "Holothuria ophidiana",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "445442",
    cd_ref: "445442",
    lb_nom: "Bidens aoraiensis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "445456",
    cd_ref: "445456",
    lb_nom: "Bidens orofenensis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "452570",
    cd_ref: "445456",
    lb_nom: "Bidens societatis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "103626",
    cd_ref: "103626",
    lb_nom: "Inula helenioides",
    nom_vern: "Inule faux hélénium, Inule fausse aunée, Inule fausse hélénie",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "100868",
    cd_ref: "103626",
    lb_nom: "Helenium helenioides",
    nom_vern: "Inule faux hélénium, Inule fausse aunée, Inule fausse hélénie",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "445484",
    cd_ref: "445484",
    lb_nom: "Senecio stokesii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "706492",
    cd_ref: "706492",
    lb_nom: "Lobelia parva",
    nom_vern: "Lobélie petite",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "3885",
    cd_ref: "3885",
    lb_nom: "Buxbaumia viridis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "3886",
    cd_ref: "3885",
    lb_nom: "Buxbaumia indusiata",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125935",
    cd_ref: "125935",
    lb_nom: "Tetragonia tetragonoides",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94608",
    cd_ref: "125935",
    lb_nom: "Demidovia tetragonoides",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "614189",
    cd_ref: "125935",
    lb_nom: "Tetragonia cornuta",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125931",
    cd_ref: "125935",
    lb_nom: "Tetragonia cornuta",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "830414",
    cd_ref: "125935",
    lb_nom: "Tetragonia expansa var. cornuta",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125932",
    cd_ref: "125935",
    lb_nom: "Tetragonia expansa",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125933",
    cd_ref: "125935",
    lb_nom: "Tetragonia halimifolia",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125934",
    cd_ref: "125935",
    lb_nom: "Tetragonia japonica",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "445376",
    cd_ref: "125935",
    lb_nom: "Tetragonia tetragonioides",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4797",
    cd_ref: "4797",
    lb_nom: "Bruchia vogesiaca",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4763",
    cd_ref: "4763",
    lb_nom: "Dicranum viride",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "787543",
    cd_ref: "4763",
    lb_nom: "Paraleucobryum viride",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1078416",
    cd_ref: "4763",
    lb_nom: "Campylopus viridis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4387",
    cd_ref: "4387",
    lb_nom: "Fissidens monguillonii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4388",
    cd_ref: "4388",
    lb_nom: "Fissidens osmundoides",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4393",
    cd_ref: "4393",
    lb_nom: "Fissidens rivularis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079557",
    cd_ref: "4393",
    lb_nom: "Fissidens bryoides var. rivularis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4770",
    cd_ref: "4770",
    lb_nom: "Leucobryum glaucum",
    nom_vern: "Coussinet des bois",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "787683",
    cd_ref: "4770",
    lb_nom: "Dicranum glaucum",
    nom_vern: "Coussinet des bois",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "3912",
    cd_ref: "3912",
    lb_nom: "Crossidium aberrans",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106678",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "137436",
    cd_ref: "106678",
    lb_nom: "Lotus angustissimus subsp. hispidus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "137437",
    cd_ref: "106678",
    lb_nom: "Lotus angustissimus subsp. suaveolens",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106635",
    cd_ref: "106678",
    lb_nom: "Lotus approximatus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106663",
    cd_ref: "106678",
    lb_nom: "Lotus divaricatus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106669",
    cd_ref: "106678",
    lb_nom: "Lotus fallax",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "148432",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus var. filiformis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "148433",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus var. littoralis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "148434",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus var. major",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106681",
    cd_ref: "106678",
    lb_nom: "Lotus levieri",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106690",
    cd_ref: "106678",
    lb_nom: "Lotus odoratus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "619879",
    cd_ref: "106678",
    lb_nom: "Lotus pilosissimus var. filiformis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106699",
    cd_ref: "106678",
    lb_nom: "Lotus pilosissimus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106714",
    cd_ref: "106678",
    lb_nom: "Lotus stagnalis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106715",
    cd_ref: "106678",
    lb_nom: "Lotus suaveolens",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106716",
    cd_ref: "106678",
    lb_nom: "Lotus subbiflorus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "5036",
    cd_ref: "5036",
    lb_nom: "Orthotrichum rogeri",
    nom_vern: "Orthotric de Roger",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "788338",
    cd_ref: "5036",
    lb_nom: "Orthotrichum rogeri var. rogeri",
    nom_vern: "Orthotric de Roger",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "88792",
    cd_ref: "88792",
    lb_nom: "Carex pseudobrizoides",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "152907",
    cd_ref: "88792",
    lb_nom: "Carex brizoides proles clavaudiana",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "88733",
    cd_ref: "88792",
    lb_nom: "Carex ohmuelleriana",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "619024",
    cd_ref: "88792",
    lb_nom: "Carex pseudoarenaria",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "88818",
    cd_ref: "88792",
    lb_nom: "Carex reichenbachii",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "84476",
    cd_ref: "84476",
    lb_nom: "Asplenium cuneifolium",
    nom_vern:
      "Doradille cunéiforme, Doradille à feuilles en coin, Doradille à feuilles cunéiformes",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "131805",
    cd_ref: "84476",
    lb_nom: "Asplenium adiantum-nigrum subsp. cuneifolium",
    nom_vern:
      "Doradille cunéiforme, Doradille à feuilles en coin, Doradille à feuilles cunéiformes",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1050383",
    cd_ref: "84476",
    lb_nom: "Asplenium adiantum-nigrum var. cuneifolium",
    nom_vern:
      "Doradille cunéiforme, Doradille à feuilles en coin, Doradille à feuilles cunéiformes",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "133619",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis subsp. diaphana",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "84446",
    cd_ref: "133619",
    lb_nom: "Aspidium viridulum",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "84479",
    cd_ref: "133619",
    lb_nom: "Asplenium diaphanum",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94057",
    cd_ref: "133619",
    lb_nom: "Cystopteris atrovirens",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94060",
    cd_ref: "133619",
    lb_nom: "Cystopteris canariensis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94062",
    cd_ref: "133619",
    lb_nom: "Cystopteris diaphana",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "153042",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis proles viridula",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "133617",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis subsp. canariensis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1038639",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis subsp. canariensis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "785069",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94073",
    cd_ref: "133619",
    lb_nom: "Cystopteris viridula",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "114953",
    cd_ref: "133619",
    lb_nom: "Polypodium diaphanum",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079427",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora subsp. anthora",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142548",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. atrovirens",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142549",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. confertiflorum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142550",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. eulophum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079434",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. glabriflorum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142551",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. grandiflorum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142552",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. inclinatum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142553",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. jacquinianum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142555",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. jacquinii",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142554",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. jacquinii",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142556",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. patulum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079432",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthoroideum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079431",
    cd_ref: "1079427",
    lb_nom: "Aconitum decandollei",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80020",
    cd_ref: "1079427",
    lb_nom: "Aconitum eulophum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80027",
    cd_ref: "1079427",
    lb_nom: "Aconitum jacquinii",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80040",
    cd_ref: "1079427",
    lb_nom: "Aconitum nemorosum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80052",
    cd_ref: "1079427",
    lb_nom: "Aconitum pseudanthora",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80014",
    cd_ref: "80014",
    lb_nom: "Aconitum corsicum",
    nom_vern: "Aconit de Corse",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "130784",
    cd_ref: "80014",
    lb_nom: "Aconitum napellus subsp. corsicum",
    nom_vern: "Aconit de Corse",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142566",
    cd_ref: "80014",
    lb_nom: "Aconitum pyramidale var. corsicum",
    nom_vern: "Aconit de Corse",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6720",
    cd_ref: "6720",
    lb_nom: "Sphagnum affine",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "788386",
    cd_ref: "6720",
    lb_nom: "Sphagnum affine var. affine",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435494",
    cd_ref: "6720",
    lb_nom: "Sphagnum affine var. flagellare",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435495",
    cd_ref: "6720",
    lb_nom: "Sphagnum imbricatum subsp. affine",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "786824",
    cd_ref: "6720",
    lb_nom: "Sphagnum imbricatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6722",
    cd_ref: "6722",
    lb_nom: "Sphagnum angustifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "787676",
    cd_ref: "6722",
    lb_nom: "Sphagnum parvifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435498",
    cd_ref: "6722",
    lb_nom: "Sphagnum recurvum var. tenue",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6724",
    cd_ref: "6724",
    lb_nom: "Sphagnum austinii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435496",
    cd_ref: "6724",
    lb_nom: "Sphagnum imbricatum subsp. austinii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6725",
    cd_ref: "6725",
    lb_nom: "Sphagnum balticum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6736",
    cd_ref: "6736",
    lb_nom: "Sphagnum contortum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6737",
    cd_ref: "6736",
    lb_nom: "Sphagnum laricinum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435504",
    cd_ref: "6736",
    lb_nom: "Sphagnum subsecundum var. contortum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6746",
    cd_ref: "6746",
    lb_nom: "Sphagnum fallax",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "786823",
    cd_ref: "6746",
    lb_nom: "Sphagnum apiculatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435500",
    cd_ref: "6746",
    lb_nom: "Sphagnum brevifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "788204",
    cd_ref: "6746",
    lb_nom: "Sphagnum fallax subsp. fallax",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435501",
    cd_ref: "6746",
    lb_nom: "Sphagnum fallax subsp. isoviitae",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435502",
    cd_ref: "6746",
    lb_nom: "Sphagnum isoviitae",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "701795",
    cd_ref: "6746",
    lb_nom: "Sphagnum recurvum subsp. mucronatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435503",
    cd_ref: "6746",
    lb_nom: "Sphagnum recurvum var. brevifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "701794",
    cd_ref: "6746",
    lb_nom: "Sphagnum recurvum var. mucronatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4964",
    cd_ref: "4964",
    lb_nom: "Meesia longiseta",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "786732",
    cd_ref: "4964",
    lb_nom: "Diplocomium longisetum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  // Non-protected taxa: present in TAXREF but absent from BDC-Statuts
  {
    cd_nom: "4503",
    cd_ref: "4503",
    lb_nom: "Corvus corone",
    nom_vern: "Corneille noire",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "60585",
    cd_ref: "60585",
    lb_nom: "Vulpes vulpes",
    nom_vern: "Renard roux, Renard, Goupil",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "61057",
    cd_ref: "61057",
    lb_nom: "Capreolus capreolus",
    nom_vern: "Chevreuil européen, Chevreuil, Brocard (mâle), Chevrette (femelle)",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "119097",
    cd_ref: "119097",
    lb_nom: "Rubus fruticosus",
    nom_vern: "Ronce ligneuse, Ronce de Bertram, Ronce commune",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];

export async function seed(knex: Knex) {
  await knex("espece_taxref").truncate();
  await knex.batchInsert("espece_taxref", TAXREF, 1000);

  console.log(`  Seed espece_taxref OK (${TAXREF.length} lignes)`);
}
