import type { Knex } from "knex";

import type { EspeceBdcStatutInitializer } from "@pitchou/types/database/public/EspeceBdcStatut.ts";

const PN_DOCUMENT = {
  label_statut:
    "Liste des oiseaux protégés sur l'ensemble du territoire et les modalités de leur protection : Article 3",
  cd_doc: "713",
  full_citation:
    "Arrêté interministériel du 29 octobre 2009 fixant la liste des oiseaux protégés sur l’ensemble du territoire et les modalités de leur protection (JORF 5 décembre 2009, p. 21056)",
  doc_url: "http://legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000021384277",
};

const PR_DOCUMENT = {
  label_statut: "Liste des espèces végétales protégées en région Île-de-France : Article 1",
  cd_doc: "735",
  full_citation:
    "Arrêté interministériel du 11 mars 1991 relatif à la liste des espèces végétales protégées en région Île-de-France complétant la liste nationale",
  doc_url: "https://www.legifrance.gouv.fr/loda/id/LEGITEXT000006059591/",
};

const BDC_STATUT: EspeceBdcStatutInitializer[] = [
  { cd_nom: "100", cd_ref: "100", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1005", cd_ref: "1005", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1005", cd_ref: "1005", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1009", cd_ref: "1009", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1009", cd_ref: "1009", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1009", cd_ref: "1009", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "1027", cd_ref: "1027", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1027", cd_ref: "1027", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1027", cd_ref: "1027", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "1031", cd_ref: "1031", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "103626", cd_ref: "103626", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1079427", cd_ref: "1079427", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1079427", cd_ref: "1079427", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "125935", cd_ref: "125935", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "133619", cd_ref: "133619", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "133619", cd_ref: "133619", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "133619", cd_ref: "133619", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "139", cd_ref: "139", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1948", cd_ref: "1948", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1948", cd_ref: "1948", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1955", cd_ref: "1955", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1955", cd_ref: "1955", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "1958", cd_ref: "1958", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1960", cd_ref: "1960", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1972", cd_ref: "1972", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1973", cd_ref: "1973", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1988", cd_ref: "1988", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "1988", cd_ref: "1988", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "199352", cd_ref: "199352", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "199357", cd_ref: "199357", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "199363", cd_ref: "199363", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "212", cd_ref: "212", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "240", cd_ref: "240", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2419", cd_ref: "2419", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2473", cd_ref: "2473", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2477", cd_ref: "2477", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2514", cd_ref: "2514", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2557", cd_ref: "2557", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "2557", cd_ref: "2557", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2571", cd_ref: "2571", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "2571", cd_ref: "2571", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2645", cd_ref: "2645", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2645", cd_ref: "2645", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "2657", cd_ref: "2657", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2660", cd_ref: "2660", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "2660", cd_ref: "2660", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2660", cd_ref: "2660", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "2666", cd_ref: "2666", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2709", cd_ref: "2709", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2709", cd_ref: "2709", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "2826", cd_ref: "2826", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2852", cd_ref: "2852", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "2869", cd_ref: "2869", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "292", cd_ref: "292", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "299", cd_ref: "299", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "3053", cd_ref: "3053", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "3053", cd_ref: "3053", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "3089", cd_ref: "3089", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "3420", cd_ref: "3420", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "386316", cd_ref: "386316", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "3885", cd_ref: "3885", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "3912", cd_ref: "3912", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "416999", cd_ref: "416999", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "417000", cd_ref: "417000", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "432596", cd_ref: "432596", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "4387", cd_ref: "4387", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "4388", cd_ref: "4388", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "4393", cd_ref: "4393", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "445442", cd_ref: "445442", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "445456", cd_ref: "445456", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "445484", cd_ref: "445484", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "4763", cd_ref: "4763", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "4770", cd_ref: "4770", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "4797", cd_ref: "4797", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "4797", cd_ref: "4797", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "4964", cd_ref: "4964", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "5036", cd_ref: "5036", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "535463", cd_ref: "535463", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "59", cd_ref: "59", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "66371", cd_ref: "66371", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "66376", cd_ref: "66376", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "66376", cd_ref: "66376", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "66382", cd_ref: "66382", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "66391", cd_ref: "66391", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "66395", cd_ref: "66395", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "66459", cd_ref: "66459", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "66459", cd_ref: "66459", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "66465", cd_ref: "66465", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "66465", cd_ref: "66465", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "6720", cd_ref: "6720", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "6722", cd_ref: "6722", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "6722", cd_ref: "6722", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "6724", cd_ref: "6724", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "6725", cd_ref: "6725", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "6736", cd_ref: "6736", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "6736", cd_ref: "6736", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "6746", cd_ref: "6746", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "6746", cd_ref: "6746", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "706492", cd_ref: "706492", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "7466", cd_ref: "7466", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "80014", cd_ref: "80014", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "80014", cd_ref: "80014", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "80014", cd_ref: "80014", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "8332", cd_ref: "8332", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "84476", cd_ref: "84476", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "84476", cd_ref: "84476", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "86", cd_ref: "86", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "88792", cd_ref: "88792", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "88792", cd_ref: "88792", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "9074", cd_ref: "9074", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "92", cd_ref: "92", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "9266", cd_ref: "9266", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "9370", cd_ref: "9370", cd_type_statut: "PR", label_statut: "" },
  { cd_nom: "953", cd_ref: "953", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "956", cd_ref: "956", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "959", cd_ref: "959", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "959", cd_ref: "959", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "965", cd_ref: "965", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "968", cd_ref: "968", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "968", cd_ref: "968", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "971", cd_ref: "971", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "971", cd_ref: "971", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "974", cd_ref: "974", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "977", cd_ref: "977", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "977", cd_ref: "977", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "982", cd_ref: "982", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "982", cd_ref: "982", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "982", cd_ref: "982", cd_type_statut: "POM", label_statut: "" },
  { cd_nom: "994", cd_ref: "994", cd_type_statut: "PD", label_statut: "" },
  { cd_nom: "994", cd_ref: "994", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "994", cd_ref: "994", cd_type_statut: "POM", label_statut: "" },
  // Species used by the seed dossiers D10 / D11.
  { cd_nom: "459478", cd_ref: "459478", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "4663", cd_ref: "4663", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "4669", cd_ref: "4669", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "4221", cd_ref: "4221", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "351", cd_ref: "351", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "77600", cd_ref: "77600", cd_type_statut: "PN", label_statut: "" },
  { cd_nom: "88560", cd_ref: "88560", cd_type_statut: "PN", label_statut: "" },
];

function enrichDocument(row: EspeceBdcStatutInitializer): EspeceBdcStatutInitializer {
  if (row.cd_type_statut === "PN") return { ...row, ...PN_DOCUMENT };
  if (row.cd_type_statut === "PR") return { ...row, ...PR_DOCUMENT };
  return row;
}

export async function seed(knex: Knex) {
  await knex("espece_bdc_statut").truncate();
  await knex.batchInsert("espece_bdc_statut", BDC_STATUT.map(enrichDocument), 1000);

  console.log(`  Seed espece_bdc_statut OK (${BDC_STATUT.length} lignes)`);
}
