export type DossierCorseRow = {
  Remarques: string;
  Département: string;
  Commune: string;
  "Nom du demandeur": string;
  "Type de projet": string;
  "Libellé Projet": string;
  "Service Pilote": string;
  "Espèces impactées": string;
  Raccourci: string;
  Statut: string;
  "Niveau d'avancement": string;
  "Date de début d'accompagnement": number;
  "Date de réception 1er dossier": string | number | Date;
  "Date de réception du dossier autoportant": string | Date;
  "N°ONAGRE": string;
  "Date de dépôt sur ONAGRE": string | Date;
  "Instructeur DREAL": string;
  Compétence: string;
  "Avis rendu": string;
  "Date avis": string;
  Contribution: string;
  "Commentaires phase instruction": string;
  "Début consultation": string;
  "Fin de publication": string;
  "Numéro AP": string;
  "Date AP": string | Date;
  "Commentaires post AP": string;
};
