import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_19: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "125933",
    cd_ref: "125935",
    lb_nom: "Tetragonia halimifolia",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125934",
    cd_ref: "125935",
    lb_nom: "Tetragonia japonica",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "445376",
    cd_ref: "125935",
    lb_nom: "Tetragonia tetragonioides",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4797",
    cd_ref: "4797",
    lb_nom: "Bruchia vogesiaca",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4763",
    cd_ref: "4763",
    lb_nom: "Dicranum viride",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "787543",
    cd_ref: "4763",
    lb_nom: "Paraleucobryum viride",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1078416",
    cd_ref: "4763",
    lb_nom: "Campylopus viridis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4387",
    cd_ref: "4387",
    lb_nom: "Fissidens monguillonii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4388",
    cd_ref: "4388",
    lb_nom: "Fissidens osmundoides",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4393",
    cd_ref: "4393",
    lb_nom: "Fissidens rivularis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079557",
    cd_ref: "4393",
    lb_nom: "Fissidens bryoides var. rivularis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4770",
    cd_ref: "4770",
    lb_nom: "Leucobryum glaucum",
    nom_vern: "Coussinet des bois",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "787683",
    cd_ref: "4770",
    lb_nom: "Dicranum glaucum",
    nom_vern: "Coussinet des bois",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "3912",
    cd_ref: "3912",
    lb_nom: "Crossidium aberrans",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106678",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "137436",
    cd_ref: "106678",
    lb_nom: "Lotus angustissimus subsp. hispidus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "137437",
    cd_ref: "106678",
    lb_nom: "Lotus angustissimus subsp. suaveolens",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106635",
    cd_ref: "106678",
    lb_nom: "Lotus approximatus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];
