import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_04: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "143",
    cd_ref: "139",
    lb_nom: "Salamandra lati-caudata",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "142",
    cd_ref: "139",
    lb_nom: "Salamandra platyura",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "141",
    cd_ref: "139",
    lb_nom: "Triton cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "147",
    cd_ref: "139",
    lb_nom: "Triton intermedius",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "146",
    cd_ref: "139",
    lb_nom: "Triton trouessarti",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "951901",
    cd_ref: "139",
    lb_nom: "Triturus cristatus cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "79256",
    cd_ref: "139",
    lb_nom: "Triturus (cristatus) cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1046385",
    cd_ref: "139",
    lb_nom: "Molge cristata",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "185961",
    cd_ref: "185961",
    lb_nom: "Aves",
    nom_vern: "Oiseaux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2869",
    cd_ref: "2869",
    lb_nom: "Aegypius monachus",
    nom_vern: "Vautour moine",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2871",
    cd_ref: "2869",
    lb_nom: "Vultur monachus",
    nom_vern: "Vautour moine",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2645",
    cd_ref: "2645",
    lb_nom: "Aquila chrysaetos",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "416681",
    cd_ref: "2645",
    lb_nom: "Aquila fulva",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2647",
    cd_ref: "2645",
    lb_nom: "Falco chrysaetos",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "846567",
    cd_ref: "2645",
    lb_nom: "Falco fulvus",
    nom_vern: "Aigle royal",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2657",
    cd_ref: "2657",
    lb_nom: "Aquila fasciata",
    nom_vern: "Aigle de Bonelli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2655",
    cd_ref: "2657",
    lb_nom: "Hieraaetus fasciatus",
    nom_vern: "Aigle de Bonelli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "432596",
    cd_ref: "432596",
    lb_nom: "Circus maillardi",
    nom_vern: "Busard de Maillard",
    regne: "Animalia",
    classe: "Aves",
  },
];
