import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_11: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "581851",
    cd_ref: "66459",
    lb_nom: "Carcharins menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581852",
    cd_ref: "66459",
    lb_nom: "Carcharius menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "562907",
    cd_ref: "66459",
    lb_nom: "Eulamia malpeloensis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "562908",
    cd_ref: "66459",
    lb_nom: "Eulamia menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563781",
    cd_ref: "66459",
    lb_nom: "Gymnorhinus pharaonis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "565552",
    cd_ref: "66459",
    lb_nom: "Prionodon tiburo",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554884",
    cd_ref: "66459",
    lb_nom: "Squalus tiburo",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66465",
    cd_ref: "66465",
    lb_nom: "Carcharhinus leucas",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555566",
    cd_ref: "66465",
    lb_nom: "Carcharhinus azureus",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66467",
    cd_ref: "66465",
    lb_nom: "Carcharhinus nicaraguensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66469",
    cd_ref: "66465",
    lb_nom: "Carcharhinus vanrooyeni",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66468",
    cd_ref: "66465",
    lb_nom: "Carcharhinus zambezensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555772",
    cd_ref: "66465",
    lb_nom: "Carcharias azureus",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555802",
    cd_ref: "66465",
    lb_nom: "Carcharias leucas",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555882",
    cd_ref: "66465",
    lb_nom: "Carcharias spenceri",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555893",
    cd_ref: "66465",
    lb_nom: "Carcharias zambezensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "562909",
    cd_ref: "66465",
    lb_nom: "Eulamia nicaraguensis",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563464",
    cd_ref: "66465",
    lb_nom: "Galeolamna bogimba",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
];
