import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_16: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "60727",
    cd_ref: "60716",
    lb_nom: "Mustela monticola",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "899271",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis boccamela",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60718",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis corsicana",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60719",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis nivalis",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "200109",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis vulgaris",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60721",
    cd_ref: "60716",
    lb_nom: "Mustela typicus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60729",
    cd_ref: "60716",
    lb_nom: "Mustela vulgaris",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60731",
    cd_ref: "60731",
    lb_nom: "Mustela putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60737",
    cd_ref: "60731",
    lb_nom: "Mustela albus",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60738",
    cd_ref: "60731",
    lb_nom: "Mustela anglia",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60739",
    cd_ref: "60731",
    lb_nom: "Mustela aureola",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60740",
    cd_ref: "60731",
    lb_nom: "Mustela caledoniae",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60733",
    cd_ref: "60731",
    lb_nom: "Mustela foetens",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60741",
    cd_ref: "60731",
    lb_nom: "Mustela furo-putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60735",
    cd_ref: "60731",
    lb_nom: "Mustela iltis",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60734",
    cd_ref: "60731",
    lb_nom: "Mustela infectus",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60743",
    cd_ref: "60731",
    lb_nom: "Mustela orientalis",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "200111",
    cd_ref: "60731",
    lb_nom: "Mustela putorius putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
];
