import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_01: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "8332",
    cd_ref: "8332",
    lb_nom: "Cicindela sylvatica",
    nom_vern: "Cicindèle à labre noir",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "251458",
    cd_ref: "8332",
    lb_nom: "Cicindela sylvatica sylvatica",
    nom_vern: "Cicindèle à labre noir",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9266",
    cd_ref: "9266",
    lb_nom: "Ophonus cordatus",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "798822",
    cd_ref: "9266",
    lb_nom: "Carabus cordatus",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "395528",
    cd_ref: "9266",
    lb_nom: "Carabus porosus",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "395529",
    cd_ref: "9266",
    lb_nom: "Harpalus iberiae",
    nom_vern: "Ophone cordiforme",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9370",
    cd_ref: "9370",
    lb_nom: "Oodes gracilis",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "808473",
    cd_ref: "9370",
    lb_nom: "Oodes gracilior",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "967142",
    cd_ref: "9370",
    lb_nom: "Oodes gracilior",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "967141",
    cd_ref: "9370",
    lb_nom: "Oodes similis",
    nom_vern: "Oode gracile",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9074",
    cd_ref: "9074",
    lb_nom: "Pterostichus aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "799002",
    cd_ref: "9074",
    lb_nom: "Carabus aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9077",
    cd_ref: "9074",
    lb_nom: "Omaseus aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "9075",
    cd_ref: "9074",
    lb_nom: "Pterostichus (Argutor) aterrimus",
    nom_vern: "Poecile fovéolé",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "417000",
    cd_ref: "417000",
    lb_nom: "Antanartia borbonica",
    nom_vern: "Vanesse de l’Obetie",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "812102",
    cd_ref: "417000",
    lb_nom: "Vanessa borbonica",
    nom_vern: "Vanesse de l’Obetie",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "985508",
    cd_ref: "417000",
    lb_nom: "Vanessa hippomene",
    nom_vern: "Vanesse de l’Obetie",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "416999",
    cd_ref: "416999",
    lb_nom: "Papilio phorbanta",
    nom_vern: "Papillon la Pâture",
    regne: "Animalia",
    classe: "Insecta",
  },
];
