import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_22: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "142549",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. confertiflorum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142550",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. eulophum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079434",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. glabriflorum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142551",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. grandiflorum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142552",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. inclinatum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142553",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. jacquinianum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142555",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. jacquinii",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142554",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. jacquinii",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142556",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. patulum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079432",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthoroideum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079431",
    cd_ref: "1079427",
    lb_nom: "Aconitum decandollei",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80020",
    cd_ref: "1079427",
    lb_nom: "Aconitum eulophum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80027",
    cd_ref: "1079427",
    lb_nom: "Aconitum jacquinii",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80040",
    cd_ref: "1079427",
    lb_nom: "Aconitum nemorosum",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80052",
    cd_ref: "1079427",
    lb_nom: "Aconitum pseudanthora",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "80014",
    cd_ref: "80014",
    lb_nom: "Aconitum corsicum",
    nom_vern: "Aconit de Corse",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "130784",
    cd_ref: "80014",
    lb_nom: "Aconitum napellus subsp. corsicum",
    nom_vern: "Aconit de Corse",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142566",
    cd_ref: "80014",
    lb_nom: "Aconitum pyramidale var. corsicum",
    nom_vern: "Aconit de Corse",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];
