import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_21: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "88818",
    cd_ref: "88792",
    lb_nom: "Carex reichenbachii",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "84476",
    cd_ref: "84476",
    lb_nom: "Asplenium cuneifolium",
    nom_vern:
      "Doradille cunéiforme, Doradille à feuilles en coin, Doradille à feuilles cunéiformes",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "131805",
    cd_ref: "84476",
    lb_nom: "Asplenium adiantum-nigrum subsp. cuneifolium",
    nom_vern:
      "Doradille cunéiforme, Doradille à feuilles en coin, Doradille à feuilles cunéiformes",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1050383",
    cd_ref: "84476",
    lb_nom: "Asplenium adiantum-nigrum var. cuneifolium",
    nom_vern:
      "Doradille cunéiforme, Doradille à feuilles en coin, Doradille à feuilles cunéiformes",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "133619",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis subsp. diaphana",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "84446",
    cd_ref: "133619",
    lb_nom: "Aspidium viridulum",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "84479",
    cd_ref: "133619",
    lb_nom: "Asplenium diaphanum",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94057",
    cd_ref: "133619",
    lb_nom: "Cystopteris atrovirens",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94060",
    cd_ref: "133619",
    lb_nom: "Cystopteris canariensis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94062",
    cd_ref: "133619",
    lb_nom: "Cystopteris diaphana",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "153042",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis proles viridula",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "133617",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis subsp. canariensis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1038639",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis subsp. canariensis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "785069",
    cd_ref: "133619",
    lb_nom: "Cystopteris fragilis",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94073",
    cd_ref: "133619",
    lb_nom: "Cystopteris viridula",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "114953",
    cd_ref: "133619",
    lb_nom: "Polypodium diaphanum",
    nom_vern: "Cystoptéride diaphane, Cystoptéris diaphane, Asplenium vert",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "1079427",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora subsp. anthora",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "142548",
    cd_ref: "1079427",
    lb_nom: "Aconitum anthora var. atrovirens",
    nom_vern: "Aconit anthore, Aconit anthora, Anthore, Maclou",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];
