import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_06: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "2712",
    cd_ref: "2709",
    lb_nom: "Olor columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2826",
    cd_ref: "2826",
    lb_nom: "Oxyura leucocephala",
    nom_vern: "Érismature à tête blanche",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2828",
    cd_ref: "2826",
    lb_nom: "Anas leucocephala",
    nom_vern: "Érismature à tête blanche",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "199352",
    cd_ref: "199352",
    lb_nom: "Calidris tenuirostris",
    nom_vern: "Bécasseau de l'Anadyr",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "927283",
    cd_ref: "199352",
    lb_nom: "Totanus tenuirostris",
    nom_vern: "Bécasseau de l'Anadyr",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "199363",
    cd_ref: "199363",
    lb_nom: "Heteroscelus brevipes",
    nom_vern: "Chevalier de Sibérie",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "814097",
    cd_ref: "199363",
    lb_nom: "Totanus brevipes",
    nom_vern: "Chevalier de Sibérie",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "442470",
    cd_ref: "199363",
    lb_nom: "Tringa brevipes",
    nom_vern: "Chevalier de Sibérie",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2557",
    cd_ref: "2557",
    lb_nom: "Limnodromus griseus",
    nom_vern: "Bécassin à bec court, Limnodrome à bec court, Bécassin roux, Grise à long bec",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "814241",
    cd_ref: "2557",
    lb_nom: "Scolopax grisea",
    nom_vern: "Bécassin à bec court, Limnodrome à bec court, Bécassin roux, Grise à long bec",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "199357",
    cd_ref: "199357",
    lb_nom: "Numenius minutus",
    nom_vern: "Courlis nain",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2571",
    cd_ref: "2571",
    lb_nom: "Numenius phaeopus",
    nom_vern: "Courlis corlieu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2573",
    cd_ref: "2571",
    lb_nom: "Scolopax phaeopus",
    nom_vern: "Courlis corlieu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3420",
    cd_ref: "3420",
    lb_nom: "Columba livia",
    nom_vern: "Pigeon biset",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3429",
    cd_ref: "3429",
    lb_nom: "Streptopelia decaocto",
    nom_vern: "Tourterelle turque",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3431",
    cd_ref: "3429",
    lb_nom: "Columba decaocto",
    nom_vern: "Tourterelle turque",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961155",
    cd_ref: "3429",
    lb_nom: "Columba risoria L. var. decaocto",
    nom_vern: "Tourterelle turque",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2666",
    cd_ref: "2666",
    lb_nom: "Falco naumanni",
    nom_vern: "Faucon crécerellette",
    regne: "Animalia",
    classe: "Aves",
  },
];
