import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_24: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "435501",
    cd_ref: "6746",
    lb_nom: "Sphagnum fallax subsp. isoviitae",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435502",
    cd_ref: "6746",
    lb_nom: "Sphagnum isoviitae",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "701795",
    cd_ref: "6746",
    lb_nom: "Sphagnum recurvum subsp. mucronatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435503",
    cd_ref: "6746",
    lb_nom: "Sphagnum recurvum var. brevifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "701794",
    cd_ref: "6746",
    lb_nom: "Sphagnum recurvum var. mucronatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "4964",
    cd_ref: "4964",
    lb_nom: "Meesia longiseta",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "786732",
    cd_ref: "4964",
    lb_nom: "Diplocomium longisetum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  // Non-protected taxa: present in TAXREF but absent from BDC-Statuts
  {
    cd_nom: "4503",
    cd_ref: "4503",
    lb_nom: "Corvus corone",
    nom_vern: "Corneille noire",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "60585",
    cd_ref: "60585",
    lb_nom: "Vulpes vulpes",
    nom_vern: "Renard roux, Renard, Goupil",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "61057",
    cd_ref: "61057",
    lb_nom: "Capreolus capreolus",
    nom_vern: "Chevreuil européen, Chevreuil, Brocard (mâle), Chevrette (femelle)",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "119097",
    cd_ref: "119097",
    lb_nom: "Rubus fruticosus",
    nom_vern: "Ronce ligneuse, Ronce de Bertram, Ronce commune",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  // Species used by the seed dossiers D10 / D11.
  {
    cd_nom: "459478",
    cd_ref: "459478",
    lb_nom: "Cecropis daurica",
    nom_vern: "Hirondelle rousseline",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "4663",
    cd_ref: "4663",
    lb_nom: "Emberiza bruniceps",
    nom_vern: "Bruant à tête rousse",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "4669",
    cd_ref: "4669",
    lb_nom: "Emberiza schoeniclus",
    nom_vern: "Bruant des roseaux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "4221",
    cd_ref: "4221",
    lb_nom: "Sylvia undata",
    nom_vern: "Fauvette pitchou",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "351",
    cd_ref: "351",
    lb_nom: "Rana temporaria",
    nom_vern: "Grenouille rousse (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "77600",
    cd_ref: "77600",
    lb_nom: "Natrix maura",
    nom_vern: "Couleuvre vipérine (La)",
    regne: "Animalia",
    classe: "Reptilia",
  },
  {
    cd_nom: "88560",
    cd_ref: "88560",
    lb_nom: "Brassica oleracea subsp. oleracea",
    nom_vern: "Chou commun",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];
