import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_10: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "1029",
    cd_ref: "1027",
    lb_nom: "Procellaria puffinus",
    nom_vern: "Puffin des Anglais",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1030",
    cd_ref: "1027",
    lb_nom: "Puffinus puffinus puffinus",
    nom_vern: "Puffin des Anglais",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1031",
    cd_ref: "1031",
    lb_nom: "Puffinus yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961093",
    cd_ref: "1031",
    lb_nom: "Procellaria yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1033",
    cd_ref: "1031",
    lb_nom: "Puffinus puffinus yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1034",
    cd_ref: "1031",
    lb_nom: "Puffinus yelkouan yelkouan",
    nom_vern: "Puffin yelkouan",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "189374",
    cd_ref: "189374",
    lb_nom: "Ara",
    nom_vern: "",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "195598",
    cd_ref: "195598",
    lb_nom: "Otus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "66459",
    cd_ref: "66459",
    lb_nom: "Carcharhinus falciformis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564788",
    cd_ref: "66459",
    lb_nom: "Aprionodon sitankaiensis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555565",
    cd_ref: "66459",
    lb_nom: "Carcharhinus atrodorsus",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581850",
    cd_ref: "66459",
    lb_nom: "Carcharhinus falciformes",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66461",
    cd_ref: "66459",
    lb_nom: "Carcharhinus floridanus",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "551202",
    cd_ref: "66459",
    lb_nom: "Carcharhinus floridianus",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "577750",
    cd_ref: "66459",
    lb_nom: "Carcharhinus menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555783",
    cd_ref: "66459",
    lb_nom: "Carcharias falciformis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555784",
    cd_ref: "66459",
    lb_nom: "Carcharias falcipinnis",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555862",
    cd_ref: "66459",
    lb_nom: "Carcharias menisorrah",
    nom_vern: "Requin soyeux",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
];
