import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_09: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "980",
    cd_ref: "977",
    lb_nom: "Podiceps ruficollis",
    nom_vern: "Grèbe castagneux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2419",
    cd_ref: "2419",
    lb_nom: "Hydrobates pelagicus",
    nom_vern: "Océanite tempête, Pétrel tempête",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2421",
    cd_ref: "2419",
    lb_nom: "Procellaria pelagica",
    nom_vern: "Océanite tempête, Pétrel tempête",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1005",
    cd_ref: "1005",
    lb_nom: "Bulweria bulwerii",
    nom_vern: "Pétrel de Bulwer",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1007",
    cd_ref: "1005",
    lb_nom: "Procellaria bulwerii",
    nom_vern: "Pétrel de Bulwer",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "929600",
    cd_ref: "1005",
    lb_nom: "Thalassidroma bulwerii",
    nom_vern: "Pétrel de Bulwer",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "886117",
    cd_ref: "886117",
    lb_nom: "Calonectris borealis",
    nom_vern: "Puffin cendré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1014",
    cd_ref: "886117",
    lb_nom: "Calonectris diomedea borealis",
    nom_vern: "Puffin cendré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "886120",
    cd_ref: "886117",
    lb_nom: "Puffinus borealis",
    nom_vern: "Puffin cendré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1009",
    cd_ref: "1009",
    lb_nom: "Calonectris diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1015",
    cd_ref: "1009",
    lb_nom: "Calonectris diomedea diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1011",
    cd_ref: "1009",
    lb_nom: "Procellaria diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961387",
    cd_ref: "1009",
    lb_nom: "Procellaria kuhlii",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1013",
    cd_ref: "1009",
    lb_nom: "Puffinus diomedea",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1012",
    cd_ref: "1009",
    lb_nom: "Puffinus kuhli",
    nom_vern: "Puffin de Scopoli",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "994",
    cd_ref: "994",
    lb_nom: "Macronectes giganteus",
    nom_vern: "Fulmar géant, Fulmar de Hall, Pétrel géant",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "996",
    cd_ref: "994",
    lb_nom: "Procellaria gigantea",
    nom_vern: "Fulmar géant, Fulmar de Hall, Pétrel géant",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1027",
    cd_ref: "1027",
    lb_nom: "Puffinus puffinus",
    nom_vern: "Puffin des Anglais",
    regne: "Animalia",
    classe: "Aves",
  },
];
