import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_14: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "554794",
    cd_ref: "66391",
    lb_nom: "Squalus ferox",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66395",
    cd_ref: "66395",
    lb_nom: "Odontaspis noronhai",
    nom_vern: "Requin noronhai",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66397",
    cd_ref: "66395",
    lb_nom: "Carcharias noronhai",
    nom_vern: "Requin noronhai",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "186194",
    cd_ref: "186194",
    lb_nom: "Myliobatidae",
    nom_vern: "Raies",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "60674",
    cd_ref: "60674",
    lb_nom: "Martes foina",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60683",
    cd_ref: "60674",
    lb_nom: "Martes foina bunites",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60677",
    cd_ref: "60674",
    lb_nom: "Martes foina foina",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60684",
    cd_ref: "60674",
    lb_nom: "Martes foina milleri",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60678",
    cd_ref: "60674",
    lb_nom: "Mustela alba",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60679",
    cd_ref: "60674",
    lb_nom: "Mustela bosniaca",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60680",
    cd_ref: "60674",
    lb_nom: "Mustela domestica",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60676",
    cd_ref: "60674",
    lb_nom: "Mustela foina",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60681",
    cd_ref: "60674",
    lb_nom: "Mustela mediterranea",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60682",
    cd_ref: "60674",
    lb_nom: "Mustela mehringi",
    nom_vern: "Fouine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60658",
    cd_ref: "60658",
    lb_nom: "Martes martes",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60664",
    cd_ref: "60658",
    lb_nom: "Martes abietum",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60665",
    cd_ref: "60658",
    lb_nom: "Martes latinorum",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60670",
    cd_ref: "60658",
    lb_nom: "Martes martes lorenzi",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
];
