import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_20: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "106663",
    cd_ref: "106678",
    lb_nom: "Lotus divaricatus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106669",
    cd_ref: "106678",
    lb_nom: "Lotus fallax",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "148432",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus var. filiformis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "148433",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus var. littoralis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "148434",
    cd_ref: "106678",
    lb_nom: "Lotus hispidus var. major",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106681",
    cd_ref: "106678",
    lb_nom: "Lotus levieri",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106690",
    cd_ref: "106678",
    lb_nom: "Lotus odoratus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "619879",
    cd_ref: "106678",
    lb_nom: "Lotus pilosissimus var. filiformis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106699",
    cd_ref: "106678",
    lb_nom: "Lotus pilosissimus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106714",
    cd_ref: "106678",
    lb_nom: "Lotus stagnalis",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106715",
    cd_ref: "106678",
    lb_nom: "Lotus suaveolens",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "106716",
    cd_ref: "106678",
    lb_nom: "Lotus subbiflorus",
    nom_vern: "Lotier hispide",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "5036",
    cd_ref: "5036",
    lb_nom: "Orthotrichum rogeri",
    nom_vern: "Orthotric de Roger",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "788338",
    cd_ref: "5036",
    lb_nom: "Orthotrichum rogeri var. rogeri",
    nom_vern: "Orthotric de Roger",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "88792",
    cd_ref: "88792",
    lb_nom: "Carex pseudobrizoides",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "152907",
    cd_ref: "88792",
    lb_nom: "Carex brizoides proles clavaudiana",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "88733",
    cd_ref: "88792",
    lb_nom: "Carex ohmuelleriana",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "619024",
    cd_ref: "88792",
    lb_nom: "Carex pseudoarenaria",
    nom_vern: "Laîche fausse brize",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];
