import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_15: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "60661",
    cd_ref: "60658",
    lb_nom: "Martes martes martes",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60669",
    cd_ref: "60658",
    lb_nom: "Martes martes sabaneevi",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60668",
    cd_ref: "60658",
    lb_nom: "Martes martes uralensis",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60666",
    cd_ref: "60658",
    lb_nom: "Martes notialis",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60667",
    cd_ref: "60658",
    lb_nom: "Martes ruthena",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60662",
    cd_ref: "60658",
    lb_nom: "Martes sylvestris",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60663",
    cd_ref: "60658",
    lb_nom: "Martes vulgaris",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60660",
    cd_ref: "60658",
    lb_nom: "Mustela martes",
    nom_vern: "Martre des pins, Martre",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60686",
    cd_ref: "60686",
    lb_nom: "Mustela erminea",
    nom_vern: "Hermine",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60716",
    cd_ref: "60716",
    lb_nom: "Mustela nivalis",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60722",
    cd_ref: "60716",
    lb_nom: "Mustela alpinus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60728",
    cd_ref: "60716",
    lb_nom: "Mustela boccamela",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60730",
    cd_ref: "60716",
    lb_nom: "Mustela corsicana",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60723",
    cd_ref: "60716",
    lb_nom: "Mustela ibericus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60724",
    cd_ref: "60716",
    lb_nom: "Mustela italicus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60725",
    cd_ref: "60716",
    lb_nom: "Mustela meridionalis",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60720",
    cd_ref: "60716",
    lb_nom: "Mustela minor",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60726",
    cd_ref: "60716",
    lb_nom: "Mustela minutus",
    nom_vern: "Belette d'Europe, Belette",
    regne: "Animalia",
    classe: "Mammalia",
  },
];
