import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_08: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "2479",
    cd_ref: "2477",
    lb_nom: "Ardea minuta",
    nom_vern: "Blongios nain, Butor blongios",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2514",
    cd_ref: "2514",
    lb_nom: "Ciconia nigra",
    nom_vern: "Cigogne noire",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2516",
    cd_ref: "2514",
    lb_nom: "Ardea nigra",
    nom_vern: "Cigogne noire",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "971",
    cd_ref: "971",
    lb_nom: "Podiceps auritus",
    nom_vern: "Grèbe esclavon",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "973",
    cd_ref: "971",
    lb_nom: "Colymbus auritus",
    nom_vern: "Grèbe esclavon",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380267",
    cd_ref: "971",
    lb_nom: "Podicipes auritus",
    nom_vern: "Grèbe esclavon",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "965",
    cd_ref: "965",
    lb_nom: "Podiceps cristatus",
    nom_vern: "Grèbe huppé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "967",
    cd_ref: "965",
    lb_nom: "Colymbus cristatus",
    nom_vern: "Grèbe huppé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380268",
    cd_ref: "965",
    lb_nom: "Podicipes cristatus",
    nom_vern: "Grèbe huppé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "968",
    cd_ref: "968",
    lb_nom: "Podiceps grisegena",
    nom_vern: "Grèbe jougris",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "970",
    cd_ref: "968",
    lb_nom: "Colymbus grisegena",
    nom_vern: "Grèbe jougris",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380269",
    cd_ref: "968",
    lb_nom: "Podicipes grisegena",
    nom_vern: "Grèbe jougris",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "974",
    cd_ref: "974",
    lb_nom: "Podiceps nigricollis",
    nom_vern: "Grèbe à cou noir",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "380266",
    cd_ref: "974",
    lb_nom: "Podicipes nigricollis",
    nom_vern: "Grèbe à cou noir",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "982",
    cd_ref: "982",
    lb_nom: "Podilymbus podiceps",
    nom_vern: "Grèbe à bec bigarré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "814135",
    cd_ref: "982",
    lb_nom: "Colymbus podiceps",
    nom_vern: "Grèbe à bec bigarré",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "977",
    cd_ref: "977",
    lb_nom: "Tachybaptus ruficollis",
    nom_vern: "Grèbe castagneux",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "979",
    cd_ref: "977",
    lb_nom: "Colymbus ruficollis",
    nom_vern: "Grèbe castagneux",
    regne: "Animalia",
    classe: "Aves",
  },
];
