import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_13: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "554821",
    cd_ref: "66371",
    lb_nom: "Squalus perlo",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66376",
    cd_ref: "66376",
    lb_nom: "Hexanchus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555683",
    cd_ref: "66376",
    lb_nom: "Hexanchus corinum",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555684",
    cd_ref: "66376",
    lb_nom: "Hexanchus corinus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564060",
    cd_ref: "66376",
    lb_nom: "Hexanchus griseus australis",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564891",
    cd_ref: "66376",
    lb_nom: "Monopterhinus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581794",
    cd_ref: "66376",
    lb_nom: "Monopterinus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66378",
    cd_ref: "66376",
    lb_nom: "Notidanus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563801",
    cd_ref: "66376",
    lb_nom: "Notidanus monge",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66379",
    cd_ref: "66376",
    lb_nom: "Notidanus vulgaris",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "546241",
    cd_ref: "66376",
    lb_nom: "Squalus griseus",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554888",
    cd_ref: "66376",
    lb_nom: "Squalus vacca",
    nom_vern: "Requin griset",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66382",
    cd_ref: "66382",
    lb_nom: "Hexanchus nakamurai",
    nom_vern: "Requin vache",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564061",
    cd_ref: "66382",
    lb_nom: "Hexanchus griseus nakamurai",
    nom_vern: "Requin vache",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66380",
    cd_ref: "66382",
    lb_nom: "Hexanchus vitulus",
    nom_vern: "Requin vache",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66391",
    cd_ref: "66391",
    lb_nom: "Odontaspis ferox",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66394",
    cd_ref: "66391",
    lb_nom: "Carcharias ferox",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66393",
    cd_ref: "66391",
    lb_nom: "Odontaspis herbsti",
    nom_vern: "Requin féroce",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
];
