import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_02: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "985500",
    cd_ref: "416999",
    lb_nom: "Papilio disparilis",
    nom_vern: "Papillon la Pâture",
    regne: "Animalia",
    classe: "Insecta",
  },
  {
    cd_nom: "212",
    cd_ref: "212",
    lb_nom: "Bombina variegata",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "214",
    cd_ref: "212",
    lb_nom: "Rana variegata",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1020126",
    cd_ref: "212",
    lb_nom: "Bombina salsa",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1042155",
    cd_ref: "212",
    lb_nom: "Bombinator igneus",
    nom_vern: "Sonneur à ventre jaune (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "292",
    cd_ref: "292",
    lb_nom: "Hyla meridionalis",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "286",
    cd_ref: "292",
    lb_nom: "Hyla africana",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "294",
    cd_ref: "292",
    lb_nom: "Hyla arborea var. meridionalis",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "296",
    cd_ref: "292",
    lb_nom: "Hyla barytonus",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "295",
    cd_ref: "292",
    lb_nom: "Hyla perezii",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "1009333",
    cd_ref: "292",
    lb_nom: "Hyla arborea meridionalis",
    nom_vern: "Rainette méridionale (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "240",
    cd_ref: "240",
    lb_nom: "Pelobates fuscus",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "242",
    cd_ref: "240",
    lb_nom: "Bufo fuscus",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "243",
    cd_ref: "240",
    lb_nom: "Cultripes minor",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "699685",
    cd_ref: "240",
    lb_nom: "Pelobates fuscus fuscus",
    nom_vern: "Pélobate brun (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "299",
    cd_ref: "299",
    lb_nom: "Rana arvalis",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "302",
    cd_ref: "299",
    lb_nom: "Rana palustris",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "303",
    cd_ref: "299",
    lb_nom: "Rana ulginosa",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
];
