import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_18: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "386336",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens lutea",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "386337",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens pulchra",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "569433",
    cd_ref: "386316",
    lb_nom: "Holothuria ophidiana",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "445442",
    cd_ref: "445442",
    lb_nom: "Bidens aoraiensis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "445456",
    cd_ref: "445456",
    lb_nom: "Bidens orofenensis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "452570",
    cd_ref: "445456",
    lb_nom: "Bidens societatis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "103626",
    cd_ref: "103626",
    lb_nom: "Inula helenioides",
    nom_vern: "Inule faux hélénium, Inule fausse aunée, Inule fausse hélénie",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "100868",
    cd_ref: "103626",
    lb_nom: "Helenium helenioides",
    nom_vern: "Inule faux hélénium, Inule fausse aunée, Inule fausse hélénie",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "445484",
    cd_ref: "445484",
    lb_nom: "Senecio stokesii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "706492",
    cd_ref: "706492",
    lb_nom: "Lobelia parva",
    nom_vern: "Lobélie petite",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "3885",
    cd_ref: "3885",
    lb_nom: "Buxbaumia viridis",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "3886",
    cd_ref: "3885",
    lb_nom: "Buxbaumia indusiata",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125935",
    cd_ref: "125935",
    lb_nom: "Tetragonia tetragonoides",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "94608",
    cd_ref: "125935",
    lb_nom: "Demidovia tetragonoides",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "614189",
    cd_ref: "125935",
    lb_nom: "Tetragonia cornuta",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125931",
    cd_ref: "125935",
    lb_nom: "Tetragonia cornuta",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "830414",
    cd_ref: "125935",
    lb_nom: "Tetragonia expansa var. cornuta",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "125932",
    cd_ref: "125935",
    lb_nom: "Tetragonia expansa",
    nom_vern:
      "Tétragone fausse tétragone, Tétragone cornue, Tétragone, Épinard de Nouvelle-Zélande",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];
