import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_17: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "60744",
    cd_ref: "60731",
    lb_nom: "Mustela rotschildi",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60745",
    cd_ref: "60731",
    lb_nom: "Mustela stantschinskii",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "60742",
    cd_ref: "60731",
    lb_nom: "Putorius putorius",
    nom_vern: "Putois d'Europe, Putois, Furet",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "535463",
    cd_ref: "535463",
    lb_nom: "Hydrurga leptonyx",
    nom_vern: "Léopard de mer",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186209",
    cd_ref: "186209",
    lb_nom: "Bovidae",
    nom_vern: "Bisons, Boeufs",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186233",
    cd_ref: "186233",
    lb_nom: "Chiroptera",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186236",
    cd_ref: "186233",
    lb_nom: "Microchiroptera",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "192256",
    cd_ref: "192256",
    lb_nom: "Eptesicus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "195005",
    cd_ref: "195005",
    lb_nom: "Myotis",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "186259",
    cd_ref: "186259",
    lb_nom: "Muridae",
    nom_vern: "Souris, Campagnols, Mulots, Rats",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "194935",
    cd_ref: "194935",
    lb_nom: "Mus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Mammalia",
  },
  {
    cd_nom: "7466",
    cd_ref: "7466",
    lb_nom: "Epizoanthus arenaceus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Anthozoa",
  },
  {
    cd_nom: "386316",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "371739",
    cd_ref: "386316",
    lb_nom: "Fistularia impatiens",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "359560",
    cd_ref: "386316",
    lb_nom: "Holothuria botellus",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "569419",
    cd_ref: "386316",
    lb_nom: "Holothuria fulva",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "386334",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens bicolor",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
  {
    cd_nom: "386335",
    cd_ref: "386316",
    lb_nom: "Holothuria impatiens concolor",
    nom_vern: "",
    regne: "Animalia",
    classe: "Holothuroidea",
  },
];
