import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_23: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "6720",
    cd_ref: "6720",
    lb_nom: "Sphagnum affine",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "788386",
    cd_ref: "6720",
    lb_nom: "Sphagnum affine var. affine",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435494",
    cd_ref: "6720",
    lb_nom: "Sphagnum affine var. flagellare",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435495",
    cd_ref: "6720",
    lb_nom: "Sphagnum imbricatum subsp. affine",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "786824",
    cd_ref: "6720",
    lb_nom: "Sphagnum imbricatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6722",
    cd_ref: "6722",
    lb_nom: "Sphagnum angustifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "787676",
    cd_ref: "6722",
    lb_nom: "Sphagnum parvifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435498",
    cd_ref: "6722",
    lb_nom: "Sphagnum recurvum var. tenue",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6724",
    cd_ref: "6724",
    lb_nom: "Sphagnum austinii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435496",
    cd_ref: "6724",
    lb_nom: "Sphagnum imbricatum subsp. austinii",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6725",
    cd_ref: "6725",
    lb_nom: "Sphagnum balticum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6736",
    cd_ref: "6736",
    lb_nom: "Sphagnum contortum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6737",
    cd_ref: "6736",
    lb_nom: "Sphagnum laricinum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435504",
    cd_ref: "6736",
    lb_nom: "Sphagnum subsecundum var. contortum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "6746",
    cd_ref: "6746",
    lb_nom: "Sphagnum fallax",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "786823",
    cd_ref: "6746",
    lb_nom: "Sphagnum apiculatum",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "435500",
    cd_ref: "6746",
    lb_nom: "Sphagnum brevifolium",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
  {
    cd_nom: "788204",
    cd_ref: "6746",
    lb_nom: "Sphagnum fallax subsp. fallax",
    nom_vern: "",
    regne: "Plantae",
    classe: "Equisetopsida",
  },
];
