import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_05: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "2852",
    cd_ref: "2852",
    lb_nom: "Gypaetus barbatus",
    nom_vern: "Gypaète barbu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2854",
    cd_ref: "2852",
    lb_nom: "Vultur barbatus",
    nom_vern: "Gypaète barbu",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2660",
    cd_ref: "2660",
    lb_nom: "Pandion haliaetus",
    nom_vern: "Balbuzard pêcheur",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2662",
    cd_ref: "2660",
    lb_nom: "Falco haliaetus",
    nom_vern: "Balbuzard pêcheur",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1973",
    cd_ref: "1973",
    lb_nom: "Anas acuta",
    nom_vern: "Canard pilet",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1948",
    cd_ref: "1948",
    lb_nom: "Anas bahamensis",
    nom_vern: "Canard des Bahamas, Pilet des Bahamas",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1958",
    cd_ref: "1958",
    lb_nom: "Anas crecca",
    nom_vern: "Sarcelle d'hiver",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1960",
    cd_ref: "1960",
    lb_nom: "Anas crecca crecca",
    nom_vern: "Sarcelle d'hiver",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1988",
    cd_ref: "1988",
    lb_nom: "Aythya collaris",
    nom_vern: "Fuligule à bec cerclé, Fuligule à collier, Morillon à collier",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1990",
    cd_ref: "1988",
    lb_nom: "Anas collaris",
    nom_vern: "Fuligule à bec cerclé, Fuligule à collier, Morillon à collier",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1955",
    cd_ref: "1955",
    lb_nom: "Mareca americana",
    nom_vern: "Canard à front blanc, Canard d'Amérique, Canard siffleur d'Amérique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1953",
    cd_ref: "1955",
    lb_nom: "Anas americana",
    nom_vern: "Canard à front blanc, Canard d'Amérique, Canard siffleur d'Amérique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1972",
    cd_ref: "1972",
    lb_nom: "Spatula clypeata",
    nom_vern: "Canard souchet",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1970",
    cd_ref: "1972",
    lb_nom: "Anas clypeata",
    nom_vern: "Canard souchet",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2709",
    cd_ref: "2709",
    lb_nom: "Cygnus columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2711",
    cd_ref: "2709",
    lb_nom: "Anas Columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2703",
    cd_ref: "2709",
    lb_nom: "Cygnus colombianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2713",
    cd_ref: "2709",
    lb_nom: "Cygnus columbianus columbianus",
    nom_vern: "Cygne de Bewick",
    regne: "Animalia",
    classe: "Aves",
  },
];
