import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_07: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "2668",
    cd_ref: "2666",
    lb_nom: "Cerchneis naumanni",
    nom_vern: "Faucon crécerellette",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "953",
    cd_ref: "953",
    lb_nom: "Gavia adamsii",
    nom_vern: "Plongeon à bec blanc",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "955",
    cd_ref: "953",
    lb_nom: "Colymbus adamsii",
    nom_vern: "Plongeon à bec blanc",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "956",
    cd_ref: "956",
    lb_nom: "Gavia arctica",
    nom_vern: "Plongeon arctique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "958",
    cd_ref: "956",
    lb_nom: "Colymbus arcticus",
    nom_vern: "Plongeon arctique",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "959",
    cd_ref: "959",
    lb_nom: "Gavia immer",
    nom_vern: "Plongeon imbrin",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961",
    cd_ref: "959",
    lb_nom: "Colymbus immer",
    nom_vern: "Plongeon imbrin",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3053",
    cd_ref: "3053",
    lb_nom: "Crex crex",
    nom_vern: "Râle des genêts",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3055",
    cd_ref: "3053",
    lb_nom: "Rallus crex",
    nom_vern: "Râle des genêts",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "1053763",
    cd_ref: "3053",
    lb_nom: "Crex pratensis",
    nom_vern: "Râle des genêts",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3089",
    cd_ref: "3089",
    lb_nom: "Tetrax tetrax",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "961340",
    cd_ref: "3089",
    lb_nom: "Otis tetrax orientalis",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3091",
    cd_ref: "3089",
    lb_nom: "Otis tetrax",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3092",
    cd_ref: "3089",
    lb_nom: "Tetrax tetrax orientalis",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "3093",
    cd_ref: "3089",
    lb_nom: "Tetrax tetrax tetrax",
    nom_vern: "Outarde canepetière",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2473",
    cd_ref: "2473",
    lb_nom: "Botaurus stellaris",
    nom_vern: "Butor étoilé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2475",
    cd_ref: "2473",
    lb_nom: "Ardea stellaris",
    nom_vern: "Butor étoilé",
    regne: "Animalia",
    classe: "Aves",
  },
  {
    cd_nom: "2477",
    cd_ref: "2477",
    lb_nom: "Ixobrychus minutus",
    nom_vern: "Blongios nain, Butor blongios",
    regne: "Animalia",
    classe: "Aves",
  },
];
