import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_12: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "566383",
    cd_ref: "66465",
    lb_nom: "Galeolamna greyi mckaili",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "581854",
    cd_ref: "66465",
    lb_nom: "Galeolamna leucas",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563471",
    cd_ref: "66465",
    lb_nom: "Galeolamna mckaili",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "565551",
    cd_ref: "66465",
    lb_nom: "Prionodon platyodon",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554817",
    cd_ref: "66465",
    lb_nom: "Squalus obtusus",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554823",
    cd_ref: "66465",
    lb_nom: "Squalus platyodon",
    nom_vern: "Requin bouledogue",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66371",
    cd_ref: "66371",
    lb_nom: "Heptranchias perlo",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555675",
    cd_ref: "66371",
    lb_nom: "Heptranchias angio",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555677",
    cd_ref: "66371",
    lb_nom: "Heptranchias cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555678",
    cd_ref: "66371",
    lb_nom: "Heptranchias dakini",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "555679",
    cd_ref: "66371",
    lb_nom: "Heptranchias deani",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "564111",
    cd_ref: "66371",
    lb_nom: "Heptrancus angio",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66373",
    cd_ref: "66371",
    lb_nom: "Heptrianchias cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "66374",
    cd_ref: "66371",
    lb_nom: "Heptrianchias deani",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "566363",
    cd_ref: "66371",
    lb_nom: "Notidanus cinereus aetatis",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "566364",
    cd_ref: "66371",
    lb_nom: "Notidanus cinereus pristiurus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "563797",
    cd_ref: "66371",
    lb_nom: "Notidanus cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
  {
    cd_nom: "554782",
    cd_ref: "66371",
    lb_nom: "Squalus cinereus",
    nom_vern: "Requin perlon",
    regne: "Animalia",
    classe: "Elasmobranchii",
  },
];
