import type { EspeceTaxrefInitializer } from "@pitchou/types/database/public/EspeceTaxref.ts";

export const TAXREF_CHUNK_03: EspeceTaxrefInitializer[] = [
  {
    cd_nom: "1056557",
    cd_ref: "299",
    lb_nom: "Rana terrestris",
    nom_vern: "Grenouille des champs (La), Grenouille oxyrhine",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "59",
    cd_ref: "59",
    lb_nom: "Euproctus montanus",
    nom_vern: "Euprocte de Corse (L')",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "61",
    cd_ref: "59",
    lb_nom: "Megapterna montana",
    nom_vern: "Euprocte de Corse (L')",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "86",
    cd_ref: "86",
    lb_nom: "Salamandra atra atra",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "17",
    cd_ref: "86",
    lb_nom: "Geotriton fuscus",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "82",
    cd_ref: "86",
    lb_nom: "Salamandra atra",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "84",
    cd_ref: "86",
    lb_nom: "Salamandra fusca",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "85",
    cd_ref: "86",
    lb_nom: "Salamandra nigra",
    nom_vern: "Salamandre noire (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "92",
    cd_ref: "92",
    lb_nom: "Salamandra salamandra",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "94",
    cd_ref: "92",
    lb_nom: "Lacerta salamandra",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "95",
    cd_ref: "92",
    lb_nom: "Salamandra maculata",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "96",
    cd_ref: "92",
    lb_nom: "Salamandra maculosa",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "98",
    cd_ref: "92",
    lb_nom: "Salamandra vulgaris",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "97",
    cd_ref: "92",
    lb_nom: "Triton corthyphorus",
    nom_vern: "Salamandre tachetée (La)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "100",
    cd_ref: "100",
    lb_nom: "Salamandra salamandra salamandra",
    nom_vern: "",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "139",
    cd_ref: "139",
    lb_nom: "Triturus cristatus",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "145",
    cd_ref: "139",
    lb_nom: "Lacerta lacustris",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
  {
    cd_nom: "144",
    cd_ref: "139",
    lb_nom: "Lacerta triton",
    nom_vern: "Triton crêté (Le)",
    regne: "Animalia",
    classe: "Amphibia",
  },
];
