import type { Knex } from "knex";

import { replaceEspecesProtegees } from "../../src/lib/server/especeProtegee.ts";

import type {
  EspeceProtegeeInitializer,
  EspeceProtegeeCdRef,
} from "../../scripts/types/database/public/EspeceProtegee.ts";

// Curated, hand-picked sample of protected species for dev / CI / tests.
//
// This is intentionally a small *fixed fixture*, NOT a full or fresh dataset: it
// exists so the app and tests have realistic data to run against without needing
// the multi-hundred-MB INPN sources. The real table is populated in production
// from those sources via `just generate-especes-protegees` (outils/liste-espèces.ts).
//
// Rows are real INPN entries chosen to cover the full variety the UI must handle:
// all three classifications, every statut type (PN / PR / PD / POM / Protection
// Pitchou, alone and combined), the ministérielle and CNPN list flags, and species
// with several scientific synonyms or vernacular names. `espece_ministerielle` and
// `espece_cnpn` default to false and are only set when true.
const ESPECES_PROTEGEES: EspeceProtegeeInitializer[] = [
  {
    cd_ref: "59",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Euproctus montanus", "Megapterna montana"],
    noms_vernaculaires: ["Euprocte de Corse (L')"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "86",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Salamandra atra atra",
      "Geotriton fuscus",
      "Salamandra atra",
      "Salamandra fusca",
      "Salamandra nigra",
    ],
    noms_vernaculaires: ["Salamandre noire (La)"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "92",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Salamandra salamandra",
      "Lacerta salamandra",
      "Salamandra maculata",
      "Salamandra maculosa",
      "Salamandra vulgaris",
      "Triton corthyphorus",
    ],
    noms_vernaculaires: ["Salamandre tachetée (La)"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "100",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Salamandra salamandra salamandra"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "139",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Triturus cristatus",
      "Lacerta lacustris",
      "Lacerta triton",
      "Salamandra lati-caudata",
      "Salamandra platyura",
      "Triton cristatus",
      "Triton intermedius",
      "Triton trouessarti",
      "Triturus cristatus cristatus",
      "Triturus (cristatus) cristatus",
      "Molge cristata",
    ],
    noms_vernaculaires: ["Triton crêté (Le)"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "212",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Bombina variegata",
      "Rana variegata",
      "Bombina salsa",
      "Bombinator igneus",
    ],
    noms_vernaculaires: ["Sonneur à ventre jaune (Le)"],
    cd_type_statuts: ["PN"],
    espece_cnpn: true,
  },
  {
    cd_ref: "240",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Pelobates fuscus",
      "Bufo fuscus",
      "Cultripes minor",
      "Pelobates fuscus fuscus",
    ],
    noms_vernaculaires: ["Pélobate brun (Le)"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "292",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Hyla meridionalis",
      "Hyla africana",
      "Hyla arborea var. meridionalis",
      "Hyla barytonus",
      "Hyla perezii",
      "Hyla arborea meridionalis",
    ],
    noms_vernaculaires: ["Rainette méridionale (La)"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "299",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Rana arvalis", "Rana palustris", "Rana ulginosa", "Rana terrestris"],
    noms_vernaculaires: ["Grenouille des champs (La)", "Grenouille oxyrhine"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "953",
    classification: "oiseau",
    noms_scientifiques: ["Gavia adamsii", "Colymbus adamsii"],
    noms_vernaculaires: ["Plongeon à bec blanc"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "956",
    classification: "oiseau",
    noms_scientifiques: ["Gavia arctica", "Colymbus arcticus"],
    noms_vernaculaires: ["Plongeon arctique"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "959",
    classification: "oiseau",
    noms_scientifiques: ["Gavia immer", "Colymbus immer"],
    noms_vernaculaires: ["Plongeon imbrin"],
    cd_type_statuts: ["PN", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "965",
    classification: "oiseau",
    noms_scientifiques: ["Podiceps cristatus", "Colymbus cristatus", "Podicipes cristatus"],
    noms_vernaculaires: ["Grèbe huppé"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "968",
    classification: "oiseau",
    noms_scientifiques: ["Podiceps grisegena", "Colymbus grisegena", "Podicipes grisegena"],
    noms_vernaculaires: ["Grèbe jougris"],
    cd_type_statuts: ["PN", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "971",
    classification: "oiseau",
    noms_scientifiques: ["Podiceps auritus", "Colymbus auritus", "Podicipes auritus"],
    noms_vernaculaires: ["Grèbe esclavon"],
    cd_type_statuts: ["PN", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "974",
    classification: "oiseau",
    noms_scientifiques: ["Podiceps nigricollis", "Podicipes nigricollis"],
    noms_vernaculaires: ["Grèbe à cou noir"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "977",
    classification: "oiseau",
    noms_scientifiques: ["Tachybaptus ruficollis", "Colymbus ruficollis", "Podiceps ruficollis"],
    noms_vernaculaires: ["Grèbe castagneux"],
    cd_type_statuts: ["PN", "PD"],
  },
  {
    cd_ref: "982",
    classification: "oiseau",
    noms_scientifiques: ["Podilymbus podiceps", "Colymbus podiceps"],
    noms_vernaculaires: ["Grèbe à bec bigarré"],
    cd_type_statuts: ["PN", "PD", "POM"],
  },
  {
    cd_ref: "994",
    classification: "oiseau",
    noms_scientifiques: ["Macronectes giganteus", "Procellaria gigantea"],
    noms_vernaculaires: ["Fulmar géant", "Fulmar de Hall", "Pétrel géant"],
    cd_type_statuts: ["PN", "PD", "POM"],
  },
  {
    cd_ref: "1005",
    classification: "oiseau",
    noms_scientifiques: ["Bulweria bulwerii", "Procellaria bulwerii", "Thalassidroma bulwerii"],
    noms_vernaculaires: ["Pétrel de Bulwer"],
    cd_type_statuts: ["PN", "PD"],
  },
  {
    cd_ref: "1009",
    classification: "oiseau",
    noms_scientifiques: [
      "Calonectris diomedea",
      "Calonectris diomedea diomedea",
      "Procellaria diomedea",
      "Procellaria kuhlii",
      "Puffinus diomedea",
      "Puffinus kuhli",
    ],
    noms_vernaculaires: ["Puffin de Scopoli"],
    cd_type_statuts: ["PN", "PD", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "1027",
    classification: "oiseau",
    noms_scientifiques: ["Puffinus puffinus", "Procellaria puffinus", "Puffinus puffinus puffinus"],
    noms_vernaculaires: ["Puffin des Anglais"],
    cd_type_statuts: ["PN", "PD", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "1031",
    classification: "oiseau",
    noms_scientifiques: [
      "Puffinus yelkouan",
      "Procellaria yelkouan",
      "Puffinus puffinus yelkouan",
      "Puffinus yelkouan yelkouan",
    ],
    noms_vernaculaires: ["Puffin yelkouan"],
    cd_type_statuts: ["PN"],
    espece_cnpn: true,
  },
  {
    cd_ref: "1948",
    classification: "oiseau",
    noms_scientifiques: ["Anas bahamensis"],
    noms_vernaculaires: ["Canard des Bahamas", "Pilet des Bahamas"],
    cd_type_statuts: ["PN", "PD"],
  },
  {
    cd_ref: "1955",
    classification: "oiseau",
    noms_scientifiques: ["Mareca americana", "Anas americana"],
    noms_vernaculaires: ["Canard à front blanc", "Canard d'Amérique", "Canard siffleur d'Amérique"],
    cd_type_statuts: ["PN", "PD"],
  },
  {
    cd_ref: "1958",
    classification: "oiseau",
    noms_scientifiques: ["Anas crecca"],
    noms_vernaculaires: ["Sarcelle d'hiver"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "1960",
    classification: "oiseau",
    noms_scientifiques: ["Anas crecca crecca"],
    noms_vernaculaires: ["Sarcelle d'hiver"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "1972",
    classification: "oiseau",
    noms_scientifiques: ["Spatula clypeata", "Anas clypeata"],
    noms_vernaculaires: ["Canard souchet"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "1973",
    classification: "oiseau",
    noms_scientifiques: ["Anas acuta"],
    noms_vernaculaires: ["Canard pilet"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "1988",
    classification: "oiseau",
    noms_scientifiques: ["Aythya collaris", "Anas collaris"],
    noms_vernaculaires: ["Fuligule à bec cerclé", "Fuligule à collier", "Morillon à collier"],
    cd_type_statuts: ["PN", "PD"],
  },
  {
    cd_ref: "2419",
    classification: "oiseau",
    noms_scientifiques: ["Hydrobates pelagicus", "Procellaria pelagica"],
    noms_vernaculaires: ["Océanite tempête", "Pétrel tempête"],
    cd_type_statuts: ["PN"],
    espece_cnpn: true,
  },
  {
    cd_ref: "2473",
    classification: "oiseau",
    noms_scientifiques: ["Botaurus stellaris", "Ardea stellaris"],
    noms_vernaculaires: ["Butor étoilé"],
    cd_type_statuts: ["PN"],
    espece_cnpn: true,
  },
  {
    cd_ref: "2477",
    classification: "oiseau",
    noms_scientifiques: ["Ixobrychus minutus", "Ardea minuta"],
    noms_vernaculaires: ["Blongios nain", "Butor blongios"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "2514",
    classification: "oiseau",
    noms_scientifiques: ["Ciconia nigra", "Ardea nigra"],
    noms_vernaculaires: ["Cigogne noire"],
    cd_type_statuts: ["PN"],
    espece_cnpn: true,
  },
  {
    cd_ref: "2557",
    classification: "oiseau",
    noms_scientifiques: ["Limnodromus griseus", "Scolopax grisea"],
    noms_vernaculaires: [
      "Bécassin à bec court",
      "Limnodrome à bec court",
      "Bécassin roux",
      "Grise à long bec",
    ],
    cd_type_statuts: ["PN", "PD"],
  },
  {
    cd_ref: "2571",
    classification: "oiseau",
    noms_scientifiques: ["Numenius phaeopus", "Scolopax phaeopus"],
    noms_vernaculaires: ["Courlis corlieu"],
    cd_type_statuts: ["PN", "PD"],
    espece_cnpn: true,
  },
  {
    cd_ref: "2645",
    classification: "oiseau",
    noms_scientifiques: ["Aquila chrysaetos", "Aquila fulva", "Falco chrysaetos", "Falco fulvus"],
    noms_vernaculaires: ["Aigle royal"],
    cd_type_statuts: ["PN", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "2657",
    classification: "oiseau",
    noms_scientifiques: ["Aquila fasciata", "Hieraaetus fasciatus"],
    noms_vernaculaires: ["Aigle de Bonelli"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "2660",
    classification: "oiseau",
    noms_scientifiques: ["Pandion haliaetus", "Falco haliaetus"],
    noms_vernaculaires: ["Balbuzard pêcheur"],
    cd_type_statuts: ["PN", "PD", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "2666",
    classification: "oiseau",
    noms_scientifiques: ["Falco naumanni", "Cerchneis naumanni"],
    noms_vernaculaires: ["Faucon crécerellette"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "2709",
    classification: "oiseau",
    noms_scientifiques: [
      "Cygnus columbianus",
      "Anas Columbianus",
      "Cygnus colombianus",
      "Cygnus columbianus columbianus",
      "Olor columbianus",
    ],
    noms_vernaculaires: ["Cygne de Bewick"],
    cd_type_statuts: ["PN", "POM"],
    espece_cnpn: true,
  },
  {
    cd_ref: "2826",
    classification: "oiseau",
    noms_scientifiques: ["Oxyura leucocephala", "Anas leucocephala"],
    noms_vernaculaires: ["Érismature à tête blanche"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "2852",
    classification: "oiseau",
    noms_scientifiques: ["Gypaetus barbatus", "Vultur barbatus"],
    noms_vernaculaires: ["Gypaète barbu"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "2869",
    classification: "oiseau",
    noms_scientifiques: ["Aegypius monachus", "Vultur monachus"],
    noms_vernaculaires: ["Vautour moine"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "3053",
    classification: "oiseau",
    noms_scientifiques: ["Crex crex", "Rallus crex", "Crex pratensis"],
    noms_vernaculaires: ["Râle des genêts"],
    cd_type_statuts: ["PN", "POM"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "3089",
    classification: "oiseau",
    noms_scientifiques: [
      "Tetrax tetrax",
      "Otis tetrax orientalis",
      "Otis tetrax",
      "Tetrax tetrax orientalis",
      "Tetrax tetrax tetrax",
    ],
    noms_vernaculaires: ["Outarde canepetière"],
    cd_type_statuts: ["PN"],
    espece_ministerielle: true,
  },
  {
    cd_ref: "3420",
    classification: "oiseau",
    noms_scientifiques: ["Columba livia"],
    noms_vernaculaires: ["Pigeon biset"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "3429",
    classification: "oiseau",
    noms_scientifiques: [
      "Streptopelia decaocto",
      "Columba decaocto",
      "Columba risoria L. var. decaocto",
    ],
    noms_vernaculaires: ["Tourterelle turque"],
    cd_type_statuts: ["Protection Pitchou"],
  },
  {
    cd_ref: "3885",
    classification: "flore",
    noms_scientifiques: ["Buxbaumia viridis", "Buxbaumia indusiata"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "3912",
    classification: "flore",
    noms_scientifiques: ["Crossidium aberrans"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "4387",
    classification: "flore",
    noms_scientifiques: ["Fissidens monguillonii"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "4388",
    classification: "flore",
    noms_scientifiques: ["Fissidens osmundoides"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "4393",
    classification: "flore",
    noms_scientifiques: ["Fissidens rivularis", "Fissidens bryoides var. rivularis"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "4763",
    classification: "flore",
    noms_scientifiques: ["Dicranum viride", "Paraleucobryum viride", "Campylopus viridis"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "4770",
    classification: "flore",
    noms_scientifiques: ["Leucobryum glaucum", "Dicranum glaucum"],
    noms_vernaculaires: ["Coussinet des bois"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "4797",
    classification: "flore",
    noms_scientifiques: ["Bruchia vogesiaca"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PN", "PR"],
  },
  {
    cd_ref: "4964",
    classification: "flore",
    noms_scientifiques: ["Meesia longiseta", "Diplocomium longisetum"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "5036",
    classification: "flore",
    noms_scientifiques: ["Orthotrichum rogeri", "Orthotrichum rogeri var. rogeri"],
    noms_vernaculaires: ["Orthotric de Roger"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "6720",
    classification: "flore",
    noms_scientifiques: [
      "Sphagnum affine",
      "Sphagnum affine var. affine",
      "Sphagnum affine var. flagellare",
      "Sphagnum imbricatum subsp. affine",
      "Sphagnum imbricatum",
    ],
    noms_vernaculaires: [],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "6722",
    classification: "flore",
    noms_scientifiques: [
      "Sphagnum angustifolium",
      "Sphagnum parvifolium",
      "Sphagnum recurvum var. tenue",
    ],
    noms_vernaculaires: [],
    cd_type_statuts: ["PR", "PD"],
  },
  {
    cd_ref: "6724",
    classification: "flore",
    noms_scientifiques: ["Sphagnum austinii", "Sphagnum imbricatum subsp. austinii"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "6725",
    classification: "flore",
    noms_scientifiques: ["Sphagnum balticum"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "6736",
    classification: "flore",
    noms_scientifiques: [
      "Sphagnum contortum",
      "Sphagnum laricinum",
      "Sphagnum subsecundum var. contortum",
    ],
    noms_vernaculaires: [],
    cd_type_statuts: ["PR", "PD"],
  },
  {
    cd_ref: "6746",
    classification: "flore",
    noms_scientifiques: [
      "Sphagnum fallax",
      "Sphagnum apiculatum",
      "Sphagnum brevifolium",
      "Sphagnum fallax subsp. fallax",
      "Sphagnum fallax subsp. isoviitae",
      "Sphagnum isoviitae",
      "Sphagnum recurvum subsp. mucronatum",
      "Sphagnum recurvum var. brevifolium",
      "Sphagnum recurvum var. mucronatum",
    ],
    noms_vernaculaires: [],
    cd_type_statuts: ["PR", "PD"],
  },
  {
    cd_ref: "7466",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Epizoanthus arenaceus"],
    noms_vernaculaires: [],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "8332",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Cicindela sylvatica", "Cicindela sylvatica sylvatica"],
    noms_vernaculaires: ["Cicindèle à labre noir"],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "9074",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Pterostichus aterrimus",
      "Carabus aterrimus",
      "Omaseus aterrimus",
      "Pterostichus (Argutor) aterrimus",
    ],
    noms_vernaculaires: ["Poecile fovéolé"],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "9266",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Ophonus cordatus",
      "Carabus cordatus",
      "Carabus porosus",
      "Harpalus iberiae",
    ],
    noms_vernaculaires: ["Ophone cordiforme"],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "9370",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Oodes gracilis", "Oodes gracilior", "Oodes similis"],
    noms_vernaculaires: ["Oode gracile"],
    cd_type_statuts: ["PR"],
  },
  {
    cd_ref: "60658",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Martes martes",
      "Martes abietum",
      "Martes latinorum",
      "Martes martes lorenzi",
      "Martes martes martes",
      "Martes martes sabaneevi",
      "Martes martes uralensis",
      "Martes notialis",
      "Martes ruthena",
      "Martes sylvestris",
      "Martes vulgaris",
      "Mustela martes",
    ],
    noms_vernaculaires: ["Martre des pins", "Martre"],
    cd_type_statuts: ["Protection Pitchou"],
  },
  {
    cd_ref: "60674",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Martes foina",
      "Martes foina bunites",
      "Martes foina foina",
      "Martes foina milleri",
      "Mustela alba",
      "Mustela bosniaca",
      "Mustela domestica",
      "Mustela foina",
      "Mustela mediterranea",
      "Mustela mehringi",
    ],
    noms_vernaculaires: ["Fouine"],
    cd_type_statuts: ["Protection Pitchou"],
  },
  {
    cd_ref: "60686",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Mustela erminea"],
    noms_vernaculaires: ["Hermine"],
    cd_type_statuts: ["Protection Pitchou"],
  },
  {
    cd_ref: "60716",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Mustela nivalis",
      "Mustela alpinus",
      "Mustela boccamela",
      "Mustela corsicana",
      "Mustela ibericus",
      "Mustela italicus",
      "Mustela meridionalis",
      "Mustela minor",
      "Mustela minutus",
      "Mustela monticola",
      "Mustela nivalis boccamela",
      "Mustela nivalis corsicana",
      "Mustela nivalis nivalis",
      "Mustela nivalis vulgaris",
      "Mustela typicus",
      "Mustela vulgaris",
    ],
    noms_vernaculaires: ["Belette d'Europe", "Belette"],
    cd_type_statuts: ["Protection Pitchou"],
  },
  {
    cd_ref: "60731",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Mustela putorius",
      "Mustela albus",
      "Mustela anglia",
      "Mustela aureola",
      "Mustela caledoniae",
      "Mustela foetens",
      "Mustela furo-putorius",
      "Mustela iltis",
      "Mustela infectus",
      "Mustela orientalis",
      "Mustela putorius putorius",
      "Mustela rotschildi",
      "Mustela stantschinskii",
      "Putorius putorius",
    ],
    noms_vernaculaires: ["Putois d'Europe", "Putois", "Furet"],
    cd_type_statuts: ["Protection Pitchou"],
  },
  {
    cd_ref: "66371",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Heptranchias perlo",
      "Heptranchias angio",
      "Heptranchias cinereus",
      "Heptranchias dakini",
      "Heptranchias deani",
      "Heptrancus angio",
      "Heptrianchias cinereus",
      "Heptrianchias deani",
      "Notidanus cinereus aetatis",
      "Notidanus cinereus pristiurus",
      "Notidanus cinereus",
      "Squalus cinereus",
      "Squalus perlo",
    ],
    noms_vernaculaires: ["Requin perlon"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "66376",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Hexanchus griseus",
      "Hexanchus corinum",
      "Hexanchus corinus",
      "Hexanchus griseus australis",
      "Monopterhinus griseus",
      "Monopterinus griseus",
      "Notidanus griseus",
      "Notidanus monge",
      "Notidanus vulgaris",
      "Squalus griseus",
      "Squalus vacca",
    ],
    noms_vernaculaires: ["Requin griset"],
    cd_type_statuts: ["PD", "POM"],
  },
  {
    cd_ref: "66382",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Hexanchus nakamurai", "Hexanchus griseus nakamurai", "Hexanchus vitulus"],
    noms_vernaculaires: ["Requin vache"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "66391",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Odontaspis ferox",
      "Carcharias ferox",
      "Odontaspis herbsti",
      "Squalus ferox",
    ],
    noms_vernaculaires: ["Requin féroce"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "66395",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Odontaspis noronhai", "Carcharias noronhai"],
    noms_vernaculaires: ["Requin noronhai"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "66459",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Carcharhinus falciformis",
      "Aprionodon sitankaiensis",
      "Carcharhinus atrodorsus",
      "Carcharhinus falciformes",
      "Carcharhinus floridanus",
      "Carcharhinus floridianus",
      "Carcharhinus menisorrah",
      "Carcharias falciformis",
      "Carcharias falcipinnis",
      "Carcharias menisorrah",
      "Carcharins menisorrah",
      "Carcharius menisorrah",
      "Eulamia malpeloensis",
      "Eulamia menisorrah",
      "Gymnorhinus pharaonis",
      "Prionodon tiburo",
      "Squalus tiburo",
    ],
    noms_vernaculaires: ["Requin soyeux"],
    cd_type_statuts: ["PD", "POM"],
  },
  {
    cd_ref: "66465",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Carcharhinus leucas",
      "Carcharhinus azureus",
      "Carcharhinus nicaraguensis",
      "Carcharhinus vanrooyeni",
      "Carcharhinus zambezensis",
      "Carcharias azureus",
      "Carcharias leucas",
      "Carcharias spenceri",
      "Carcharias zambezensis",
      "Eulamia nicaraguensis",
      "Galeolamna bogimba",
      "Galeolamna greyi mckaili",
      "Galeolamna leucas",
      "Galeolamna mckaili",
      "Prionodon platyodon",
      "Squalus obtusus",
      "Squalus platyodon",
    ],
    noms_vernaculaires: ["Requin bouledogue"],
    cd_type_statuts: ["PD", "POM"],
  },
  {
    cd_ref: "80014",
    classification: "flore",
    noms_scientifiques: [
      "Aconitum corsicum",
      "Aconitum napellus subsp. corsicum",
      "Aconitum pyramidale var. corsicum",
    ],
    noms_vernaculaires: ["Aconit de Corse"],
    cd_type_statuts: ["PN", "PR", "PD"],
  },
  {
    cd_ref: "84476",
    classification: "flore",
    noms_scientifiques: [
      "Asplenium cuneifolium",
      "Asplenium adiantum-nigrum subsp. cuneifolium",
      "Asplenium adiantum-nigrum var. cuneifolium",
    ],
    noms_vernaculaires: [
      "Doradille cunéiforme",
      "Doradille à feuilles en coin",
      "Doradille à feuilles cunéiformes",
    ],
    cd_type_statuts: ["PN", "PR"],
    espece_cnpn: true,
  },
  {
    cd_ref: "88792",
    classification: "flore",
    noms_scientifiques: [
      "Carex pseudobrizoides",
      "Carex brizoides proles clavaudiana",
      "Carex ohmuelleriana",
      "Carex pseudoarenaria",
      "Carex reichenbachii",
    ],
    noms_vernaculaires: ["Laîche fausse brize"],
    cd_type_statuts: ["PN", "PR"],
  },
  {
    cd_ref: "103626",
    classification: "flore",
    noms_scientifiques: ["Inula helenioides", "Helenium helenioides"],
    noms_vernaculaires: ["Inule faux hélénium", "Inule fausse aunée", "Inule fausse hélénie"],
    cd_type_statuts: ["PN"],
    espece_cnpn: true,
  },
  {
    cd_ref: "125935",
    classification: "flore",
    noms_scientifiques: [
      "Tetragonia tetragonoides",
      "Demidovia tetragonoides",
      "Tetragonia cornuta",
      "Tetragonia expansa var. cornuta",
      "Tetragonia expansa",
      "Tetragonia halimifolia",
      "Tetragonia japonica",
      "Tetragonia tetragonioides",
    ],
    noms_vernaculaires: [
      "Tétragone fausse tétragone",
      "Tétragone cornue",
      "Tétragone",
      "Épinard de Nouvelle-Zélande",
    ],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "133619",
    classification: "flore",
    noms_scientifiques: [
      "Cystopteris fragilis subsp. diaphana",
      "Aspidium viridulum",
      "Asplenium diaphanum",
      "Cystopteris atrovirens",
      "Cystopteris canariensis",
      "Cystopteris diaphana",
      "Cystopteris fragilis proles viridula",
      "Cystopteris fragilis subsp. canariensis",
      "Cystopteris fragilis",
      "Cystopteris viridula",
      "Polypodium diaphanum",
    ],
    noms_vernaculaires: ["Cystoptéride diaphane", "Cystoptéris diaphane", "Asplenium vert"],
    cd_type_statuts: ["PN", "PR", "PD"],
  },
  {
    cd_ref: "199352",
    classification: "oiseau",
    noms_scientifiques: ["Calidris tenuirostris", "Totanus tenuirostris"],
    noms_vernaculaires: ["Bécasseau de l'Anadyr"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "199357",
    classification: "oiseau",
    noms_scientifiques: ["Numenius minutus"],
    noms_vernaculaires: ["Courlis nain"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "199363",
    classification: "oiseau",
    noms_scientifiques: ["Heteroscelus brevipes", "Totanus brevipes", "Tringa brevipes"],
    noms_vernaculaires: ["Chevalier de Sibérie"],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "386316",
    classification: "faune non-oiseau",
    noms_scientifiques: [
      "Holothuria impatiens",
      "Fistularia impatiens",
      "Holothuria botellus",
      "Holothuria fulva",
      "Holothuria impatiens bicolor",
      "Holothuria impatiens concolor",
      "Holothuria impatiens lutea",
      "Holothuria impatiens pulchra",
      "Holothuria ophidiana",
    ],
    noms_vernaculaires: [],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "416999",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Papilio phorbanta", "Papilio disparilis"],
    noms_vernaculaires: ["Papillon la Pâture"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "417000",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Antanartia borbonica", "Vanessa borbonica", "Vanessa hippomene"],
    noms_vernaculaires: ["Vanesse de l’Obetie"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "432596",
    classification: "oiseau",
    noms_scientifiques: ["Circus maillardi"],
    noms_vernaculaires: ["Busard de Maillard"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "445442",
    classification: "flore",
    noms_scientifiques: ["Bidens aoraiensis"],
    noms_vernaculaires: [],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "445456",
    classification: "flore",
    noms_scientifiques: ["Bidens orofenensis", "Bidens societatis"],
    noms_vernaculaires: [],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "445484",
    classification: "flore",
    noms_scientifiques: ["Senecio stokesii"],
    noms_vernaculaires: [],
    cd_type_statuts: ["POM"],
  },
  {
    cd_ref: "535463",
    classification: "faune non-oiseau",
    noms_scientifiques: ["Hydrurga leptonyx"],
    noms_vernaculaires: ["Léopard de mer"],
    cd_type_statuts: ["PN"],
  },
  {
    cd_ref: "706492",
    classification: "flore",
    noms_scientifiques: ["Lobelia parva"],
    noms_vernaculaires: ["Lobélie petite"],
    cd_type_statuts: ["PD"],
  },
  {
    cd_ref: "1079427",
    classification: "flore",
    noms_scientifiques: [
      "Aconitum anthora subsp. anthora",
      "Aconitum anthora var. atrovirens",
      "Aconitum anthora var. confertiflorum",
      "Aconitum anthora var. eulophum",
      "Aconitum anthora var. glabriflorum",
      "Aconitum anthora var. grandiflorum",
      "Aconitum anthora var. inclinatum",
      "Aconitum anthora var. jacquinianum",
      "Aconitum anthora var. jacquinii",
      "Aconitum anthora var. patulum",
      "Aconitum anthoroideum",
      "Aconitum decandollei",
      "Aconitum eulophum",
      "Aconitum jacquinii",
      "Aconitum nemorosum",
      "Aconitum pseudanthora",
    ],
    noms_vernaculaires: ["Aconit anthore", "Aconit anthora", "Anthore", "Maclou"],
    cd_type_statuts: ["PR", "PD"],
  },
].map((espece) => ({ ...espece, cd_ref: espece.cd_ref as EspeceProtegeeCdRef }));

export async function seed(knex: Knex) {
  await replaceEspecesProtegees(ESPECES_PROTEGEES, knex);

  console.log(`  Seed espèces protégées OK (${ESPECES_PROTEGEES.length} espèces)`);
}
