import type { DossierFull } from "@pitchou/types/API_Pitchou.ts";

export const dossierFullColumns = [
  "dossier.id as id",
  "demarche_numerique_number",
  "demarche_number",
  "depot_date",
  "dossier.name as name",
  "description",
  "urgent_contact_phone",
  "request_context",
  "accompaniment_need",
  "intervention_start_date",
  "intervention_end_date",
  "intervention_duration",
  "no_other_satisfactory_solution_justification",
  "motif_derogation",
  "motif_derogation_justification",
  "file_especes_impactees.id as especes_impactees_id",
  "file_especes_impactees.name as especes_impactees_name",
  "file_especes_impactees.media_type as especes_impactees_media_type",
  "linked_to_ae_regime",
  "ae_procedures",
  "ae_other_procedure",
  "especes_prise_detention_limitee_type",
  "scientifique_mortality_measures_taken",
  "scientifique_mortality_measures_details",
  "eolien_commissioning_year",
  "eolien_turbines_count",
  "eolien_tip_height",
  "eolien_rotor_diameter",
  "eolien_ground_clearance",
  "eolien_monitored_turbines_count",
  "eolien_field_inventory_period",
  "eolien_monitoring_visits_count",
  "eolien_weekly_monitoring_visits_count",
  "eolien_mortality_actions",
  "eolien_carcass_collection_method",
  "eolien_carcass_preservation_method",
  "eolien_carcass_examination_address",
  "main_activite",
  "source",
  "departments",
  "communes",
  "regions",
  "location_scope",
  "primary_department",
  "projet_map",
  "next_action_expected_from",
  "identite_demandeur.last_name as deposant_last_name",
  "identite_demandeur.first_names as deposant_first_names",
  "identite_demandeur.email as deposant_email",
  "identite_mandataire.last_name as mandataire_last_name",
  "identite_mandataire.first_names as mandataire_first_names",
  "identite_mandataire.email as mandataire_email",
  "demandeur_personne_physique.last_name as demandeur_personne_physique_last_name",
  "demandeur_personne_physique.first_names as demandeur_personne_physique_first_names",
  "demandeur_personne_physique.email as demandeur_personne_physique_email",
  "demandeur_personne_physique.address as demandeur_personne_physique_address",
  "demandeur_personne_physique.phone as demandeur_personne_physique_phone",
  "demandeur_personne_physique.role as demandeur_personne_physique_role",
  "demandeur_personne_morale.siret as demandeur_personne_morale_siret",
  "demandeur_personne_morale.legal_name as demandeur_personne_morale_legal_name",
  "demandeur_personne_morale.address as demandeur_personne_morale_address",
  "demandeur_personne_morale.siren as demandeur_personne_morale_siren",
  "demandeur_personne_morale.legal_form as demandeur_personne_morale_legal_form",
  "demandeur_personne_morale.naf_code as demandeur_personne_morale_naf_code",
  "demandeur_personne_morale.naf_label as demandeur_personne_morale_naf_label",
  "demandeur_personne_morale.creation_date as demandeur_personne_morale_creation_date",
  "demandeur_personne_morale.admin_status as demandeur_personne_morale_admin_status",
  "demandeur_personne_morale.headcount as demandeur_personne_morale_headcount",
  "demandeur_personne_morale.share_capital as demandeur_personne_morale_share_capital",
  "demandeur_personne_morale.insee_code as demandeur_personne_morale_insee_code",
  "demandeur_personne_morale.postal_code as demandeur_personne_morale_postal_code",
  "demandeur_personne_morale.department as demandeur_personne_morale_department",
  "demandeur_personne_morale.region as demandeur_personne_morale_region",
  "identite_representant.last_name as representative_last_name",
  "identite_representant.first_names as representative_first_names",
  "identite_representant.email as representative_email",
  "identite_representant.phone as representative_phone",
  "identite_representant.role as representative_role",
  "ddep_required",
  "scientifique_demande_type",
  "scientifique_previous_assessment",
  "scientifique_demande_purposes",
  "scientifique_suivi_protocol_description",
  "scientifique_capture_mode",
  "scientifique_light_source_conditions",
  "scientifique_marking_conditions",
  "scientifique_transport_conditions",
  "scientifique_intervention_perimeter",
  "scientifique_intervenants",
  "scientifique_other_intervenants_details",
  "enjeu",
  "free_comment",
  "onagre_demande_identifier",
  "public_consultation_start_date",
  "public_consultation_end_date",
  "mesures_erc_planned",
  "er_mesures_sufficient",
  "dossier_oiseau_simple_compensated_nids_count",
  "dossier_oiseau_simple_destroyed_nids_count",
  "dossier.type as type",
  "ecological_inventory_completed",
  "especes_present_in_influence_area",
  "risk_despite_erc_mesures",
  "commissioning_date",
] as (keyof DossierFull)[];

export function joinDossierIdentities<T extends { leftJoin: Function }>(query: T): T {
  return query
    .leftJoin("identite_dossier as identite_demandeur", function (this: any) {
      this.on("identite_demandeur.dossier", "dossier.id").andOnVal(
        "identite_demandeur.type",
        "demandeur",
      );
    })
    .leftJoin("identite_dossier as identite_mandataire", function (this: any) {
      this.on("identite_mandataire.dossier", "dossier.id").andOnVal(
        "identite_mandataire.type",
        "mandataire",
      );
    })
    .leftJoin("identite_dossier as identite_representant", function (this: any) {
      this.on("identite_representant.dossier", "dossier.id").andOnVal(
        "identite_representant.type",
        "representant",
      );
    })
    .leftJoin("personne as demandeur_personne_physique", {
      "demandeur_personne_physique.id": "dossier.demandeur_personne_physique",
    })
    .leftJoin("entreprise as demandeur_personne_morale", {
      "demandeur_personne_morale.siret": "dossier.demandeur_personne_morale",
    })
    .leftJoin("file as file_especes_impactees", {
      "file_especes_impactees.id": "dossier.especes_impactees",
    });
}
