name: reviewdog
on: [pull_request]
jobs:
  tsc:
    name: Run tsc with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EPMatt/reviewdog-action-tsc@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: file
          fail_on_error: true
  svelte-check: 
    name: Run svelte-check with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - name: Install svelte-check
        run: npm install
      - name: Run reviewdog
        run: |
          npx svelte-check | reviewdog -reporter=github-pr-review -efm="%E%f:%l:%c" -efm="%CError: %m" -efm="%C\ %#%m" -efm="%-A%.%#" -name svelte-check -filter-mode file