name: Qualité de code

on: [pull_request]

#on: 
#  push:
#      branches:
#        - svelte-check-tower

jobs:
  tsc:
    name: Run tsc with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EPMatt/reviewdog-action-tsc@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: file
          fail_on_error: true

  svelte-check:
    name: Run svelte-check
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        # You can replace these steps with your specific setup steps
        # This example assumes Node 22 and pnpm 8
        - name: Setup Node 22
          uses: actions/setup-node@v4
          with:
              node-version: 22
              registry-url: https://registry.npmjs.org/

        - name: Setup PNPM
          uses: pnpm/action-setup@v3.0.0
          with:
              version: 8.12.1

        - name: Install
          run: pnpm install

        # Run the svelte check action
        - name: Svelte Check
          uses: ghostdevv/svelte-check-action@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            # filterChanges: false
            failOnError: true
  build:
      name: Test npm run build
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Node 22
            uses: actions/setup-node@v4
            with:
                node-version: 22
                registry-url: https://registry.npmjs.org/

          - name: Setup PNPM
            uses: pnpm/action-setup@v3.0.0
            with:
                version: 8.12.1

          - name: Install
            run: pnpm install

          - name: Test build
            run: pnpm run build