name: Test Build

on: [pull_request, push]

jobs:
  build:
    name: Test npm run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.12.1

      - name: Install dependencies
        run: pnpm install

      - name: Test build
        run: pnpm run build 